### ISSUE TITLE
Android studio / Android

### ISSUE THREAD

**Issue by FunnyDevs** [manifold-systems/manifold#10]
is possible to use Manifold with Android Studio projects??

**Comment by rsmckinney** [comment]
No, Manifold currently will not work with Android Studio.  Manifold works
with standard Java 8 or better, we don't plan to support Android Studio
until after Manfold's official release later this year.

Scott

**Comment by IMarksAvans** [comment]
Any update on Android Studio support?

**Comment by rsmckinney** [comment]
@IMarksAvans 

Hi Mark. Getting there.  There are some other features in the works on which Android support depends. For instance, I am currently finishing up decoupling some of the manifold libraries along with separating documentation etc. Once this is complete it will be easier to target android with specific parts of manifold.  The core library will be first.

**Comment by rsmckinney** [comment]
work in progress...

**Comment by rsmckinney** [comment]
Android Studio now supported with Manifold version 2020.1.13, and ]Manifold plugin for Android Studio](https://plugins.jetbrains.com/plugin/10057-manifold/update/88505) version 2019.2.15
