### ISSUE TITLE
String templates + Spring + Annotations = possible error

### ISSUE THREAD

**Issue by marcobehler** [manifold-systems/manifold#102]
Have a completely empty Spring project, with just one class like this:

```java
@Configuration
@PropertySources({
        @PropertySource(value = "classpath:application.properties", ignoreResourceNotFound = true),
        @PropertySource(value = "classpath:application-${spring.profiles.active}.properties", ignoreResourceNotFound = true)
})
public class DefaultConfig {
}
```

When you now have string templating enabled with Manifold, compilation will fail with an "java: package spring does not exist" error. I understand why that error happens and that @DisableStringLiteralTemplates is probably a sane workaround. 
Just wanted to trigger a discussion if string replacements in annotations is actually needed/feasible to change? 

![image](https://user-images.githubusercontent.com/4457254/60831330-9a399f00-a1b9-11e9-804e-6ee9286d3407.png)

**Comment by rsmckinney** [comment]
Hi @marcobehler.  That's a great question.  This has come up before with Spring and the answer is to disable string templates entirely or selectively with @DisableStringLiteralTemplates.  However, more use-cases have surfaced where specific parts of code should be filtered from string template processing.  To account for this I've added the capability for string templates to filter stuff, but it's internal.  I think for now I'll hard code a filter for Spring annotations, but I'll probably expose an API to formalize it. I'll keep this issue open until it's all settled.

So for now you can either:
1. remove the "strings" parameter from the -Xplugin:Manifold javac argument or
2. use @DisableStringLiteralTemplates where needed

But I'll likely have this fixed within 24 hours, I'll keep you posted.

**Comment by rsmckinney** [comment]
Update.  I added a 3rd option above (escape the $)

But I'm working out a solution to filter spring framework annotations from string templates.  As easy as escaping the $ is, most folks will trip over the issue because it is not obvious.

**Comment by rsmckinney** [comment]
Note this fix will be included in a new release due later this evening (PDT)

**Comment by dalegaspi** [comment]
> But I'm working out a solution to filter spring framework annotations from string templates. As easy as escaping the $ is, most folks will trip over the issue because it is not obvious.

@rsmckinney FYI for the most part it's fine now...i guess just for "common" Spring annotations (e.g., `@Value`)?  If i use Spring Retry's `@Retryable` annotation with (Spring) string interpolation as configuration, Manifold plugin would try to flag it as a warning.

<img width="747" alt="image" src="https://github.com/manifold-systems/manifold/assets/1777690/7eb4e88f-d500-4f99-93ab-6298f426cbaa">

**Comment by dalegaspi** [comment]
@rsmckinney another (relatively) minor thing: if i use `\` to escape `$`, spotless (at least with Google formatter...have not tried with other formatters) will complain about illegal escape character 
<img width="845" alt="image" src="https://github.com/manifold-systems/manifold/assets/1777690/0c61c4f9-d1d0-400f-b11f-4eed018c116b">

**Comment by rsmckinney** [comment]
@dalegaspi Not much can be done re google formatter on my side. Can you tell the formatter to ignore “illegal” escape chars? Legit illegal ones will be singled out by the compiler anyway.

**Comment by dalegaspi** [comment]
> @dalegaspi Not much can be done re google formatter on my side. Can you tell the formatter to ignore “illegal” escape chars? Legit illegal ones will be singled out by the compiler anyway.

yep, i don't expect that you'll be able to get around that...unfortunately, i did not find a setting to ignore it.  IMO, this is a bug for the formatter.
