### ISSUE TITLE
Jailbreak functionality not working

### ISSUE THREAD

**Issue by ciaranodc** [manifold-systems/manifold#104]
Hello. I have followed the set up instructions for Maven and Java 8 to the letter but it is not working.

[x] Add manifold-all dependency -> YES
[x] Configure the maven-compiler-plugin -> YES
[x] Add tools.jar dependency -> YES (tried as profile and within dependencies)

I am using the @Jailbreak annotation on a class with a private field. When I try and access this field later I am still seeing compile error "privateField has private access in com.example.MyClass". Also trying myClassInstance.jailbreak().myPrivateMethod() is saying "Cannot resolve method 'jailbreak()'". 

Any ideas as to what I'm missing?

**Comment by rsmckinney** [comment]
Hi @ciaranodc. Are the errors from the IntelliJ editor or from the compiler/build output?  I can probably find the problem quickly if I have access to your project.

**Comment by ciaranodc** [comment]
Hi @rsmckinney. Thanks for the reply. 

I cloned the **[manifold-sample-project](https://github.com/manifold-systems/manifold-sample-project)** repo and opened it in IntelliJ. I have pared the code down so it is using Java 8 and I am only testing Jailbreak functionality. So the only test/method getting run is useJailbreak(). And actually you are correct, the compile errors are in the IDE only but when I run 'mvn package' from command line the code runs through fine! 

Do you know what's up with IntelliJ?

**Comment by rsmckinney** [comment]
Hmm.  I've basically done the same exercise and it looks good on my end.  When you're all through making Maven changes remember to punch the `reimport`/`resync` button on the Maven tool window in IJ, otherwise IJ will be in a weird state.  Here's what I have:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>systems.manifold</groupId>
  <artifactId>manifold-sample-project</artifactId>
  <version>${manifold-version}</version>

  <properties>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
    <manifold-version>2019.1.7</manifold-version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <!--Use all core Manifold features with 'manifold-all' -->
    <dependency>
      <groupId>systems.manifold</groupId>
      <artifactId>manifold-all</artifactId>
      <version>${manifold-version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <!--
    *** JAVA 8 ***

    Add tools.jar from the jdk (exclusively for Java 8 usage)
  -->
    <profiles>
      <profile>
        <id>internal.tools-jar</id>
        <activation>
          <file>
            <exists>${java.home}/../lib/tools.jar</exists>
          </file>
        </activation>
        <dependencies>
          <dependency>
            <groupId>com.sun</groupId>
            <artifactId>tools</artifactId>
            <version>1.8.0</version>
            <scope>system</scope>
            <systemPath>${java.home}/../lib/tools.jar</systemPath>
          </dependency>
        </dependencies>
      </profile>
    </profiles>

  <build>
    <plugins>

      <!--
       *** JAVA 8 ***

       Configure the maven-compiler-plugin use Manifold.
       - add the -Xplugin:Manifold argument for the javac compiler
      -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
          <configuration>
            <encoding>UTF-8</encoding>
            <compilerArgs>

              <arg>-Xplugin:Manifold strings exceptions</arg>

            </compilerArgs>
          </configuration>
        </plugin>

    </plugins>
  </build>

</project>
```
![image](https://user-images.githubusercontent.com/588843/61082326-17455e00-a3de-11e9-8570-616ea1fdec5e.png)

**Comment by rsmckinney** [comment]
One other thing.  Remember to set the IJ SDK to Java 8 too, I forget that sometimes.

**Comment by ciaranodc** [comment]
I have the exactly the same. I copied and pasted your _pom.xml_ from above just to be sure. And yes, platform SKD, project SDK, project language level, module SDK, and module language level are all set to 1.8. There must be something else going on specific to my system. I'll leave it for now.

Thanks for your help.

**Comment by rsmckinney** [comment]
I'm curious what could be wrong.  What version of the Manifold IJ plugin are you using?

**Comment by ciaranodc** [comment]
It's v2019.1.7

**Comment by ciaranodc** [comment]
Hmm... I wonder is this the cause. I just made an edit to the pom.xml and a warning appeared: 
"Your copy of the Manifold plugin is not licensed or your license has expired. For uninterrupted use of the plugin please visit the JetBrains Marketplace to directly create or update your Manifold plugin subscription"

I selected the 30-day trial option when installing the plugin via IntelliJ marketplace. I also uninstalled that plugin tried installing manually from disk after downloading from here: [https://plugins.jetbrains.com/plugin/10057-manifold/pricing#edition=personal](https://plugins.jetbrains.com/plugin/10057-manifold/pricing#edition=personal)

Again I got the same warning message. This shouldn't happen right? I'm only just trying to use this for the first time today.

![Screen Shot 2019-07-11 at 17 22 05](https://user-images.githubusercontent.com/1556467/61089612-520cbd80-a401-11e9-8447-9fe05b13313c.png)

**Comment by rsmckinney** [comment]
The Jetbrains Marketplace is brand new, I'm not sure they handle the case where you download it and install it manually.  Can you try uninstalling it and then reinstalling it from the Marketplace?

**Comment by ciaranodc** [comment]
Yes, that is what I did the first time and I see that warning message. I have tried uninstalling and reinstalling through IntelliJ -> Settings -> Plugins once again but no luck. The link in the message brings you to the market place so I tried the 'download and install manually' option but I got the same warning message. I don't know if this warning message is actually what's causing the compile errors in IntelliJ though.

**Comment by rsmckinney** [comment]
Ok, something is clearly wrong with the license verification.  That message comes directly from the pluign only if the license check with JetBrains fails.

I would like to notify my contact at JetBrains regarding this incident and get you in contact with them.  I'm hopeful they'll quickly work this out with you.  Would you mind [sending me an email](mailto:scott@manifold.systems) with your contact info?

**Comment by ciaranodc** [comment]
Email sent. Thanks.
