### ISSUE TITLE
Sync in IntelliJ not quite right

### ISSUE THREAD

**Issue by marcobehler** [manifold-systems/manifold#105]
Hey Scott,
I was just trying to record a video about Manifold but ran into some issues. The short version is, it seems to me that IDE support is only working properly after "refreshing the Maven project" in idea.

I tried to add some properties to the project and reference them inside an app class. Then tried to rebuild/build the project/clean etc. Which doesn't really work until I refresh the Maven project. Have a look at what I tried to do here:

https://youtu.be/3djLa8SWO4k   (success at the end)

Am I doing anything wrong?

Using Java 12. The latest IntelliJ Version and your latest plugin version.

**Comment by marcobehler** [comment]
Just fixed the youtube link.

**Comment by rsmckinney** [comment]
Hi @marcobehler.  Ah, looking at your video I see the problem.  Manifold does not support the `default` package for resources.  If you put your resources in a directory within your resource root, it'll all come together.  Sorry the documentation is not clear on that.

**Comment by marcobehler** [comment]
Yup, I noticed the default root thing, but then again ,in the video, I am putting the properties file in a directory right from the start. ("Config"). Or?

**Comment by rsmckinney** [comment]
Ah right.  Ok, I can't reproduce the problem.  One thing: if you've made changes to your pom file before you started using it, you have to sync with intellij, which may explain why it started working after you synced.

I think if you start fresh, make sure you sync IntellIJ with Maven after your pom changes are complete, everything should work.  I didn't see in your video when you created the Test.properties file or what transpired before or immediately after, so it's difficult to say.

In any case I want to be sure all is well, and if not, I want to be able to reproduce the issue.  So if you still see a problem, can you provide steps to reproduce?  Thanks!

**Comment by marcobehler** [comment]
sorry @rsmckinney , this week has been super busy so far. I'll try and record a new bug showcase in the next couple of days. Thanks!

**Comment by rsmckinney** [comment]
No problem @marcobehler.  Whenever you find the time.  Thanks for helping!

**Comment by rsmckinney** [comment]
Unable to reproduce
