### ISSUE TITLE
[ENHANCEMENT] Add Maven/Gradle coordinates to docs

### ISSUE THREAD

**Issue by hron84** [manifold-systems/manifold#110]
You never write down Maven / Gradle coordinates for Manifold which is required to use it in any project. Please add these info to the `README.md` because this info is quite buried in the documentation.

**Comment by rsmckinney** [comment]
Please select the “Learn More” link at the bottom of the page, which takes you to the [documentation](http://manifold.systems/docs.html).  From there find the [Setup](http://manifold.systems/docs.html#setup) section. Let us know if you have questions.

**Comment by rsmckinney** [comment]
Also the website + readme filed are undergoing incremental changes over the next week.  The changes include building up the readme files, standardizing them, and overall shifting documentation focus more toward Manifold’s individual projects and away from the current monolithic docs.  Keep a lookout!
