### ISSUE TITLE
Support XSD/XML Type Manifold

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#111]
Support XSD (XML) via type manifold

Initial thoughts:
Use XJC (via JAXB) to dynamically produce source
- see https://dzone.com/articles/running-jaxb-xjc-compiler-with-openjdk-11
- use version 2.3.0 because it works with jdk 9, but is not a full module JPMS monster

**Comment by sporkisfaster** [comment]
Looking through the commits and some source it seems you have an xml parser? Is that related to this?

**Comment by rsmckinney** [comment]
@sporkisfaster Hey long time.  The XML parser will likely be used for the XSD Manifold, however it was created for use with other manifolds where an XML file is used to define or contribute to a separate type.  For example, an XSD file might define a Person element which the XSD Manifold exposes indirectly as a Java Person type, thus the XML is just a the I/O for the XSD defined type. You could also have XML files where XSDs don't matter; the data in the files corresponds with one or more logical types you care about.  A manifold for this set of XML files needs an XML parser to make sense of the data.  The only real reason I created this parser was to encode location information for XML elements and attributes for use with code navigation in IDEs (off the shelf XML parsers do not preserve that level of info).

**Comment by sporkisfaster** [comment]
Gotcha. Is there anything I/community can do to assist with the XML manifold? I've suddenly run into a use case for it

**Comment by rsmckinney** [comment]
Do you want to use XSD or plain XML?  If the latter, you are talking about a custom Manifold that uses the XML parser, I can help you get started on that.  If the former, I can bump the priority of the XSD manifold, but no promises on when that work begins, sorry.

**Comment by sporkisfaster** [comment]
Yes just on an XML basis.

**Comment by sporkisfaster** [comment]
Should we keep the discussion in the issue or offline it? Also preemptive thanks for the help! Love this tool

**Comment by rsmckinney** [comment]
I'll move the discussion to a [separate issue](https://github.com/manifold-systems/manifold/issues/130). Thanks, I appreciate the support!
