### ISSUE TITLE
manifold-exceptions doesn't handle method refs unless manifold-all is depended upon

### ISSUE THREAD

**Issue by StrangeNoises** [manifold-systems/manifold#115]
**Describe the bug**
`manifold-exceptions` does not trap and handle when a method ref of a method throwing a checked exception is used... unless the declared dependency is for `manifold-all` instead of `manifold-exceptions`. Using a lambda is fine, just not a methodref.

**To Reproduce**
1. Create a trivial project using `gradle init --type java-application`
2. Modify App.main to include a near reproduction of the example in the `manifold-extensions` readme
3. Try to run it.

By *near* reproduction I mean, pasted in verbatim it couldn't work. So instead:

```java
        List<String> strings = List.of("http://example.com", "https://google.com");
        List<URL> urls = strings.stream()
          .map(URL::new) // Mmm, life is good
          //.map(s -> new URL(s)) // life finds a way
          .collect(Collectors.toList());
        urls.forEach(System.out::println);
```

With the project depending on `manifold-exceptions` this does indeed fail to compile with the MalformedURLException as you would normally expect. Comment that line out and uncomment the following line which uses the lambda form, and all is well. The URLs are printed.

If you depend instead on `manifold-all`, and make no code changes at all, it all works. As does being able to just use List::map from the `manifold-collections` dependency (ie: removing `.stream()`). It would appear maybe something is missing from the narrow dependency on `manifold-exceptions`?

(Depending on `manifold-all` on my (non-modular) bigger project fails to compile at all at the moment, with many errors including mostly `class (x) in module  not exported` errors (note missing module name) even though I'm not attempting to use any other manifold features yet. But that'll be another story. For this issue it just means the workaround of depending on `manifold-all` won't work for me right now.)

**Expected behavior**
When depending only on `manifold-exceptions`, it should handle method refs.

**Desktop (please complete the following information):**
- OS Type & Version: Linux x64 (Ubuntu 19.10)
- Java/JDK version: AdoptOpenJDK 11.0.4+11
- IntelliJ IDEA version: N/A
- Gradle version: 5.5
- Manifold version: 2019.1.11
- Manifold IntelliJ plugin version: N/A

**Comment by rsmckinney** [comment]
@StrangeNoises

Hi Rachel.  Thanks for reporting this issue!  Yes indeed there is a missing dependency in `manifold-exceptions`, it should have `manifold-ext` as a dependency.  This is fixed in the next manifold release coming later this week. For the time being you can add `manifold-ext` to your project's dependencies.  You can also substitute both with `manifold-all` as you have discovered.

Regarding `class (x) in module not exported` I'd be happy to help diagnose the problem if you can share your project using github or otherwise.  You can share it privately if you prefer, my email: scott@manifold.systems.  If you'd rather report a separate issue with steps to reproduce, that works too.

Thanks again for reporting this!

**Comment by rsmckinney** [comment]
@StrangeNoises 

Hello again.  First, I'm going to have a build ready for your two issues, probably by tomorrow morning PDT.  I'll update this issue when it's available.  Next, we tend to use Maven for most everything related to Manifold, so please excuse our Gradle Fail.  I've put together an actual working `build.gradle` file for a basic project:

```groovy
plugins {
    id 'java'
}

group 'com.example'
version '1.0-SNAPSHOT'

targetCompatibility = 11
sourceCompatibility = 11

repositories {
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

dependencies {
    compile group: 'systems.manifold', name: 'manifold-all', version: '2019.1.11'
    testCompile group: 'junit', name: 'junit', version: '4.12'

    // Add manifold to -processorpath for javac
    annotationProcessor group: 'systems.manifold', name: 'manifold-all', version: '2019.1.11'
}

compileJava {
    doFirst() {
        // If you DO NOT define a module-info.java file:
        options.compilerArgs += ['-Xplugin:Manifold']

        // if you DO define a module-info.java file:
        //options.compilerArgs += ['-Xplugin:Manifold', '--module-path', classpath.asPath]
        //classpath = files()
    }
}

sourceSets {
    main {
        output.resourcesDir = "build/classes/java/main"
    }
    test {
        output.resourcesDir = "build/classes/java/test"
    }
}
```

>Notice the `compileJava` directive defines separate steps depending on whether or not you define a `module-info.java` file.  These are mutually exclusive, comment out the one that does not apply.

Unlike Maven, Gradle requires detailed (boilerplate) steps to define the module-path and classpath for a modular project. Gradle also requires `resourceDir` to be remapped to the classpath. _shrug_

Please let me know if these changes help resolve the issue your having, I'd like to get to the bottom of the problem. Thanks!

**Comment by StrangeNoises** [comment]
Can confirm with 2019.1.12 (and gradle 5.6 as per the other issue) a trivial application only depending on manifold-exceptions does now work with method refs, so i'll be closing this issue.

Extras:

1. I didn't seem to need to set the resourcesDir, did you find that was needed for a modular app? as I didn't try that. It's possible the test app was *too* trivial (no actual resources)...

2. I'm not able to share the "bigger" project as it's not so much mine but my employer's, and even if we could opensource it we've still got some more embarrassing technical debt to pay down before i'd want to ;-) (Trying this out is part of that longrunning process (we have been bitching for *years* about checked exceptions, doubly so since java.util.function appeared), as was replacing an ancient rats' nest of build scripts with gradle last year...) It's got a number of subprojects some of which already have their own annotation processors and non-annotation-based code generators, so I just need to narrow those errors down anyway and then hopefully produce a test-case reproducing it. That is assuming 2019.1.12 didn't fix it for the case where i only want to use manifold-exceptions at present anyway. (It only happened when I tried to depend on manifold-all, but some of the (x) classes were in manifold-ext.) I'll test later but obvs it belongs in its own issue which I'll raise as and when I'm able to do that. Just noted in passing here.

**Comment by rsmckinney** [comment]
> 1. I didn't seem to need to set the resourcesDir, did you find that was needed for a modular app? as I didn't try that. It's possible the test app was too trivial (no actual resources)...

This is necessary only if your project has resources, otherwise no need.

> 2. I'm not able to share the "bigger" project as it's not so much mine but my employer's

No problem
