### ISSUE TITLE
Spurious warnings relating to java.util.Map when manifold-ext depended upon

### ISSUE THREAD

**Issue by StrangeNoises** [manifold-systems/manifold#116]
**Describe the bug**
This is the issue already mentioned in passing in #115. Building projects with manifold-exceptions depended upon (which now further depends on manifold-ext) produces these compiler warnings for each subproject.

Note they are *warnings*. I was eventually able to reproduce it even on a trivial application by just having `import java.util.Map` at the top, not even using a Map in the class, and using `-Xlint:all` in the compiler args. As such this probably isn't really a bug, and not a showstopper; it's just warnings being thrown, and we happen to throw nearly all of them in our main project. (We do suppress some of them, but [rawtypes] in particular is one i want to be yelled at for doing in my own code. OTOH I don't mind suppressing [exports] generally as we're not attempting modular builds yet.)

So the request would be if you could suppress (or resolve) those warnings at source; in this case it looks like the methods in `MapStructExt.java` and `ICallHandler.java` being echoed in generated code, but remember when I depended on manifold-all there were many more.

BTW is it possible to direct things such that the intermediate generated class sources are left behind after compilation so I can look at what this is all actually doing to the code? :-) At the moment in gradle it looks like it's leaving behind an empty folder `build/generated/sources/annotationProcessor/java/main`.

```
~/manifold 
➜ ./gradlew clean classes  

> Task :compileJava
java/util/Map.java:105: warning: [rawtypes] found raw type: Class
  default public java.lang.Object call(java.lang.Class arg1, java.lang.String arg2, java.lang.String arg3, java.lang.Class arg4, java.lang.Class[] arg5, java.lang.Object[] arg6) {
                                                ^
  missing type arguments for generic class Class<T>
  where T is a type-variable:
    T extends Object declared in class Class
java/util/Map.java:105: warning: [rawtypes] found raw type: Class
  default public java.lang.Object call(java.lang.Class arg1, java.lang.String arg2, java.lang.String arg3, java.lang.Class arg4, java.lang.Class[] arg5, java.lang.Object[] arg6) {
                                                                                                                    ^
  missing type arguments for generic class Class<T>
  where T is a type-variable:
    T extends Object declared in class Class
java/util/Map.java:105: warning: [rawtypes] found raw type: Class
  default public java.lang.Object call(java.lang.Class arg1, java.lang.String arg2, java.lang.String arg3, java.lang.Class arg4, java.lang.Class[] arg5, java.lang.Object[] arg6) {
                                                                                                                                          ^
  missing type arguments for generic class Class<T>
  where T is a type-variable:
    T extends Object declared in class Class
java/util/Map.java:5: warning: [exports] interface ICallHandler in module  is not exported
public abstract interface Map<K, V> extends manifold.ext.api.ICallHandler {
                                                            ^
4 warnings

BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed

```

**To Reproduce**

1. Take a trivial app, such as generated by gradle --init type=java-application

2. Add the dependency on manifold-exceptions. Add `-Xlint:all` to the compilerArgs.

3. Edit a class to `import java.util.Map`. It's not necessary to actually try to *use* it, let alone to use manifold features on it. Just import it.

4. Build.

**Desktop (please complete the following information):**
- OS Type & Version: Linux x64 (Ubuntu 19.10)
- Java/JDK version: AdoptOpenJDK 11.0.4+11
- IntelliJ IDEA version: N/A
- Gradle version: 5.6
- Manifold version: 2019.1.12
- Manifold IntelliJ plugin version: N/A

**Comment by rsmckinney** [comment]
@StrangeNoises 

Ah, we don't build with `Xlint:all`, but should probably test with it.  The warnings are harmless and will be fixed in the generated code.

>BTW is it possible to direct things such that the intermediate generated class sources are left behind after compilation so I can look at what this is all actually doing to the code? :-) At the moment in gradle it looks like it's leaving behind an empty folder `build/generated/sources/annotationProcessor/java/main`.

Manifold never generates code to disk; that folder is never used. It is generated automatically when annotation processing is enabled.  However, the manifold build process should either find a way to avoid its creation or at least remove it afterward.

`manifold-exceptions` does not change the generated code, instead it suppresses compile errors that would otherwise prevent code from compiling, therefore there are no intermediate sources or other modified sources to see.  Other manifold dependencies *do* effect generated source and/or bytecode.  For instance, all *type manifolds* such as the JSON and GraphQL libraries dynamically create types corresponding with resource files as the compiler resolves type names.  You can examine the source for any resource using the Manifold plugin for IntelliJ IDEA.  Are you using the plugin?

**Comment by StrangeNoises** [comment]
I think the main anxiety here is side-effects: that manifold might be altering the code that runs *even when no actual manifold-provided features are in use.* Stuff being spat out by the compiler kind of gives that impression. :-) I just want the confidence to know that if I'm *not* using any manifold features in a given class, the class will be completely unaltered compared to if manifold isn't set up on the project at all.

(I don't actually compile with `-Xlint:all` either, or rather I do, but with a list of exceptions following, as some of them are truly ridiculous. I don't mind adding -exports to that list but as i'm not attempting modular builds yet I can't say whether that's a warning that ought actually to be heeded.)

Suppressing the creation of the generated annotationProcessor directory is... low priority! I only mentioned it on the offchance it was an artefact of source actually having been generated and deleted.

I'm checking out another issue where an extra exception is being thrown out of javac after reporting on any other compiler errors - only in the subprojects which also have our own annotation processors on them. There may be some interaction there, and I need to confirm it's not that our APs are misbehaving.

**Comment by rsmckinney** [comment]
>I think the main anxiety here is side-effects: that manifold might be altering the code that runs even when no actual manifold-provided features are in use. Stuff being spat out by the compiler kind of gives that impression. :-)

Ah sure.  The `Map` class is a special case within the `manifold.ext` dependency.  Internally javac's view of `Map` is slightly altered, however its behavior in terms of your project's use of `Map` is unchanged _**unless**_ you use the structural interfaces on `Map`. In general unless you begin using structural interfaces or other features provided by `manifold-ext` Manifold stays out of your bytecode.

>I'm checking out another issue where an extra exception is being throw

Gotcha.  Please let me know if you suspect an issue with Manifold.

Cheers!
