### ISSUE TITLE
not support multproject

### ISSUE THREAD

**Issue by wxq1990** [manifold-systems/manifold#120]
create a extension method in project A,can not be used in project B.
compile error: cannot find symbol

**To Reproduce**
1. create extension method in project A
2. use the extension method in project B
3. compile/run project  B

**Screenshots**
![)2W ( 74J8RSNRKA8U6@1E6](https://user-images.githubusercontent.com/10300594/65116278-40f0b600-da1b-11e9-90ff-e5c9a4eea1e6.png)

**Desktop (please complete the following information):**
- OS Type & Version: win10
- Java/JDK version:openjdk11
- IntelliJ IDEA version:2019.2.2
- Manifold version:2019.1.14
- Manifold IntelliJ plugin version: 2019.1.14

**Comment by rsmckinney** [comment]
You probably need to add the `Contains-Sources` key to your jar's manifest entries.  Please read the documentation regarding this at [Extension Libraries](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-libraries).  Thanks.

**Comment by wxq1990** [comment]
i see thanks
