### ISSUE TITLE
Setup guide

### ISSUE THREAD

**Issue by terryBaz** [manifold-systems/manifold#128]
The docs are very poor from the view of a beginner, there is no simple setup guide, and links like `http://manifold.systems/docs.html#setup` and `http://manifold.systems/docs.html#maven` are not working any more (for my case I want a simple guide to setup the Manifold plugin for java 8).

**Comment by rsmckinney** [comment]
@terryBaz Hi. Where do you see those links? e.g., http://manifold.systems/docs.html#setup?  They are obsolete and should not be referenced anywhere from Manifold's documentation.

All of the docs have been updated and subdivided into projects.  For instance, the `manifold-all` project has its own README.md file accessible from Manifold's main index. 
 There you can find the Java 8 setup for maven: https://github.com/manifold-systems/manifold/tree/master/manifold-all#maven

**Comment by terryBaz** [comment]
Hello, @rsmckinney 
[those links (and others) appears 32 times in docs (also in FAQ, and some articles on the net!)](https://github.com/manifold-systems/manifold/search?q=http%3A%2F%2Fmanifold.systems%2Fdocs.html%23setup&unscoped_q=http%3A%2F%2Fmanifold.systems%2Fdocs.html%23setup)
if you want let me PR a fix.
Thanks

**Comment by rsmckinney** [comment]
@terryBaz Thanks!  Note a lot of those are in files that are no longer published on the website, but they should be fixed nonetheless. (i don't like broken links either)  Cheers!

**Comment by rsmckinney** [comment]
Added content for http://manifold.systems/docs.html#setup
