### ISSUE TITLE
Manifold IntelliJ plugin not properly identifying a use case.

### ISSUE THREAD

**Issue by williamfu4github** [manifold-systems/manifold#129]
**Describe the bug**
I am using Manifold @extension with java generics in IntelliJ IDEA with the manifold plugin.
The plugin seems to be not properly identifing a use case: when a generic type returned from a @extension function is assigned directly to its super type, IntelliJ complains about "incompatible types" and mark the line in red, although code can compile (I can compile it both in IntelliJ and maven on command line). When I write the exactly same function in the same class of drive code without @extension, IntelliJ don't show the error.
I have attached the minimal working code snippet below.
The code snippet mimics Google Guava's ImmutableSet.of(), which doesn't have "incompatible types" in IntelliJ.

**To Reproduce**
1. copy and paste the code snippet in IntelliJ
2. you should see the error line
3. try compile it. It will compile

**Expected behavior**
IntelliJ don't prompt "incompatible type" error.

**Desktop:**
- OS Type & Version: OSX Sierra 10.12.6
- Java/JDK version: jdk1.8.0_202
- IntelliJ IDEA version: 2019.2.1 Community Edition
- Manifold version: 2019.1.22
- Manifold IntelliJ plugin version: 2019.2.3

**Additional context**
```
@Extension
public class JavaSetExtension {
    @Extension
    public static <E> Set<E> of(E e1) {
        return Stream.of(e1)
                .toSet();
    }
}

public class Driver {
    public static <E> Set<E> of(E e1) {
        return Stream.of(e1)
                .toSet();
    }

    @Test
    void test() {
        // IntelliJ mark this as an error
        Set<Object> ints = Set.of(new Integer(3));
        // This is fine, not using extension
        Set<Object> ints2 = Driver.of(new Integer(3));
        // This is also fine, using google Guava
        Set<Object> ints3 = ImmutableSet.of(new Integer(3));
    }
}
```

**Comment by williamfu4github** [comment]
I understand I can always go with Set.<Object>of(new Integer(3)). That actually fix the IntelliJ issue. I am only raising this issue because the version without @Extension work.... and explicitly give the generic type is sometimes just annoying.

**Comment by williamfu4github** [comment]
I understand I can always go with Set.<Object>of(new Integer(3)). That actually fix the IntelliJ issue. I am only raising this issue because the version without @extension work.... and explicitly give the generic type is sometimes just annoying.

**Comment by williamfu4github** [comment]
I understand I can always go with ```Set.<Object>of(new Integer(3))```. That actually fix the IntelliJ issue. I am only raising this issue because the version without @extension work.... and explicitly give the generic type is sometimes just annoying.

**Comment by williamfu4github** [comment]
I understand I can always go with ```Set.<Object>of(new Integer(3))```. That actually fix the IntelliJ issue. I am only raising this issue because the version without @extension works.... and explicitly give the generic type is sometimes just annoying.

**Comment by rsmckinney** [comment]
@williamfu4github Hi.  Interesting bug.  For some reason the inference from the LHS (Object) is not happening.  However the inference from the RHS is fine (Integer): 
```java
Set<Integer> ints = Set.of(new Integer(3));
```
This is what you want for most cases, but it should infer the other way too. Thanks for submitting this!

*Note this issue is limited to the IntelliJ plugin, it works file in the compiler.*

**Comment by williamfu4github** [comment]
In case the LHS type is abstract, you would have to use the concrete type on RHS.

One canonical example:
```
class abstract Vehicle {}
class Car extends Vehicle {}

Set<Vehicle> vehicles = Set.of(new Car());
```

**Comment by williamfu4github** [comment]
In case the LHS type is abstract, you would have to use the concrete type on RHS.

One canonical example:

```Java
class abstract Vehicle {}
class Car extends Vehicle {}

Set<Vehicle> vehicles = Set.of(new Car());
```

**Comment by williamfu4github** [comment]
In case the LHS type is abstract, you would have to use the concrete type on RHS.

One canonical example:

```Java
abstract class Vehicle {}
class Car extends Vehicle {}


Set<Vehicle> vehicles = Set.of(new Car());
```

**Comment by rsmckinney** [comment]
Sure. That needs to work (there is a bug here!) however in most cases, especially where the collection is immutable as with `Set.of()`, you want the more specific type -- most of the time you want the type inferred from the RHS.  In fact with Java 10 and beyond most of the time you'll write:
```java
var cars = Set.of(new Car());
```

**Comment by rsmckinney** [comment]
Won't fix
