### ISSUE TITLE
Unexpected token error of array assignment in IntelliJ

### ISSUE THREAD

**Issue by yueliangwen** [manifold-systems/manifold#139]
**Describe the bug**
I just install the manifold plugin, but get an "unexpected token" error in IntelliJ.

**To Reproduce**
1. copy and paste the code snippet in IntelliJ
2. you should see the error prompts
3. it can compile

**Expected behavior**
IntelliJ doesn't prompt an "unexpected token" error.

**Screenshots**
Prompt "unexpected token"  and "not a statement"

![image](https://user-images.githubusercontent.com/1107708/68821402-383df880-06c9-11ea-9030-635e499685d0.png)

![image](https://user-images.githubusercontent.com/1107708/68821387-278d8280-06c9-11ea-82a8-a2150de35648.png)

**Desktop (please complete the following information):**
- OS Type & Version: macOS Catalina (10.15.1)
- Java/JDK version: jdk1.8_192
- IntelliJ IDEA version: 2019.2.4 Ultimate Edition
- Manifold version: 2019.1.26
- Manifold IntelliJ plugin version: 2019.2.5

**Additional context**
 ```
 private void testMethod() {
    String[] strings = new String[1];
    strings[0] = "tips";
  }
```

**Comment by rsmckinney** [comment]
@yueliangwen Hi. This is a bug with the IntelliJ plugin, not Manifold itself.  It will be fixed for the next plugin release, within 10 days.  For now you can safely ignore it. Thanks for reporting this issue!

**Comment by yueliangwen** [comment]
Thanks @rsmckinney , it's great.

**Comment by rsmckinney** [comment]
A fix is implemented and will be included in the next release coming soon
