### ISSUE TITLE
Embedded graphql  cannot resolve symbol in IntelliJ

### ISSUE THREAD

**Issue by yueliangwen** [manifold-systems/manifold#140]
**Describe the bug**
It worked well at first in IntelliJ when I use Embedded graphql, but the manifold plugin is broken. IntelliJ shows "cannot resolve symbol" error tips.

**To Reproduce**
1. copy and paste the code snippet in IntelliJ
2. restart IntelliJ
3. you should see the error prompts
4. it can compile

**Expected behavior**
IntelliJ doesn't prompt  " cannot resolve symbol " error when restart.

**Screenshots**
Prompt "cannot resolve symbol."

![image](https://user-images.githubusercontent.com/1107708/69118654-2bf1db00-0acf-11ea-8985-28f1ce4ad466.png)

**Desktop (please complete the following information):**
- OS Type & Version: macOS Catalina (10.15.1)
- Java/JDK version: jdk1.8_192
- IntelliJ IDEA version: 2019.2.4 Ultimate Edition
- Manifold version: 2019.1.28
- Manifold IntelliJ plugin version: 2019.2.5

**Additional context**
```
/* [> MyEmbedded.graphql <]
    query MyOneAnimal($id: ID!) {
        animal(id: $id) {
            id
            name
            kind
            nationality
        }
    }*/
    MyEmbedded.MyOneAnimal myOneAnimal = MyEmbedded.MyOneAnimal.builder("1").build();
```

**Comment by rsmckinney** [comment]
@yueliangwen Hi.  Note that problem is specific to embedding, which is experimental. A quick way to "fix" it: press the refresh button on the Maven tool window.

**Comment by yueliangwen** [comment]
@rsmckinney I use Gradle as a building tool. I press the refresh button, but it doesn't work. I comment code and then uncomment, it will be fine. If I press the refresh button, the worked code will become broken again.

**Comment by rsmckinney** [comment]
@yueliangwen Right, sorry, I meant Gradle button ;)  Glad you can work around it.  I'll loop back on the embedding soon and fix this.  Thanks for reporting this!

**Comment by rsmckinney** [comment]
Fixed with https://github.com/manifold-systems/manifold-ij/commit/5e63cdf0f265f964e0dc7b4d476e8041632f5a93
