### ISSUE TITLE
Support for the VS Code IDE

### ISSUE THREAD

**Issue by gae123** [manifold-systems/manifold#142]
I started using this technology to call GQL from a Java client. I am very impressed.

However, we use VS Code as our IDE and without IDE support guessing the generated method names etc is very challenging.

Please consider a VS Code plugin..

**Comment by rsmckinney** [comment]
Excellent suggestion.  I'll have a look at the VS Code extension API, with any luck it'll provide the necessary hooks.  Manifold is currently supported exclusively on IntelliJ IDEA.  Other IDEs on the list include Eclipse and NetBeans, but (shhhh) I think I'm going to support VS Code first.  Thanks again for suggesting this!

**Comment by rsmckinney** [comment]
A cursory examination of the VS Code extension API reveals the Java LSP is a retread of the Eclipse JDT running in the background (LOL). I was hoping for a nicer architecture similar to IntelliJ IDEA.  The silver lining: implementing a Manifold plugin for Eclipse equates to implementing a plugin for VS Code.  I guess my work is cut out.

**Comment by rsmckinney** [comment]
Relates to: https://github.com/manifold-systems/manifold/issues/18

**Comment by rsmckinney** [comment]
in progress

**Comment by rsmckinney** [comment]
I've suspended further development on this, will consider reopening at a later date.

**Comment by ivarec** [comment]
Just a suggestion: you could remove this from the roadmap at https://manifold.systems/roadmap.html

**Comment by rsmckinney** [comment]
Heheh. Thanks. I still haven't quite ruled it out.

**Comment by Gaming32** [comment]
Why was development suspended? Especially since Eclipse is such a commonly used IDE? (Yes, I'm aware this is the VSCode thread, but I use VSCode, and VSCode just uses Eclipse)

**Comment by rsmckinney** [comment]
Hi @Gaming32.  Put simply, I don’t have the time. Manifold itself  + the IntelliJ plugin are quite a lot for a side project. Adding an Eclipse plugin would send me to divorce court.

**Comment by Gaming32** [comment]
The problem is that I legit can't use Manifold unless it has some sort of VSCode support. Can you add support for APT at least? (also I feel like this is the second time I'm writing this, but I guess it's not)

**Comment by rsmckinney** [comment]
Hi @Gaming32. Can you explain why you need VSCode support?  Would APT support be enough to justify using manifold with VSCode as-is?

I'm not quite sure what APT support entails, sorry, I'm not a frequent linux user and know little about apt beyond it being a packaging/deployment tool.  If supporting APT isn't crazy, I'll have a look at implementing that.

Also, a couple of recent developments:
 
- I may be assisting a company some time next year to build a manifold LSP plugin for VSCode. It will implemented by them and it was agreed to be shared and open source. I don't think they are looking at full coverage of manifold, probably just the features they require. The ball is currently in their court, I'm not sure of the timeframe. 

- JetBrains is working on a new "light weight" IDE: _Fleet_.  At least part of the plugin API will be LSP-based. If there is enough overlap between their LSP (it's not quite standard) and VSCode LSP, that will change my outlook toward supporting VSCode.

**Comment by Gaming32** [comment]
By APT support, I meant Annotation Processing Tool, not Linux Aptitude. The Eclipse JDT supports APT through Maven, with some fiddling.

**Comment by rsmckinney** [comment]
Ah, ok that makes more sense

**Comment by rsmckinney** [comment]
@Gaming32 It’s open now.

**Comment by Gaming32** [comment]
Do you have a Discord or some other way we could talk more in real time? I think I have Eclipse JDT AST manipulation almost down, but I don't really understand how Manifold itself works, so I need some help with that.

**Comment by rsmckinney** [comment]
The [Slack channel](https://join.slack.com/t/manifold-group/shared_invite/zt-e0bq8xtu-93ASQa~a8qe0KDhOoD6Bgg) is probably the right place for this. I'm there on and off throughout the day.

**Comment by iwangbowen** [comment]
Any progress
