### ISSUE TITLE
Intellij Inspections Problem

### ISSUE THREAD

**Issue by MegaCrafter** [manifold-systems/manifold#144]
**Describe the bug**
Intellij IDEA doesn't recognize syntax alterations of manifold. But programs run without any errors.

**To Reproduce**
1. Install the Manifold plugin from Intellij marketplace.
2. Create a new Gradle project. (I tried with maven as well but the problem was still the same)
3. Copy the whole sample build.gradle script from manifold-all github page. (https://github.com/manifold-systems/manifold/tree/master/manifold-all#setup) (I tested for both java 8 and java 11)
4. Write a code that manifold changes syntax for. (Screenshot will demostrate better)
5. As a result, Intellij tells me that line has errors but when I build&run, no build errors occur and the program runs fine.

**Expected behavior**
Intellij should give code completions about manifold's syntax and should recognize the code before I build.

**Screenshots**
![image](https://user-images.githubusercontent.com/11876549/69913919-fcd45580-144e-11ea-98a6-7b799a81456b.png)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: Tested for both Java 8 and Java 11 with respectable JDK
- IntelliJ IDEA version: 
![image](https://user-images.githubusercontent.com/11876549/69913935-2f7e4e00-144f-11ea-9848-5da4c945fb7e.png)
- Manifold version: 2019.1.29
- Manifold IntelliJ plugin version: 2019.3.7

**Comment by MegaCrafter** [comment]
As a side note, this problem doesn't occur when I use manifold as a jar library in Intellij.

**Comment by rsmckinney** [comment]
Just tested with 193.5233.102. Works fine on my end, both with tests and sample projects.

Looking at your project, if you are using Maven or Gradle, you'll need to put resource files like User.json in the `resources` directory e.g., `src/main/resources`, otherwise resource files are not copied to the target directory. Similarly, unless you specify otherwise, source files such as Core.java should be rooted in `src/main/java`.

Hope this helps.  Let me know if you have questions.

**Comment by MegaCrafter** [comment]
There are no problems with the roots. I somehow messed up the intellij project view so to clear out the junk, I switched to package view. As you can see, the code works fine and in console it printed out "<id>nee</id>" without problems. But in code view, intellij thinks that there is a problem.

**Comment by rsmckinney** [comment]
@MegaCrafter  Still no luck reproducing this.  In any case there is a new sample project demonstrating how to use Manifold with Gradle.  Try it out if/when you get a chance.  The readme file has all the instructions you should need.  Let me know if you have questions:

>https://github.com/manifold-systems/manifold-simple-gradle-project

**Comment by rsmckinney** [comment]
@MegaCrafter Hi, any luck? I'll close this if I don't hear back.  Thanks again for reporting the issue.
