### ISSUE TITLE
Can I use the free plugin with IDEA Student edition?

### ISSUE THREAD

**Issue by davidhsv** [manifold-systems/manifold#146]

**Comment by rsmckinney** [comment]
@davidhsv Hi.  The Manifold plugin is free for IDEA Community Edition and also supports all IDEA discounts, including student and faculty. HOWEVER, last I checked JetBrains has not yet completed the licensing aspect of Marketplace.  Please contact JetBrains Sales for more information regarding student discounts and Marketplace plugins: https://www.jetbrains.com/support/sales/#department=american&tab=email-sales

In the meantime you have two options:
1. Use Manifold free with IntelliJ IDEA Community Edition
2. continue using Ultimate Edition and get a free one month trial of Manifold

**Comment by davidhsv** [comment]
Thanks!

**Comment by AleMuzzi** [comment]
@rsmckinney I'm currently using Manifold plugin in IntelliJ IDEA 2020.3 with student license but I am not able to license Manifold plugin with it. The plugin says that the license will expire in 2 days.

**Comment by rsmckinney** [comment]
You can license it with the main menu:   `Help |  Register Plugins...` 

Note, if you don't license it, it will remain free for use after the 30-day trial, with a light reminder about the license at startup.

**Comment by AleMuzzi** [comment]
I'm probably doing something wrong, but this seems to don't work

![image](https://user-images.githubusercontent.com/7605774/115592050-12ac1a00-a2d3-11eb-9bd7-abcd8bdc873e.png)
