### ISSUE TITLE
javac -source 1.7 -target 1.7

### ISSUE THREAD

**Issue by cheburashka** [manifold-systems/manifold#151]
I am loving the Manifold preprocessor. However, my project uses Java Card that requires that I use target 1.7 for the bytecode. If I change the version from 8 to 7 in IntelliJ or in a command line build that uses Manifold, then the compilation breaks as I guess Manifold is using 1.8 specific features. Is there any way to make it work in conjunction with the -source 1.7 and -target 1.7 flags? Or maybe is it worth discussing it as a feature request?

**Comment by rsmckinney** [comment]
@cheburashka Hi. Nice to hear re preprocessor, thanks.  Manifold components, both compile-time and runtime, including the preprocessor, require at least Java 8. So 1.7 is not supported. However, with some changes to core Manifold, there may be a way to support 1.7 and older targets while running exclusively with the preprocessor.  I'll investigate the feasibility of this scenario.

**Comment by pr-yemibedu** [comment]
Hello,
  It is definitely more akin to looking at only Core for now or the minimum viable (+Preprocessor, +Util) to towards giving some wider reach to the Manifold install and user base. There always has to be a line drawn somewhere as some things will require so much overhead and wasted time in solving challenges to [simple and useful features](https://www.javatpoint.com/java-8-features). But if the extra pieces can be provided by the community on top of a strong Core release, then it could split the workload off your plate for a Java 7 release. Probably cannot go back further than Java 6 for [compiler support](https://docs.oracle.com/javase/9/docs/api/com/sun/source/util/JavacTask.html) anyway. Best of luck. Thank you. Good day.

**Comment by rsmckinney** [comment]
@pr-yemibedu Hi. Manifold uses the [javac plugin API](https://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/util/Plugin.html) to inject features like the preprocessor directly into the compiler. Unfortunately, the API is new in Java 8, so the real challenge with supporting Java 7 and older is to find some another way to hook into the compiler. But without an API there is no other way that does not involve additional steps on the user's end to enable Manifold. I have some ideas, but this general problem is a sticking point for me and is the main reason for my inactivity on this issue.

**Comment by rsmckinney** [comment]
With release 2020.1.17 Manifold now supports Java -source and -target levels prior to 8 with core features and most extensions including **manifold-preprocessor**.

For instance, you can use builtin definitions like this:

```java
#if JAVA_6
  public String bar() {
      return "java6";
  }
#elif JAVA_7
  public String bar() {
      return "java7";
  }
#elif JAVA_8_OR_LATER
  public String bar() {
      return "at least java8";
  }
#endif
```

>Note some type manifolds such as manifold-graphql and manifold-json are _not_ supported with -source levels below 8.
