### ISSUE TITLE
Compiler warnings not reported correctly when combined with Lombok

### ISSUE THREAD

**Issue by iadcode** [manifold-systems/manifold#153]
This is one of the symptoms I reported in #137, which I said was resolved, but I was mistaken (sorry!).

When compiling with both the Manifold and [Lombok](https://projectlombok.org/) plugins, javac does not report warnings correctly.

For example, given this input:

    class Test {int x = 1/0;}

Compiling with `-Xlint:all` should print this output:

    Test.java:1: warning: [divzero] division by zero
    class Test {int x = 1/0;}
                          ^
    1 warning

However, the last line ("1 warning") is missing.

Compiling with `-Xlint:all -Werror` should print this output:

    Test.java:1: warning: [divzero] division by zero
    class Test {int x = 1/0;}
                          ^
    error: warnings found and -Werror specified
    1 error
    1 warning

...as well as setting a nonzero exit code, and exiting without producing a .class file. However, the last three lines do not appear, and the compilation succeeds.

I can reproduce the problem with the `Test` class above using this Maven build configuration:

```
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <encoding>UTF-8</encoding>
          <compilerId>javac</compilerId>
          <source>11</source>
          <target>11</target>
          <showWarnings>true</showWarnings>
          <compilerArgs>
            <arg>-Xlint:all</arg>
            <arg>-Werror</arg>
            <arg>-Xplugin:Manifold no-bootstrap</arg>
          </compilerArgs>
          <annotationProcessorPaths>
            <processorPath>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.10</version>
            </processorPath>
            <processorPath>
              <groupId>systems.manifold</groupId>
              <artifactId>manifold</artifactId>
              <version>2019.1.32</version>
            </processorPath>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

Without the `-Xplugin:Manifold` arg, it behaves as expected.

Relevant versions:
- Windows 10
- OpenJDK 11.0.2+9
- Manifold 2019.1.32
- Lombok 1.18.10

**Comment by HuanRuan** [comment]
Hi, has there been any progress on this? It will be really useful to have manifold and Lombok work together. Thanks.

**Comment by rsmckinney** [comment]
@HuanRuan Hi. I'll investigate this later today.

**Comment by HuanRuan** [comment]
@rsmckinney many thanks for the quick reply. You are right and we do use both. It's the compiler warning/error reporting part I was referring to.

**Comment by rsmckinney** [comment]
@HuanRuan no problem.  I have it fixed locally, will be included in the next release (2020.1.12) available within 24 hrs.

**Comment by HuanRuan** [comment]
That is amazing @rsmckinney , thanks a lot.

**Comment by iadcode** [comment]
All appears to be working in the new release, thanks @rsmckinney!
