### ISSUE TITLE
Default methods for interfaces as extension methods

### ISSUE THREAD

**Issue by MarceloLaser** [manifold-systems/manifold#154]
How does one create an extension method for an interface, as a default method? And also, how does one make use of Generics with extension methods? I have a specific situation that calls for both: I'd like to extend `Map` to have a `containsKeySet(Collection<T> keys)` method, which is to return true if the `Map` contains all keys, and false otherwise. It can be written as a default method by calling the already-existing `containsKey(Object key)` method from `Map`, as:

```
for(Object key : keys)
      if(!containsKey(key)) return false;
return true;
```

However, I cannot for the life of me even begin to think of how to implement that, so I can't even test for myself whether this works with Manifold. Any help would be appreciated.

**Comment by rsmckinney** [comment]
@MarceloLaser Hi. There's a bit of docs covering extension methods and generics in the [manifold-ext readme docs](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#Generics).  Generally, an extension method on a generic class must convey the extended class' type variables as method type variables.  For instance, your containsKeySet() method:

```java
package manifoldsampleproject.extensions.java.util.Map;

import manifold.ext.api.Extension;
import manifold.ext.api.This;

import java.util.Collection;
import java.util.Map;

@Extension
public class MyMapExtension {
  public static <K, V> boolean containsKeySet(@This Map<K, V>  thiz, Collection<K> keys) {
    return thiz.keySet().containsAll(keys);
  }
}
```
Using the method:
```java
    Map<String, Integer> map = new HashMap<>() {{
      put("one", 1);
      put("two", 2);
      put("three", 3);
    }};
    List<String> keys = Arrays.asList("one", "two");
    boolean result = map.containsKeySet(keys);
```
