### ISSUE TITLE
Question about Manifold plugin for IntelliJ IDEA Community edition

### ISSUE THREAD

**Issue by grudir** [manifold-systems/manifold#158]
Hi,

First of all I'd like to say that Manifold is a great idea!

I wanted to explore the Manifold plugin in the IntelliJ IDEA Community edition 2019.3.3. In various documents it was written that the plugin is free for the Community edition, but I noticed it is marked as `Paid` in the Marketplace inside IntelliJ. Is it still free or the documentations is getting a bit outdated?

Thank you in advance and keep up the good work!

**Comment by rsmckinney** [comment]
@grudir Hi. Sorry about the confusion regarding licensing. It confuses me as well! It used to be that Marketplace plugins could still function without a license. That changed where IntelliJ now requires a license at startup, without one a plugin will not load thereby denying it the opportunity to override the license with customized access e.g., the Manifold plugin provides access if the user is running Community Edition.

There's good news. After some recent discussion JetBrains has decided to address this and once again grant paid plugins customized access.  See issue [MP-2910](https://youtrack.jetbrains.com/issue/MP-2910). It's fixed, but I'm not sure which versions will support it. In the meantime you can use the 30 day trial. Let me know if you need more time,

**Comment by grudir** [comment]
Thank you @rsmckinney for detailed and lightning fast reply!

**Comment by WesleyKhoiVo** [comment]
Hi, I have a question relative this. Do I need to buy it for commercial use?

**Comment by rsmckinney** [comment]
@WesleyKhoiVo The Android plugin is free just as it is free for IDEA Community Edition.

**Comment by WesleyKhoiVo** [comment]
Thanks @rsmckinney

**Comment by nicolasdejong** [comment]
Just found out about Manifold. Would have been a nice addition to Lombok, which is used in almost any commercial en open source project I have seen. Unfortunately in practice Manifold is only used on open source projects because in a commercial environment it would be mandatory for anyone working on a project to pay a licence for the IntelliJ plugin which is very unlikely to happen (yes it builds without, but can't edit it in IntelliJ). This prevents me from introducing this in a commercial environment. I understand the reason for monitizing this, I just hope in the future another model is found for this (patreon? donations? conversion will be lower but probably offset by much higher adoption). Anyway kudos for this great tool.

**Comment by rsmckinney** [comment]
@nicolasdejong Thanks. I've thought about other forms of monetization, like donations etc. But I'm happy with the current setup. It's all free if you use FOSS -- the IJ plugin is free on Community Edition and Android Studio; it requires a paid license exclusively on IJ Ultimate edition, which is a commercial product. If it doesn't generate revenue from that channel, it's probably an indication that it's not worth using. Simple as that.  Fortunately, it's been doing well enough.

**Comment by nicolasdejong** [comment]
I understand. I just think it is an impediment from growing larger. But who knows. Perhaps FOSS uptake will be high enough for it to make a difference. Or someone else comes along making something similar. Nice stuff to keep an eye on. Thanks for your quick answer and of course for all the time you put in to make this an awesome tool.

**Comment by bluelu** [comment]
Hi,

I'm confused with the intellij idea pricing page as well.

Is the plugin free to use (also after 30 days have expired) for the community edition, or does it require a licence?

Thanks
