### ISSUE TITLE
Refactor union type name in graphql file will cause wrong name in the java file.

### ISSUE THREAD

**Issue by yueliangwen** [manifold-systems/manifold#161]
**Describe the bug**
When refactoring union type name in graphql file, the union type name will change to ProxyFactory in java file.

**To Reproduce**
1. Declare a union type in graphql file (movies.graphql)
2. Refer to the union type in java file
3. Refactor the union type name with the idea's refactor functions (refactor CastMember to CastMember2)
4. The refactor error will make in java file

**Expected behavior**
It should get the correct union type name in java file.

**Screenshots**
The error union type name.
![image](https://user-images.githubusercontent.com/1107708/75547793-b353d080-5a66-11ea-9d6c-ac9d34165452.png)

**Desktop (please complete the following information):**
- OS Type & Version: macOS Catalina (10.15.3)
- Java/JDK version: jdk1.8_192
- IntelliJ IDEA version: 2019.3.3 Ultimate Edition
- Manifold version: 2020.1.3
- Manifold IntelliJ plugin version: 2019.3.10

**Additional context**
Refactor the snippet
`union CastMember = Person | Animal`
to
`union CastMember2 = Person | Animal`

**Comment by rsmckinney** [comment]
Fixed with https://github.com/manifold-systems/manifold-ij/commit/1aec41b40d90b163dc08b10a1ad436dbb106bb71 (ij plugin codebase)

Fix will be available in next plugin release which is pending Jetbrains approval, usually two business days.

Thanks for reporting this issue!
