### ISSUE TITLE
Trace current stream chain is disabled

### ISSUE THREAD

**Issue by arvindnagar15** [manifold-systems/manifold#163]
**Describe the bug**
I am using android studio 3.5.3 and enabled java stream debugger plugin. After enabling the plugin, I can see the trace current stream option but its not enabled, its grayed out.

**To Reproduce**
1. Enable Java debugger plugin
2. restart android studio
3. You can see the trace current stream chain option but that's grayed out

**Expected behavior**
Stream debugger option should be enable.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version:  Mac 10.14.6 
- Java/JDK version:java8
- IntelliJ IDEA version:3.5.3 (android studio)
- Manifold version:
- Manifold IntelliJ plugin version: 

**Additional context**

**Stack trace**
Please include a stack trace if applicable

**Comment by rsmckinney** [comment]
@arvindnagar15 Hi.  Maybe you meant to report this for a different plugin?  I don't see a Manifold related issue here.
