### ISSUE TITLE
Manifold plugin in Community Edition shows Trial Expiration

### ISSUE THREAD

**Issue by johnnychow1** [manifold-systems/manifold#165]
Hi

I have IntelliJ Community Edition 2019.3.1 and Manifold plugin installed version is 2019.3.10. Everything works but in the IJ plugins it shows "Trial expires in xx days". Thought it is free for the IJ Community Edition?

Regards

**Comment by rsmckinney** [comment]
@johnnychow1  Hi. The JetBrains Marketplace is still a work in progress. At one point early in development the Manifold plugin could load for free in Community Edition, but as you've discovered that no longer works. JetBrains is fixing this with [MP-2910](https://youtrack.jetbrains.com/issue/MP-2910), free plugin support for CE is coming soon in a 2020 IJ release. In the meantime please [contact JetBrains](https://www.jetbrains.com/support/sales/#email-sales) and let them know you need free Manifold plugin support for Community Edition.

**Comment by johnnychow1** [comment]
Thanks for the update

**Comment by johnnychow1** [comment]
Hi, I just installed IJ2020.1 CE and then installed Manifold, it still shows 30 expiry date. No free Manifold plugin support.

**Comment by rsmckinney** [comment]
Fixed in Manifold IJ Plugin release 2020.1.9, currently awaiting JetBrains repo approval (usually takes up to two business days)
