### ISSUE TITLE
Calling methods on a sub-type

### ISSUE THREAD

**Issue by markyys** [manifold-systems/manifold#168]
Hello, another newbie question here. My problem has to do with the interaction between an extension method on a base class, a regular method on the extension class with the same name, and an extension method OR regular method on a subclass.

An example:

```
package MyProject.extensions.java.lang.Object;
import manifold.ext.api.Extension;
import manifold.ext.api.This;

@Extension
public class ObjectExt {
	public static void One(@This Object self){
		self.Two();
	}
	public static void Two(@This Object self){
		system.out.println("Base ext");
	}
	public void Two(){
		system.out.println("Base regular");
	}
}

... another file

package MyProject.extensions.java.lang.String;
import manifold.ext.api.Extension;
import manifold.ext.api.This;

@Extension
public class StringExt {
	public static void Two(@This Object self){
		system.out.println("Sub class");
	}
	public void Two(){
		system.out.println("Sub regular");
	}
}

... another file

Package MyProject;
import MyProject.extensions.java.lang.Object.ObjectExt;
import MyProject.extensions.java.lang.String.StringExt;

public class Test {
	public static void main(String[] args){
		"test".One();
	}
}
```

What will be printed? I would expect that it would
1) try to execute `String.One`,
2) find the definition on `Object` (by extension), call `Object.One` which calls `Two` on the instance, which causes `String.Two` to be called,
3) resolves to the extension method (since this is a String and not an instance of StringExt) and
4) we get `Sub Class` printed out.

In practice, this seems to do (1), but then it calls `Object.Two` which results in `Base ext`.

I tried using `@Self` instead of `@This`, but that just causes it to fail to compile with `cannot find symbol self.Two();` and `@This @Self` will compile, but I don't appear to be able to get it to access the methods on the subclass by referencing `self`.

**Comment by rsmckinney** [comment]
@markyys Hi. As you've discovered extension methods dispatch *statically* where the compile-time type determines the method that is called, hence the `Object#Two()` call. To get a better handle on extension methods I recommend reading the entire section on [Extension Methods](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-classes-via-extension). The part explaining [static dispatching](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#static-dispatching) is particularly relevant. It's worth noting other languages with extension methods, such as C#, also use static dispatching for the same reasons.
