### ISSUE TITLE
Strange break to label behaviour with Manifold

### ISSUE THREAD

**Issue by Afarion1** [manifold-systems/manifold#169]
I can't find any mentions about Manifold changing break to label, but when I try to use break to label in IntelliJ with Manifold plugin, it doesn't recognize the label:
![image](https://user-images.githubusercontent.com/50185755/78062594-9547fb80-7397-11ea-9b81-9a4b013b9553.png)
and suggests me to create a variable
![image](https://user-images.githubusercontent.com/50185755/78062645-a7c23500-7397-11ea-851e-15529efc185f.png)
If I create the variable, error notification goes away and everything works perfectly in dev environment, but once I build a shadow jar, it doesn't work, and then works again once I remove Manifold from the shadow jar.
Is there something that I'm missing or is it a bug?

I was using the following artifact and used build.gradle setup from github guide:
systems.manifold:manifold-ext:2020.1.3

**Comment by rsmckinney** [comment]
@Afarion1 Hi.  Looks like an IntelliJ plugin bug. You can safely ignore the error the editor reports, it will compile just fine. I'll have a fix ready in the next plugin release, coming soon.  Thanks for reporting this!

**Comment by rsmckinney** [comment]
Fixed in ij plugin (2bfb0bb)
