### ISSUE TITLE
Graphql - additional GET parameters

### ISSUE THREAD

**Issue by tasior** [manifold-systems/manifold#174]
At the moment there is no simple way to add additional GET parameter to request. The only solution I found is to use reflections and add data to _reqArgs in Executor class.

It would be nice to have possibility to write code like this:
```java
query.request("http://localhost?foo=bar").get() // at the moment it generates malformed URL
```
or:
```java
query.request("http://localhost").withParam("foo", "bar")
```

Possible solition (withParam implementation in Executor class):
```java
public Executor<T> withParam(String param, String value) {
  _reqArgs.getBindings().put(param, value);
  return this;
}
```

**Comment by rsmckinney** [comment]
I like your solution! It will be implemented in the next release, coming soon.

**Comment by rsmckinney** [comment]
@tasior I'm interested to know the use-case where the name/value pair is not already included in your GraphQL payload. Knowing more will help me to focus the implementation where it is best suited.

**Comment by tasior** [comment]
@rsmckinney It's not about GraphQL payload. I'm using GraphQL that is protected by api key and this key need to be send as GET parameter. So request looks similar to this one:

```
http://localhost?query=query UsersQuery {users {id firstName}}&variables={}&api_key=secretApiKey
```

**Comment by rsmckinney** [comment]
@tasior Gotcha.  Thanks

**Comment by rsmckinney** [comment]
Added in release 2020.1.7
