### ISSUE TITLE
[Question] GraphQL requests using proxy

### ISSUE THREAD

**Issue by VeronikaVakadinova** [manifold-systems/manifold#175]
Hello all, 

I have a question regarding the usage of a proxy on any `graphQL` request.
Unfortunately, I found no information on the wiki page.

Can you explain briefly how it could be achieved?

Thank you very much in advance. 
Stay safe. 🍀

Regards,
Veronika

**Comment by rsmckinney** [comment]
Hi @VeronikaVakadinova. Support for proxies will be released in the next version (2020.1.8) coming later this week, just a few days away. The basic API looks like this:
```java
  private static String URL = "http://my.server.com:4567/graphql";
  private static Endpoint ENDPOINT_NO_PROXY = new Endpoint(URL);
  private static Endpoint ENDPOINT_PROXIED = new Endpoint(URL, "my.proxy.com");
. . .
  var result = query.request(ENDPOINT_PROXIED).post();
```
Make sense?

**Comment by rsmckinney** [comment]
Proxy support is now available in release 2020.1.8.  Please see the updated [Configuring Proxies](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-graphql#configuring-proxies) section in the GraphQL docs.

**Comment by VeronikaVakadinova** [comment]
I will try it out now. 
Working with your code is a real pleasure.

Thank you for your quick response and release.

**Comment by rsmckinney** [comment]
@VeronikaVakadinova no problem. Thank you for reporting this!
