### ISSUE TITLE
Is an Eclipse extension on the roadmap?

### ISSUE THREAD

**Issue by dewdad** [manifold-systems/manifold#18]

**Comment by rsmckinney** [comment]
No, Eclipse support is not currently a planned feature (intellij IDEA only).  Perhaps after the first major release I’ll find some bandwidth to begin developing a plugin.

**Comment by 54** [comment]
It would be really nice to see an Eclipse plugin at some point. A lot of the people I work with still haven't switched.

**Comment by rsmckinney** [comment]
I agree it would be nice; not everyone has seen the light. But building such a plugin is a pretty heavy investment I can't really afford at the moment.  Essentially, it comes down to a decision between making the IJ plugin better and/or adding new features to Manifold vs. spending time on Eclipse.  With the way IDE preferences are trending I can't see Eclipse making the cut, at least not in the short term.  Additionally, my past experience with Eclipse plugin dev leaves me a little dubious that it can be done well enough to be worth the effort -- Manifold demands a lot from the the IDE in terms of architecture and API flexibility.

On the other hand, if Manifold gains enough traction after it's 1.0 debut, perhaps I'll trick some poor slob into helping out with this ;)

**Comment by sporkisfaster** [comment]
Is there anything that can be done from the community to help this along in any way

**Comment by rsmckinney** [comment]
Sure. . .  any takers?  ;)

**Comment by sporkisfaster** [comment]
Fair points lol our shop develops eclipse plugins by trade as a platform so if the need were to be pressed / interested in the shop ramps then I'd like to look at it. Not for nothing, from 1 to 10 how hard was the IntelliJ plugin

**Comment by rsmckinney** [comment]
Heheh. What I meant was... https://www.youtube.com/watch?v=Oj_aid1LUF0

Ok the Manifold plugin is an 11 in dog years.  Some parts of Manifold are easier to build in IJ than in javac, while others are other worldly.  In most cases it depends on how much of the feature is bytecode oriented i.e., there is no compilation in the IJ plugin, just type information and AST/PSI manipulation.  But the IJ plugin makes up for this with subsystems that handle change -- compilers don't have to deal with change, but IDEs do.  Anyway doing Eclipse plugins I'm sure you're aware of all this.  The Manifold plugin shouldn't exist, it's at that level.

**Comment by rsmckinney** [comment]
in progress

**Comment by sporkisfaster** [comment]
Curious and feel free to not disclose for business reasons but how do you plan on monetizing the plugin/support for this and vs code.

**Comment by rsmckinney** [comment]
@sporkisfaster No idea.  Not much progress yet.

**Comment by rsmckinney** [comment]
I've suspended further development on this, will consider reopening at a later date.

**Comment by fxgaming** [comment]
:(

**Comment by rsmckinney** [comment]
Sorry. Would love to provide Eclipse support. Maybe there is some middle ground; some kind of 80/20 implementation where support is less than ideal, but workable enough for most project. _shrug_
