### ISSUE TITLE
[Feature] Call-site extension method

### ISSUE THREAD

**Issue by WilliamStone** [manifold-systems/manifold#183]
Hello @rsmckinney , 

Currently Manifold supports extension methods which effectively is "injected" into extension class. However I found myself seldom use this feature except for some basic utility classes, since "injecting" method into a class is global and isn't appropriate if the to-be-extension-method is just used locally.

Thus I wish another form of extension method, which is based on method invocation transformation, I've seen other languages support it, but don't know what it's named, so I'll just call it call-site extension method. 

The idea is: For any method invocation e.g. `subject.callMethod(argList)`, if it is semantically illegal, then transform it into `callMethod(subject, argList)` and try to resolve in the same context again , if this time it is legal, then that's its real invocation.
The transformation is simply move invocation target to first argument. Anything that is legal after transformation is also legal before transformation. This allows very flexible extension method definition and usage, 

Some example: 

```
import static com.google.common.base.Preconditions.checkNotNull;

class Foo {
    private int add(int val1, int val2) {
        return val1 + val2;
    }

    public <T, R> void map(List<T> list, Function<T, R> func) {
        return ...
    }

    public int size(Object obj) {
        if (obj instanceof String)
            return ((String) obj).length();
        else if (obj instanceof Collection)
            return ((Collection) obj).size();
        else
            throw new IllegalArgumentException(obj);
    }

    public void extensionMethodTest() {
        Integer subject1 = 100;
        int result1 = subject1.add(200); // illegal, so transforms into: add(subject1, 200)
        subject1.checkNotNull(); // illegal, so transforms into: checkNotNull(subject1), 
                                   // which is actually Preconditions.checkNotNull(subject1), 
                                  // simplified by static import

        List<Integer> list = arrayListOf(1, 2, 3);
        list = list.map(it -> it * 2); // illegal, so transforms into: map(list, it -> it * 2)

        i = "abc".size(); // illegal, so transform into: size("abc")
        int i = list.size(); // legal, so it doesn't transform to size(list)
    }
}
```
As above example shows, call-site extension method is on-demand, lightweight, flexible and limited scope. It can be defined in the same compilation unit where it's used, and even if the extension method is in common library, it's scope is still under control by whether or not to import the library. I don't know how hard it is or even whether possible to implement it though. Please consider if this is worth implementing, thanks!

**Comment by rsmckinney** [comment]
@WilliamStone Interesting idea. This is closer to C#-style extension methods where you must import them explicitly in a source file. Perhaps this would be more practical too, since you don't have to write the define the methods inside the source that uses them. I've considered providing something similar to this, but haven't gotten around to implementing it.

In my own experience I've found module scoped extensions such as Manifold's to be more practical in most situations. The module is typically the right granularity and you can prevent sharing extensions e.g., using Maven's 'optional' or exclude it going the other direction.  But, yeah, having file scoping can't hurt. :)
