### ISSUE TITLE
Jailbreak does not find methods that have generic types or arrays as arguments

### ISSUE THREAD

**Issue by kevin-belellou** [manifold-systems/manifold#185]
**Describe the bug**
When jailbreaking a class, calling a method that have a generic type or an array as argument results in the method not being found.

**To Reproduce**
1. Minimal project to experience the issue is here https://github.com/kevin-belellou/minimal-jailbreak-project-not-working
2. Just launch the main class

**Expected behavior**
Should output
> Hello World
> Hello World Foo:Bar

**Actual behavior**
> Hello World
> java.lang.RuntimeException: Method 'helloWorld' not found
> 	at manifold.util.ReflectUtil.method(ReflectUtil.java:161)
> 	at manifold.ext.ReflectionRuntimeMethods.invoke_Object(ReflectionRuntimeMethods.java:26)
> 	at stuff.Main.main(Main.java:14)
> java.lang.RuntimeException: Method 'helloWorld' not found
> 	at manifold.util.ReflectUtil.method(ReflectUtil.java:161)
> 	at manifold.ext.ReflectionRuntimeMethods.invoke_Object(ReflectionRuntimeMethods.java:26)
> 	at stuff.Main.main(Main.java:20)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10, 1909
- Java/JDK version: 11.0.7.10
- IntelliJ IDEA version: CE 2020.1.1
- Manifold version: 2020.1.12
- Manifold IntelliJ plugin version: 2020.1.12

**Comment by rsmckinney** [comment]
@kevin-belellou Thanks for reporting this!  By the way, the issue with the Map.Entry example has to do with inner classes, not generics. A fix will be included in the next release coming early next week.

**Comment by rsmckinney** [comment]
**Update**

This change is ready for release, but the release is waiting for #181, which is a major release. Coming soon (< 1 week). Sorry for the delay!

**Comment by kevin-belellou** [comment]
No problem! Take all the time you need :)

**Comment by rsmckinney** [comment]
available in release 2020.1.13
