### ISSUE TITLE
Manifold Website Not Secure Https

### ISSUE THREAD

**Issue by mmadson** [manifold-systems/manifold#188]
**Describe the bug**
Visiting https://manifold.systems/ in Chrome shows Not Secure instead of padlock. This produces a bad first impression when sharing the project to others.

**To Reproduce**
1. Visit https://manifold.systems/ in chrome
2. Observe that Chrome says connection is Not Secure

**Expected behavior**
Expected visiting https://manifold.systems/ would have a padlock in chrome indicating a secure connection. 

**Screenshots**
<img width="1329" alt="Screen Shot 2020-06-08 at 1 45 31 PM" src="https://user-images.githubusercontent.com/1190456/84078828-6731f980-a98e-11ea-80e2-5d8bb8d81d74.png">

**Comment by rsmckinney** [comment]
I can write me some Java code, but I'm a retard when it comes to setting up a website. Squarespace is manifold's domain provider, but github hosts it.  Something wonky going on with the SSL certificates at squarespace.  I'll figure it out.  Thanks for the heads up.
