### ISSUE TITLE
Array Extension Methods

### ISSUE THREAD

**Issue by Anuken** [manifold-systems/manifold#189]
Is there a way to create an extension method for an array type? e.g.

```java
@Extension
public class ArrayExt{

    public static void sort(@This int[] array){
        Arrays.sort(array);
    }

    //or, for objects...
    public static <T> void sort(@This T[] array){
        Arrays.sort(array);
    }
}
```

The documentation reads,
> *the remainder of the package must be the qualified name of the extended class*

...but arrays are not real classes, and thus don't have a fully qualified name.

Extensions made for `java.lang.Object` *do* function properly and show up in autocompletion for array types, but placing methods like `sort()` in `Object` would pollute autocompletion for non-array types and force me to use casting.

---

Related *""issue""*: In my tests, I attempted creating an `@Extension` class in an empty package, which caused a crash due to `ExtensionTransformer#getExtendedClassName` calling `toString()` on `getPackageName()`, which was null. 

This shouldn't have compiled anyway, but a nicer error message than a `NullPointerException` could be used (although I don't see this being much of a problem).

**Comment by rsmckinney** [comment]
@Anuken I've been meaning to add support for array extensions. At some point I'll probably add a special case for it, something like:

```java
package myproject.extensions.array.com.example.Foo;

@Extension
public class MyFooArrayExtension {
  public Foo[] add(@This Foo[] thiz, Foo... items) {
      Foo[] dest =  Arrays.copyOf(thiz, thiz.length + items.length);
      System.arraycopy(items, 0, dest, thiz.length, items.length);
      return dest;
  } 
}
```
Then use it like this:
```java
fooArray = fooArray.add(foo1, foo2, foo3);
```
You could extend any reference array using package `myproject.extensions.array.java.lang.Object`.

Considering primitive arrays, probably follow the same pattern:
```java
package myproject.extensions.array.char;

@Extension
public class MyCharExtension{
  public char[] concat(@This char[] thiz, char[] that) {
      char[] dest =  Arrays.copyOf(thiz, thiz.length + that.length);
      System.arraycopy(that, 0, dest, thiz.length, that.length);
      return dest;
  } 
}
```
Then use it like this:
```java
char[] result = charArray1.concat(charArray2);
```
Unfortunately, an extension intended to support _any_ array including primitives, would have to be duplicated with the same basic logic for Object and each primitive type. I could go the full nine yards and devise some generic solution and automatically generate specializations for the primitives, but I probably won't. :-/

**Comment by rsmckinney** [comment]
Oh wait...

After looking through javac code re arrays I remember now why I skipped over array extensions. It comes down to how array references resolve to symbols. The java compiler reuses the same type symbol instance for all array references. Since Manifold works, essentially, by manipulating type symbols, extending arrays by component type is a bridge too far.  About the best I can do is provide a single extension point for all array types, say via package `myproject.java.lang.array`.

![nothing](https://dl.dropbox.com/s/p8to75xp5n78pyv/homerbushes.gif)

**Comment by Anuken** [comment]
Thanks for the response!

> About the best I can do is provide a single extension point for all array types, say via package myproject.java.lang.array.

That would still be fairly useful, as (at least in my case) most array operations I need (*map, filter, find, contains*, etc) are only applicable to non-primitive arrays.

**Comment by rsmckinney** [comment]
No problem. Note, the `myproject.extensions.java.lang.array` package extension point would also support primitive types.  For *map, find,* etc. you can rely on boxing when dealing with a primitive parameter type i.e., use `Object`. An extension would look like:
```java
package myproject.extensions.java.lang.array;

@Extension
public class MyArrayExtension {
  public Object copy(@This Object array, int newSize) {
    Object copy = Array.newInstance(array.getClass().getComponentType(), newSize);
    System.arraycopy(array, 0, copy, 0, Array.getLength(array));
    return copy;
  } 
}
```

**Comment by rsmckinney** [comment]
in progress

**Comment by rsmckinney** [comment]
Feature available in release 2020.1.22.  See [Extending Arrays](see https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extending-arrays) for details.

**Comment by rsmckinney** [comment]
Note, I am considering adding support for specific array types where you can narrow the type of the `@This` parameter to your liking.
```java
public static String base64(@This byte[] array) {
  return Base64.getEncoder().encodeToString(array);
}
```
Although `base64()` is still generally available on all array types, the `byte[]` type on the `@This` param can be used by the IntelliJ plugin as a means to filter out the method on types that do not apply e.g., for code completion and editor error indicators.

**Comment by rsmckinney** [comment]
In fact, I can also add compile errors in the javac plugin as well.  So, I think I'll go ahead with this.

**Comment by rsmckinney** [comment]
See https://github.com/manifold-systems/manifold/issues/207
