### ISSUE TITLE
kotlinc support

### ISSUE THREAD

**Issue by DALDEI** [manifold-systems/manifold#19]
Excellent project, just what I was looking for (or looking-to-avoid-writing-myself).
I am developing in Kotlin, JVM 8, linux/server.    Gradle.
Manifold works find 'out of the box' using IntelliJ while editing kotlin files,
however builds do not find the manifold plugin
I tried using the kotlinc variant  "-Xplugin=path-to-plugin" ... guessing at which .jar file that might be -- but no errors except 'class not found' during compile.

Any suggestions?

**Comment by rsmckinney** [comment]
Hi and thanks!

The main issue here is Manifold is a _javac_ compiler plugin; other JVM language compilers such as kotlinc are not directly supported.  However, the API is designed so that other language providers can modify their type systems to recognize types provided by Manifold.  I may consider providing optional Manifold support via Kotlin pull request sometime after the Manifold official release later this fall.

**Comment by ftomassetti** [comment]
I would be really interested in this. Any way we could help?

**Comment by rsmckinney** [comment]
@ftomassetti

Hi Federico, nice to hear from you, it's been a while!

Hell Yes!  I'm spread pretty thin over all of Manifold, so your help on this is more than welcome.

Kotlin support is one of those features that is important enough to me to worry about, but not important enough to devote time to, if that makes sense.  Interestingly I did peek at this a few days or so ago, but I didn't dig too deeply -- my knowledge of Kotlin's compiler etc. is slim to none.  That understood, here is my quick assessment of the problem.

To begin with, Manifold consists of two basic parts: Type Manifolds and Type System augmentation. I think it would be best to focus on Type Manifolds and leave the other stuff for a separate effort/discussion.

There are two ways we could provide Type Manifold support for Kotlin.
1. via kotlinc plugin
2. via annotation processor

Again my understanding of kotlinc is near zero, so I could easily be wrong here, but their plugin architecture does not look like a good fit for the purposes of integrating Manifold into the compiler's type system.  Essentially we need to hack into some of the compiler's components such as the file system and override some behavior.  This seems like a more straightforward job as an annotation processor -- we would be using the annotation processor exclusively as a means to hook into the compiler, not as a proper annotation processor.

I also don't know anything about Kotlin/Java interop, which is an important aspect of this project. For example, is Kotlin's compiler also a Java compiler?  Can it resolve Java type's directly?  Or does it create transient Kotlin stubs for Java types?  The answers to these basic questions determine some high level fundamentals.  I assume we can get answers pretty quickly, I just haven't researched any of this :(

Anyway I'm glad to hear from you and if you are *still* interested after hearing this news, I'd be interested to discuss next steps with you.

Cheers!

**Comment by rsmckinney** [comment]
Shelved this project indefinitely.

**Comment by rsmckinney** [comment]
Manifold support for Kotlin is in the works. Will be released along with Android support.  See https://github.com/manifold-systems/manifold/issues/181.

**Comment by rsmckinney** [comment]
Manifold version 2020.1.13 supports Kotlin.  See [Using Manifold with Kotlin (and other JVM languages)](http://manifold.systems/kotlin.html)

**Comment by ftomassetti** [comment]
Nice!

**Comment by rsmckinney** [comment]
Thank you, Federico.
