### ISSUE TITLE
Context menu behaves unexpectedly with Manifold IntelliJ IDEA plugin on macOS

### ISSUE THREAD

**Issue by nisnevich** [manifold-systems/manifold#192]
**Describe the bug**
When invoking context menu in Project tool window after selecting a few files, a dialog "Choose Destination Directory" is opened. When trying to close it, it reopens a few times. Finally, it gets closed, and the context menu that was invoked initially appears, but it's not responsive. See a recording for a better overview: https://drive.google.com/file/d/11cSFpj7pM5_PtdSbF3bq4beGrGy6HjFq/view?usp=sharing

**To Reproduce**
1. Install Manifold plugin to IntelliJ IDEA 2020.1
2. Open Project tool window
3. Select 2 or more files with Cmd-Click
4. Right click selected files to invoke context menu

**Expected behavior**
Context menu appears

**Actual behavior**

Unexpectedly "Choose Destination Directory" dialog appears. When trying to close it, it reopens a few times. Finally, it gets closed, and the context menu appears, but it's not responsive: you can't click it or close it.

**Screenshots**

<img width="832" alt="Screen Shot 2020-06-18 at 18 14 34" src="https://user-images.githubusercontent.com/3762077/85040637-b0095f80-b191-11ea-9077-54b3164d3c13.png">
<img width="489" alt="Screen Shot 2020-06-18 at 18 14 44" src="https://user-images.githubusercontent.com/3762077/85040656-b39ce680-b191-11ea-8d58-673d587e6a6e.png">

**Desktop (please complete the following information):**
- OS Type & Version: macOS 10.15.4
- Java/JDK version: 11.0.7+10-b765.53
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2020.1.2 Build #IU-201.7846.76, built on June 1, 2020
- Manifold version: 
- Manifold IntelliJ plugin version: 2020.1.13

**Additional context**

No exceptions in logs.
[idea.log](https://github.com/manifold-systems/manifold/files/4799545/idea.log)

**Comment by rsmckinney** [comment]
@nisnevich There's nothing different or special about what the plugin does with the context menu.  If you disable the plugin, does the menu behave normally?

**Comment by delphym** [comment]
Yes, it does behave normally when Manifold plugin is disabled.
I can record a screencast or not sure how else I could help you with this Scott.

**Comment by nisnevich** [comment]
I can confirm, the problem persists only with the plugin enabled.

**Comment by rsmckinney** [comment]
Ok, thanks for checking.  I'll see what I can do.

**Comment by rsmckinney** [comment]
I was able to reproduce this on my Windows machine. To trigger it the selection must include directories and files. I'll start digging.

**Comment by rsmckinney** [comment]
Ok, I have a fix which will be included in the next release, available 6/30.

**Comment by delphym** [comment]
Yes, that sounds right.
In my case I've selected 3 modules (which are also folders) and it was enough to trigger this behaviour.
Looking forward the new release. Cheers.

**Comment by rsmckinney** [comment]
Fixed in latest plugin release (2020.1.17)

**Comment by delphym** [comment]
Thanks for the fix. I can confirm it works fine on the latest IntelliJ Idea and Manifold plugin.
