### ISSUE TITLE
After extending `java.lang.Integer` its constants are compiled wrong

### ISSUE THREAD

**Issue by vellotis** [manifold-systems/manifold#195]
**Describe the bug**
The constants of the class that is extended get resolved to the type specific default values.

**To Reproduce**
1. Define an extension for `java.lang.Integer`
```java
package extensions.java.lang.Integer;

import manifold.ext.rt.api.Extension;

@Extension
public class IntegerExtensions {

}
```
2. Define a class requiring `java.lnag.Integer.MAX_VALUE`
```java
public class Test {
    private static final int max = Integer.MAX_VALUE;
}
```
3. Which gets compiled to `Test.class`
```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

import manifold.rt.api.IBootstrap;

public class Test {
    private static final int max = 0;

    public Test() {
    }

    static {
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
    }
}

```

**Expected behavior**
After extending a compiling the class the value of `Test.max` is 0x7FFFFFFF as defined in `java.lang.Integer.MAX_VALUE`.

**Desktop (please complete the following information):**
- OS Type & Version: Win10 Enterprise 18362.900
- Java/JDK version: JDK 11.0.4
- Manifold version: 2020.01.17

**Additional info**
The constants for classes that have not been extended work fine.

**Comment by rsmckinney** [comment]
Fix released in https://github.com/manifold-systems/manifold/releases/tag/v2020.1.19

**Comment by rsmckinney** [comment]
@vellotis thanks for reporting this!
