### ISSUE TITLE
Manifold extensions -> auto boxing support on primitive types

### ISSUE THREAD

**Issue by andob** [manifold-systems/manifold#197]
Hello again. I way playing with manifold extensions on Java SE. I wrote the following extension over java.lang.Integer:

```java
@Extension
public class IntegerExtensions
{
  public static boolean isPrime(@This Integer target)  { /*implementation*/ }
}
```

If I want to call isPrime, I need to manually box the integer:

```java
if (((Integer)7).isPrime())
     System.out.println("7 is prime!");
```

Also the plugin doesn't support this use case - the syntax is not recognised by the IDE:

![image](https://user-images.githubusercontent.com/5281358/87139349-80d5a200-c2a8-11ea-93e8-5ad712fc4281.png)

I think it would be great if users could do:

![image](https://user-images.githubusercontent.com/5281358/87139600-efb2fb00-c2a8-11ea-9000-1ae7debc05dc.png)

7.isPrime() does not compile, because 7 is a primitive, not a boxed object.

**Comment by rsmckinney** [comment]
@andob The plugin does support the example `((Integer)7).isPrime()`. You many need to refresh your project (from Maven or Gradle).
