### ISSUE TITLE
Eager to strengthen the preprocessor!

### ISSUE THREAD

**Issue by SaltedFishBayonet** [manifold-systems/manifold#200]
### Such as:
```C
#define E 2.71828
```

```C

#define Print(f,p)    {                                                           \
                                    char arr[1024] = { 0 };                       \
                                    char *mid = strstr((char*)(f), "%Z");         \
                                    memcpy(arr, (f), mid - (f));                  \
                                    printf("%s", arr);                            \
                                }
#endif // !Print
```

### Hopefully it will be stronger and become a true preprocessor.

**Comment by rsmckinney** [comment]
@SaltedFishBayonet.  Macro substitution was left out intentionally. While it's a powerful feature, it has a pretty consistent history of obfuscating code, behaving counter-intuitively, and generally being misused. Additionally, there is much less need for macros in Java. For instance, the performance aspect of macros is unjustified in Java where inlining happens intelligently during JIT compilation -- most macros can be modeled as functions in Java. Other reasons macros were left out include: they can't be debugged, they escape tooling making them difficult to use/discover, and they wreak havoc on packaging/naming especially if #include is supported.
