### ISSUE TITLE
[Feature Request] Provide support for defining and comparing integers with the preprocessor

### ISSUE THREAD

**Issue by JasonHK** [manifold-systems/manifold#204]
**Is your feature request related to a problem? Please describe.**

Sometimes comparing between numbers would be better than using `X_OR_LATER`.

**Describe the solution you'd like**

The first thing needed is the numeric comparison operators: `<`, `>`, `<=` and `>=`.

There are two ways to implement the comparison function.

1. Checks if two sides are both numeric-like strings, throw an error if not. But `==` and `!=` comparisons will be difficult to implement.
2. Require strings to be wrapped in quotes. This will break backwards compatibility, but allows `==` and `!=` comparisons.

**Describe alternatives you've considered**

**Additional context**

**Comment by rsmckinney** [comment]
Fix released with 2020.1.22.  For relational expressions operands are coerced to BigDecimal and compared. If either operand cannot be coerced, a compile error results on the operand[s]. No changes made for equality expressions; the operands are compared as raw strings and must be exactly the same.
