### ISSUE TITLE
Java compilator dropping `@Self` annotation on extension method argument generic type

### ISSUE THREAD

**Issue by vellotis** [manifold-systems/manifold#205]
Hi

I'm writing a lot of functional code in Java. Java is not a functional language. Still, there are a lot of libraries that simplify using the functional approach. Manifold Extensions is one among many.

I have been longing for following feature in Java
```java
Target object = someObject.self((thisOfSomeObject) -> {
    thisOfSomeObject.returnsVoid(someParameter);
))
.finzalize();
```

This is possible with Manifold with the following extension. 🙂 Yay!
```java
package extensions.java.lang.Object;

import io.vavr.CheckedConsumer;
import io.vavr.CheckedFunction1;
import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.Self;
import manifold.ext.rt.api.This;

@Extension
public class ObjectExtensions {

    public static @Self Object self(@This Object thiz, CheckedConsumer<@Self Object> consumer) {
        consumer.unchecked().accept(thiz);
        return thiz;
    }

    public static <R> R self(@This Object thiz, CheckedFunction1<@Self Object, ? super R> consumer) {
        return (R) consumer.unchecked().apply(thiz);
    }

}
```

The thing is that Manifold needs the `@Self` annotation to be present for the generic type to work as an extension library. When using the extension from a library the annotation is missing. This seems not a Manifold issue but a Java compilation issue. This is the decompiled java class.

```java
package extensions.java.lang.Object;

import io.vavr.CheckedConsumer;
import io.vavr.CheckedFunction1;
import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.Self;
import manifold.ext.rt.api.This;
import manifold.rt.api.IBootstrap;

@Extension
public class ObjectExtensions {
    public ObjectExtensions() {
    }

    @Self
    public static Object self(@This Object thiz, CheckedConsumer<Object> consumer) {
        consumer.unchecked().accept(thiz);
        return thiz;
    }

    public static <R> R self(@This Object thiz, CheckedFunction1<Object, ? super R> consumer) {
        return consumer.unchecked().apply(thiz);
    }

    static {
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
        IBootstrap.dasBoot();
    }
}
```
⚠️ **Also why does it perform `IBootstrap.dasBoot();` 5 times?**

I have looked around how to make `javac` to retain the annotations after compilation but without any luck. I think the Manifold team has a better understanding of the behavior of java compilation.

Do you see a way to overcome this problem?

**Comment by rsmckinney** [comment]
As it happens I've just run into (and fixed) this issue while adding support for array extensions.  However, IntelliJ has a similar problem in their API, so although it compile and runs just fine, the editor still marks this as an error. I'm awaiting JetBrains response to a slack discussion [here](https://app.slack.com/client/T5P9YATH9/C5U8BM1MK/thread/C5U8BM1MK-1596052753.172000).

**Comment by rsmckinney** [comment]
Re five dasBoot() calls, I'll fix that too.  Don't worry about though, it has no impact on perf.
