### ISSUE TITLE
withBearerAuthorization does not populate correct Authorization header value

### ISSUE THREAD

**Issue by bhodgesopi** [manifold-systems/manifold#208]
**Describe the bug**
When creating a new graphql request using withBearerAuthorization(token) the actual header set is Authorization $tokenType $accessToken in v2020.1.20 (worked previously in .12).

**To Reproduce**
1. make an graphql request withBearerAuthorization(token)
2. get access denied error back

**Expected behavior**
Authorization header value should set to "Bearer {sometoken}", but sets to "$tokenType $accessToken" instead.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version: 
- Java/JDK version: 11.0.7
- IDE version (IntelliJ IDEA or Android Studio): Intellij IDEA Community Edition 2019.1
- Manifold version: 2020.1.20
- Manifold IntelliJ plugin version: v2019.1.28

**Additional context**
https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-json-rt/src/main/java/manifold/json/rt/api/Requester.java

Line 171 seems to be the issue...
  public Requester<T> withAuthorization( String tokenType, String accessToken )
  {
    return withHeader( "Authorization", "$tokenType $accessToken" ); **// <<< this doesn't replace tokenType, accessToken
  }**

I am able to work around currently by using withHeader() and setting Authorization directly.

**Stack trace**
Please include a stack trace if applicable

**Comment by rsmckinney** [comment]
@bhodgesopi thanks for reporting this! Fix available in release 2020.1.23.

**Comment by bhodgesopi** [comment]
Thanks for the quick turn around! Been using Manifold on current project and its made working with graphql a breeze.

**Comment by rsmckinney** [comment]
@bhodgesopi Glad to hear!  Thanks.
