### ISSUE TITLE
runtime bootstrap should not open compiler jdk module (Java 9+)

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#215]
Since there is no need of it, on Java 9+ the runtime bootstrap should not open the compiler jdk module.

Currently, if manifold is used statically there is no need to open the jdk module during the rt bootstrap process. In fact, some environments like docker commonly deploy an optimized Java 11 "jre" where the jdk modules are omitted from the image. In such a case the manifold bootstrap process will fail with an exception. (See the [slack thread](https://manifold-group.slack.com/archives/C012UD98MC5/p1599242552000100?thread_ts=1599041763.006600&cid=C012UD98MC5))

**Comment by rsmckinney** [comment]
Fix released in version 2020.1.27

**Comment by JJBRT** [comment]
Please take a look at my new article that explain [how to export all modules to all modules at runtime in Java 16 and later](https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m) without using any JVM parameter
