### ISSUE TITLE
Manifold's Intellij plugin and source code

### ISSUE THREAD

**Issue by NickAcPT** [manifold-systems/manifold#217]
Hello, I was wondering on the availability of the source code for the Manifold intellij plugin.

If it's not available, will it be in the future?

Thanks for your time.

**Comment by rsmckinney** [comment]
Hi @NickAcPT. The IntelliJ plugin is semi-commercial -- it's free for IDEA Community Edition and Android Studio, but licensed for Ultimate Edition, although with the latest release it's also technically free for Ultimate but includes a nag message on project load.  The codebase is maintained as a private project on github and is available commercially on a case-by-case basis.

**Comment by NickAcPT** [comment]
@rsmckinney Thanks so much for the fast reply!

Maybe in the future could you consider making it fully open-source (even though it checks for licenses).

Closing this issue as it was solved. Thanks once again. 👍
