### ISSUE TITLE
[Feature] Please add two small but very useful information to build errors

### ISSUE THREAD

**Issue by schittli** [manifold-systems/manifold#219]
Hello
Thank you **very much** for this great Software! I'm a C# developer and java felt like C# 20 years in the past :-(. With Manifold, Java gets a lot of tools, which oracle still does not understand…

**Is your feature request related to a problem? Please describe.**
I tried to get started with manifold-json and it's hard because of missing information. I get the following error and I can just guess that manifold-json created it, because it talks about my Json File which is called `Full.json`:
```
java: cannot find symbol
  symbol:   class Full
  location: package ch.jig.erp.util.REST.RestCountries
```

Here, I miss two small informations - could you please add it?

1. It would help _a lot_ if manifold would say that it is the source of its messages, e.g.:
`manifold-json, java: cannot find symbol …`
It's useful because different sources generate messages and it's great to immediately know where to look :-)

2. Manifold is doing a lot of great and magic work - but if something is broken, it's hard to guess what's wrong. In this example, manifold-json tells in which package it is searching for content:
`java: cannot find symbol`
`  symbol:   class Full`
`  location: package ch.jig.erp.util.REST.RestCountries`
but it is not clear, where **exactly** Manifold is searching for the symbol because the file exists: it's in the classes dir, too:
`classes\ch\jig\erp\util\REST\RestCountries\Full.json`
And: IntelliJ does mark any error or warning.
Do you have maybe file paths which could be displayed in the error message?

**Describe the solution you'd like**
In error messages, please:
1. explicitly tell that manifold is the source of the message
2. if manifold is not able to find something, please tell where it searched for it. If possible, file paths would be great.

Thanks a lot, kind regards,
Thomas

**Comment by rsmckinney** [comment]
@schittli can you provide an example JSON file that produces the error you describe?  Thanks.

**Comment by rsmckinney** [comment]
@schittli If this is still a problem, please provide an example demonstrating the issue.
