### ISSUE TITLE
A manifold-strings dependency in module A causes IJ to apply it to module B even if B does not depend on it

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#225]
**Describe the bug**
A manifold-strings dependency in module A causes IJ to apply it to module B even if B does not depend on it

**To Reproduce**
1. Install Manifold IJ plugin 2020.1.31
2. Create a project with two independent modules A and B, where A has dependency on manifold-string, but not B
3. Create a Java file in each of A and B using string templates, notice the IJ incorrectly applies interpolation on B's file

**Comment by rsmckinney** [comment]
fixed with IJ plugin releases 2020.3.32, 2020.1.32, 2019.3.32

**Comment by schittli** [comment]
Thanks a lot for fixing this issue!... it looks perfect.
