### ISSUE TITLE
JEP 305 (''Pattern Matching for instanceof'') usage isn't recognised in IDEA with Manifold plugin enabled

### ISSUE THREAD

**Issue by Vyacheslav-Lapin** [manifold-systems/manifold#230]
**Description**
IDEA think, that following code:
```
public class ExperimentApplication {

  public static void main(String[] __) {
    method("lorem ipsum");
  }

  public static void method(CharSequence charSequence) {
    if (charSequence instanceof String string) {  // here is an error!
      System.out.println(string);
    }
  }
}
```
is incorrect for project in java 14-15 with --enable-preview flag enabled (in the time of compiling and running this code is OK with expected output: "lorem ipsum").

But, when I disable the Manifold plugin - it looks OK in IDEA. So, problem is in the Manifold plugin...

**Screenshots**
![image](https://user-images.githubusercontent.com/930608/99543946-cdeb2280-29c4-11eb-9cae-9c4c6f3dc03c.png)

**Desktop:**
- OS Type & Version: Mac OS Big Sur 11.0.1
- Java/JDK version: 15
- IDE version (IntelliJ IDEA or Android Studio): 2020.2
- Manifold version: - (bug present even for project without Manifold dependency - just plugin)
- Manifold IntelliJ plugin version: 2020.1.36

**Comment by rsmckinney** [comment]
@Vyacheslav-Lapin ah, i see the issue, expect a fix in the next release available within two days.  Thanks for reporting this!

**Comment by rsmckinney** [comment]
Fix available in latest plugin release.
