### ISSUE TITLE
"Ansi" Maven support

### ISSUE THREAD

**Issue by dyorgio** [manifold-systems/manifold#233]
This project supports build/compilation using only maven?
I tried all examples of pom (with different JDK version) without luck: Basic print() String Extension.

I'm using NetBeans, that I know that is not supported, but if I disable "Compile On Save" it only runs mvn with javac...

If it only works in conjunction with IDE plugin, please, include this information at first line of README.md.

If only using maven + javac is not possible to use manifold is a very big limitation, how we can use CI for build versions?

**Comment by rsmckinney** [comment]
@dyorgio Manifold works with all build systems including Maven, Gradle, and Ant. Manifold also provides comprehensive IDE support in IntelliJ IDEA and Android Studio, although you don't need IDE support to use Manifold in your project.

For your print() extension example please refer to the `manifold-ext` [Setup](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#using-this-project) documentation. Let me know if you still need help setting up. If your project is available on github or elsewhere I can set it up for you.

**Comment by dyorgio** [comment]
Hi @rsmckinney, thanks for rapid response.
I use Setup as base, and see other users issues opened here.
For a moment I think that this project only works with IDE plugin, sorry.
I'm attaching a sample (but it is mostly the same of Setup example) to you try to compile.
[project-file.zip](https://github.com/manifold-systems/manifold/files/5691078/project-file.zip)

**Comment by rsmckinney** [comment]
@dyorgio thanks for including the project.  The problem is that your String extension class is incorrectly defined. From the [documentation](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-classes-via-extension):
>All extension classes must be sub-rooted in the `extensions` package where the remainder of the package must be the qualified name of the extended class. As the example illustrates, an extension class on `java.lang.String` must reside directly in a package equal to or ending with `extensions.java.lang.String`. Note this convention facilitates the extension discovery process and avoids the overhead and ceremony of alternative means such as annotation processors.

So, to fix your example simply move your `StringExtensions` class to package like `dyorgio.extensions.java.lang.String`:

```java
package dyorgio.extensions.java.lang.String;

import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.This;
import java.lang.String;

/**
  * @author dyorgio
 */
@Extension
public class StringExtensions {

  public static void print(@This String thiz) {
    System.out.println(thiz);
  }
}
```

**Comment by dyorgio** [comment]
Oh gosh 😢.
Sorry to take your time @rsmckinney, this convention was new to me.
My first impression is that **Extension** was the key for identification (APT) and type of argument annotaded with **This** was responsible to define extended target class.
Thank you for pacience, it is a nice project, I'm looking for alternatives of lombok (more easy to add/extending features).

**Comment by rsmckinney** [comment]
It's all good, Enjoy!
