### ISSUE TITLE
Manifold Adds `<clinit>()V` To Interfaces

### ISSUE THREAD

**Issue by gudenau** [manifold-systems/manifold#239]
**Describe the bug**
Using Manifold (I've only tried extensions) adds an illegal non-public static method to unrelated interfaces.

**To Reproduce**
1. Create a project with extensions (Might be any module, untested)
2. Create an interface
3. Build
4. View interface bytecode

**Expected behavior**
Interfaces in the project should not be generated with an illegal method.

**Desktop (please complete the following information):**
- OS Type & Version: Arch 
- Java/JDK version: OpenJDK 15+36-1562
- IDE version (IntelliJ IDEA or Android Studio): Idea 2020.3.1U
- Manifold version: 2020.1.44
- Manifold IntelliJ plugin version: 2020.3.37

**Additional context**
The class [MinecraftClientAccessor](https://github.com/gudenau/minecraft-extension-crash/blob/master/src/main/java/net/fabricmc/example/mixin/MinecraftClientAccessor.java) is an example of this.

The source is:
```Java
package net.fabricmc.example.mixin;

import net.minecraft.client.MinecraftClient;
import net.minecraft.client.util.WindowProvider;
import org.apache.logging.log4j.Logger;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;

@Mixin(MinecraftClient.class)
public interface MinecraftClientAccessor{
    @SuppressWarnings("ConstantConditions")
    @Accessor static Logger getLOGGER(){ return (Logger)new Object();}
    @Accessor WindowProvider getWindowProvider();
}
```
This does not touch Manifold in any way, yet the generated class contains a static init block for Manifold.
```
// class version 52.0 (52)
// access flags 0x601
public abstract interface net/fabricmc/example/mixin/MinecraftClientAccessor {

  // compiled from: MinecraftClientAccessor.java

  @Lorg/spongepowered/asm/mixin/Mixin;(value={net.minecraft.client.MinecraftClient.class}) // invisible

  // access flags 0x9
  public static getLOGGER()Lorg/apache/logging/log4j/Logger;
  @Lorg/spongepowered/asm/mixin/gen/Accessor;()
   L0
    LINENUMBER 12 L0
    NEW java/lang/Object
    DUP
    INVOKESPECIAL java/lang/Object.<init> ()V
    CHECKCAST org/apache/logging/log4j/Logger
    ARETURN
    MAXSTACK = 2
    MAXLOCALS = 0

  // access flags 0x401
  public abstract getWindowProvider()Lnet/minecraft/client/util/WindowProvider;
  @Lorg/spongepowered/asm/mixin/gen/Accessor;()

  // access flags 0x8
  static <clinit>()V
   L0
    LINENUMBER 12 L0
    INVOKESTATIC manifold/rt/api/IBootstrap.dasBoot ()Z (itf)
    POP
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 0
}
```
Which causes an error in the [Mixin](https://github.com/SpongePowered/Mixin) library because of the illegal method deceleration, as can be seen [here](https://github.com/FabricMC/Mixin/issues/42).

**Comment by rsmckinney** [comment]
Fix available in release 2020.1.45. (thanks for reporting this!)
