### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zxa4fd** [manifold-systems/manifold#244]
-What features are in Manifold that are not in Lombok and Vise Versa?
-Is Manifold lightweight?

**Comment by rsmckinney** [comment]
Hi @zxa4fd.

Q. What features are in Manifold that are not in Lombok and Vise Versa?
A. There no much overlap between them. I think Extension Methods are the  only feature they share in common. Manifold is implemented differently using the type manifold concept. There's a high-level description of many of Manifold's features on the [Manifold readme](https://github.com/manifold-systems/manifold).

Q. Is Manifold lightweight?
A. Yes. Manifold does the heavy lifting at compile-time. The runtime dependencies range from relatively small to zero. 

Hope this helps.

>Note, you can ask questions on Manifold's [Slack Group](https://join.slack.com/t/manifold-group/shared_invite/zt-e0bq8xtu-93ASQa~a8qe0KDhOoD6Bgg) too.

**Comment by fabriceci** [comment]
￼I just discovered manifold, I take advantage of the thread to add few questions.

Seems that there is an overlap, in the sense that both helps to reduce the java heaviness, manifold seems just to offer just more than that.

- Is-it conceivable to add the few features in the Lombok ta help the code reduction in the same or different form (mainly entity/bean method generation)? Seems easier to just use one library of this kind.
￼
- Is this possible with this technique to add more features that help to reduce the heaviness of java? Like default parameters values for methods, and other nice Kotlin features. If yes, are you interested to start an issue to list ideas?

**Comment by rsmckinney** [comment]
Hi @fabriceci.

How did you discover manifold?

**Q.** Is-it conceivable to add the few features in the Lombok ta help the code reduction in the same or different form (mainly entity/bean method generation)? Seems easier to just use one library of this kind.

**A.** It would be nice to somehow combine the projects, however the architectures are quite different; I'm not certain it's workable. Also, there is very little overlap, I think _extension methods_ is the only common feature. Anyhow, having them both work in tandem should be fine. Are there specific concerns you have?

Another consideration: manifold is a project consisting of several sub-projects. For instance, [manifold-graphql](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-graphql) is a separate dependency from, say, [manifold-preprocessor](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-preprocessor).  It is designed to be used à la carte.

**Q.** Is this possible with this technique to add more features that help to reduce the heaviness of java? Like default parameters values for methods, and other nice Kotlin features. If yes, are you interested to start an issue to list ideas?

**A.** Absolutely. As it happens a new feature is in the works: a [_properties_](#242) language construct that is quite similar to Kotlin's, but using existing Java syntax. This feature will be available soon as the _manifold-props_  sub-project, which builds on the existing [_manifold-ext_](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext) sub-project.

Please create new issues for any ideas or requests you have; it's pretty informal here and I'm always interested.  Also feel free to discuss stuff in the [slack group](https://join.slack.com/t/manifold-group/shared_invite/zt-e0bq8xtu-93ASQa~a8qe0KDhOoD6Bgg), as you prefer.

Cheers!
