### ISSUE TITLE
GraphQL Custom Scalar example implementation request

### ISSUE THREAD

**Issue by superduper** [manifold-systems/manifold#246]
Hello! 

I'm trying to implement a bunch of custom scalars like JSON, PositiveInteger, akin to what [graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars) has to use with manifold client. Could you add a complete example of how to add a custom GraphQL scalar? 

Thank you!

**Comment by rsmckinney** [comment]
relates to https://github.com/manifold-systems/manifold/issues/247

**Comment by rsmckinney** [comment]
Here's a [sample project](https://github.com/manifold-systems/manifold-sample-graphql-scalars) demonstrating how to make custom scalars and how to incorporate them into a project using manifold-graphql.

Hope this helps.
