### ISSUE TITLE
Can't use extension methods from Jar dependency

### ISSUE THREAD

**Issue by YounesRahimi** [manifold-systems/manifold#25]
I asked a question by email. The question  was this:

Could we use Extensions from other libraries?
I have written a library of extensions. But I can't call these extension methods from other projects and the compiler throws this error:

java: cannot find symbol
  symbol:   method println()
  location: variable hello of type java.lang.String

My extensions can be called from their project successfully but can't be called from other projects.
Is there any way to support this?

**Comment by YounesRahimi** [comment]
And the answer was this:

Yes, you can use Extensions from other libraries, it works like a normal project dependency.  For example, if extension project compiles to my-extensions.jar, another project can use my-extensions.jar, but it must compile with manifold-all.jar and all its dependencies as well.  The other project must also include -Xplugin:Manifold as a javac argument.  All of this is documented in the Setup instructions.  If the other project uses Maven or Gradle, it's a simple matter of adding the manifold-all dependency and compiler arg -- you can copy/paste from the setup instructions.

**Comment by YounesRahimi** [comment]
Well, I was done all of the setup instructions and I still couldn't call extensions from a library.
To clarify, I created two GitHub repositories:
[java-extensions](https://github.com/YounesRahimi/java-extensions): Which contains my extensions.
[manifold-sample-project](https://github.com/YounesRahimi/manifold-sample-project): Which is a fork of the main manifold-sample-project and I used my extensions in it.

But it still doesn't recognize the extensions and print an error like the first post.

**Comment by rsmckinney** [comment]
Hi Younes.

Thanks for reporting this.

I failed to mention one requirement.  Because your `java-extenstions` project contains extension classes, it must include some information in the jar file's manifest, specifically it must add a `<Contains-Sources>` entry.  You can do this in Maven like via `maven-jar-plugin` in your pom file:

```xml
  <build>
    <plugins>
...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <!--class files as source must be available for extension classes-->
                            <Contains-Sources>java,class</Contains-Sources>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

        </plugins>
    </build>
```

**Comment by rsmckinney** [comment]
Bug:  Missing documentation regarding `<Contains-Sources>` to publish jar/module with extension classes

**Comment by YounesRahimi** [comment]
Thanks. It worked.
