### ISSUE TITLE
How can we create objects of  GraphQL Result classes?

### ISSUE THREAD

**Issue by cloudmali** [manifold-systems/manifold#250]
Have a question or something to say?  This is the place.  Check out the Manifold FAQ at  http://manifold.systems/faq.html
Hello,
I am trying to create unit tests for graphql schema. Is there a way to create new result objects? If not, what is the best way to test the graphql calls?

**Comment by rsmckinney** [comment]
Hi @cloudmali.  You have some options.  Since the GraphQL API is built with structural interfaces you can use JSON bindings directly like this:
```java
DataBindings jsonResult = loadJsonResult();
ActorQuery.Result expected = jsonResult; // structural interface maps directly to JSON bindings (and any Map)
. . .
ActorQuery.Result result = ActorQuery.request(ENDPOINT).post();
assertEquals(expected, result);
```
You can also implement your result types, which is nice for special cases.
```java
class MyResult implements ActorQuery.Result {
  private final DataBindings _result;
  public MyResult() {
    _result = new DataBindings();
  }
  public MyResult(DataBindings result) {
    _result = result;
  }

  // add methods to build result for different use-cases
}
```
Another option is to simply write tests directly against the results:
```java
  @Test
  public void testActorQuery_Single_Genre() {
    ActorQuery actorQuery = ActorQuery.builder("Le Mans").withGenre(Action).build();
    ActorQuery.Result result = actorQuery.request(ENDPOINT).post();
    var actors = result.getActors();
    assertEquals(1, actors.size());
    var actor = actors.get(0);
    assertEquals("Steve McQueen", actor.getName());
  }
```

**Comment by cloudmali** [comment]
Thanks a lot @rsmckinney.

**Comment by cloudmali** [comment]
I am using an existing API, it is not possible for me to write tests against results. Looking for an option to mock the result. I have created a method :
``  
public <T extends GqlQueryResult> T post(@NonNull final Executor<T> request) {
    return request.post();
}
``
and I am trying to mock response of this method :
``
doReturn(actor).when(graphQLExecutor).<queries.ActorQuery.Result>post(Mockito.any());
``
but I always get this from mockito : 

``
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
DataBindings cannot be returned by post()
post() should return GqlQueryResult
``
even when actor is of type queries.ActorQuery.Result or even GqlQueryResult.
Is there any other option to mock graphql response?

**Comment by rsmckinney** [comment]
This is because mockito does not understand manifold's structural interfaces. Can you change your method to:
```java
public <T> T post(@NonNull final Executor<T> request) { return request.post(); }
```
and then cast the result to your liking?

**Comment by cloudmali** [comment]
Worked perfectly. Thank you!

**Comment by cloudmali** [comment]
Sorry I said it worked prematurely. I am actually getting something like :
    java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to x.y.queries$ActorQuery$Result$actorByName
