### ISSUE TITLE
manifold-ext with jooq failed.

### ISSUE THREAD

**Issue by yueliangwen** [manifold-systems/manifold#251]
I wanna extend the ResultQuery of jooq(3.14.8) in the JooqResultQueryExt java file, it cannot compile correctly. All the code in the following attachment。
[problem-ext.tar.gz](https://github.com/manifold-systems/manifold/files/6095866/problem-ext.tar.gz)

**Comment by rsmckinney** [comment]
The next release will contain the fix for this, likely by Monday morning. One thing, since jooq uses the JetBrains annotations library in its source, you will also need to include a compile dependency on that:  `compile 'org.jetbrains:annotations:15.0'`

Thanks for reporting this!

**Comment by rsmckinney** [comment]
Fix available in release [2021.1.0](https://github.com/manifold-systems/manifold/releases/tag/v2021.1.0)

**Comment by yueliangwen** [comment]
Cool, thanks @rsmckinney .
