### ISSUE TITLE
Add mol to Manifold science

### ISSUE THREAD

**Issue by bartimaeusnek** [manifold-systems/manifold#252]
**Is your feature request related to a problem? Please describe.**
Im currently working on a chemistry lib and would like to see manifold science to support the SI unit mol.
 
**Describe the solution you'd like**
Have mol implemented like kilogram

**Describe alternatives you've considered**
There aren't really any, one could do a third party lib, but i guess SI units should be upstream functionality...

**Comment by rsmckinney** [comment]
Hi @bartimaeusnek.  Guess what?  It's already there :)  See `manifold.science.util.DimensionlessConstants#mol`

**Comment by rsmckinney** [comment]
If you have other ideas about `mol`, please provide an example.  Thanks!

**Comment by bartimaeusnek** [comment]
oh thank you!
