### ISSUE TITLE
Eclipse support

### ISSUE THREAD

**Issue by Monniasza** [manifold-systems/manifold#262]
**Is your feature request related to a problem? Please describe.**
I'm currently making a [computer game](https://github.com/MultiMachineBuilder/MultiMachineBuilder) with several interfaces, which have several mandatory variables eg. `BlockType`, where there are six properties: `leaveBehind`, `drop`, `title`, `id`, `description` and `texture`. Implementation of all of them is difficult, but I use common base class for both `Block` and `BlockEntityType`

**Describe the solution you'd like**
An Eclipse plugin, which is available on Eclipse Marketplace for convenient installation

**Describe alternatives you've considered**
Manually generated get...() and set...() methods,  but they contain boilerplate code

**Comment by rsmckinney** [comment]
@Monniasza Hi.  Yeeaaahh.  Eclipse plugin.  Probably not going to happen.  If I had more time, I'd do it.  Maybe someday...

**Comment by soundasleep** [comment]
Another 🙏 for Eclipse support some day ^_^
