### ISSUE TITLE
Strange behavior using same class with preprocessor directives in two different projects

### ISSUE THREAD

**Issue by AleMuzzi** [manifold-systems/manifold#263]
**Describe the bug**
It seems that the plugin has some difficulties when the same class (in my test even with the same package), which uses some preprocessor directives, is used in more than one project and those projects are open at the same time.
The result is that the Manifold plugin keeps raising exceptions continuously because (if I have correctly understood) there are two classes with the same name but with different uuid.
I really don't know if my supposition it's correct, below the report.

**To Reproduce**
Explained in the description.

**Expected behavior**
Not to raise any exception since those are separate projects.

**Screenshots**
![image](https://user-images.githubusercontent.com/7605774/115790021-56338080-a3c6-11eb-8df3-b05765534ae4.png)
**NB:** note that the involved-file path at the start of the stacktrace contains *assegnamento1* but the current project was *assegnamento2*

**Desktop (please complete the following information):**
- OS Type & Version:  macOS Catalina
- Java/JDK version: JDK 16 (X)
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2020.3.2, here some informations about it:
```
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to Alessandro Muzzi
Subscription is active until December 28, 2021.
For educational use only.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: actionSystem.force.alt.gr=true
Non-Bundled Plugins: manifold.ij, Dart, org.jetbrains.kotlin
```
- Manifold version: 2021.1.10
- Manifold IntelliJ plugin version: 2020.3.40

**Stack trace**
[stacktrace.txt](https://github.com/manifold-systems/manifold/files/6361488/stacktrace.txt)
[LogManager.java_file.txt](https://github.com/manifold-systems/manifold/files/6361492/LogManager.java_file.txt)
[stubTree.txt](https://github.com/manifold-systems/manifold/files/6361494/stubTree.txt)
[stubTreeFromIndex.txt](https://github.com/manifold-systems/manifold/files/6361495/stubTreeFromIndex.txt)

**Comment by AleMuzzi** [comment]
Update: the exceptions are raised even if only one project is open and will continue (overloading the IDE and causing issues with the syntax checking) until the involved file (_LogManager.java_) is not opened, then the file can be closed and no more exceptions are raised.

**Comment by rsmckinney** [comment]
@AleMuzzi Hi. Cannot reproduce this. Is your project publicly available?  Can you provide a project that demonstrates this error?

**Comment by AleMuzzi** [comment]
The involved projects are those:
https://bitbucket.org/alessandromuzzi17/assegnamento1
https://bitbucket.org/alessandromuzzi17/assegnamento2

**Comment by AleMuzzi** [comment]
I just noticed that somehow it's not required to open both projects at the same moment to get the errors, I don't know if manifold keeps some references in cache or something like that

**Comment by rsmckinney** [comment]
@AleMuzzi can you provide the manifold dependencies your project[s] use?  I assume you are using manifold-preprocessor, however from the stack trace it appears you may also be using manifold-props.  Is that the case?  Thanks.

**Comment by AleMuzzi** [comment]
I have just made public the involved projects linked above, you should be now allowed to see what you want.

**Comment by rsmckinney** [comment]
Thanks @AleMuzzi.  I've tested the projects with the latest manifold release (2021.1.34) and latest IJ plugin releases (2021.x.38) and android studio release (2020.3.47).  All look good on my end.  Please test this with latest updates if you have time.  Thanks!

**Comment by AleMuzzi** [comment]
Hi,
I'm glad you can run them without any issue.
Unfortunately those were projects that ended in themselves and at the
moment I'm not using Manifolds.

Good luck with your library and have a good day,
Alessandro Muzzi

Il gio 16 dic 2021, 03:00 Scott McKinney ***@***.***> ha
scritto:
