### ISSUE TITLE
[IDEA Plugin] Property inference sometimes doesn't work

### ISSUE THREAD

**Issue by XiaoPangxie732** [manifold-systems/manifold#265]
**Describe the bug**
Produces errors in IDEA(but can be successfully compiled) sometimes when using property inference.

**To Reproduce**
1. Get/Set a property that uses `property inference`
2. Wait for a few minutes, then restart IDEA.
3. Errors produced, but the project can be successfully compiled

**Expected behavior**
Doesn't produce any errors in IDEA.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).
![image](https://user-images.githubusercontent.com/47449269/116826742-22c3d380-abc8-11eb-96d0-4de255e9890f.png)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 x64
- Java/JDK version: 16.0.1
- IDE version (IntelliJ IDEA or Android Studio): 2021.2.1
- Manifold version: 2021.1.16
- Manifold IntelliJ plugin version: 2021.2.15

**Comment by XiaoPangxie732** [comment]
@rsmckinney Hi. The second picture "Cannot assign read-only property 'xxx'" bug may relate to #273 and have been fixed. Could you please fix the first picture "'field' has xxx access in 'class'" bug faster? But anyway, thanks for your great project!

**Comment by rsmckinney** [comment]
Fixed in release 2021.2.16
