### ISSUE TITLE
if you use String.format("%$1s", "first") format, string templates do not work

### ISSUE THREAD

**Issue by tstauffer** [manifold-systems/manifold#268]
Please add a global compiler switch to only allow "${myProperty}" style replacements vs "$myProperty" to avoid the issue this has when compiling

Example compile error
error: cannot find symbol
    throw new TimeTravelException(String.format("Expected date: %2$s.  The system date (%1$s) must be between %2$s and %3$s (%4$s days).", systemDate, startDate, endDate, Math.abs(ChronoUnit.DAYS.between(startDate, endDate))));
                                                                   ^
  symbol:   variable s
  location: class TimeTravel

**Comment by rsmckinney** [comment]
You can escape the $ with `\$`, also you can bypass string templates entirely at different levels of your code, see https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-strings#bypassing-string-template-processing

**Comment by tstauffer** [comment]
The issue I have is that this code exists in numerous places within our code base.  I don't want to fix each of those places just to drop in a feature.  I would rather drop the feature in with a precursor that it only works a certain way (e.g. ${x}

**Comment by rsmckinney** [comment]
Gotcha.  Wanted to be sure you were aware of existing means to bypass.  I like your idea to opt out of $foo syntax.  The change will likely make it into the next release.

**Comment by tstauffer** [comment]
That would be fantastic.  thanks for the quick turnaround.  This is really amazing technology.

**Comment by rsmckinney** [comment]
Available in release 2021.1.13
