### ISSUE TITLE
no such type exists in the schema: 'Date'

### ISSUE THREAD

**Issue by skHollywood** [manifold-systems/manifold#271]
Have a question or something to say?  This is the place.  Check out the Manifold FAQ at  http://manifold.systems/faq.html
When trying to use scalar Date, I receive no such type exists in the schema: 'Date'

Any Idea why? I am not able to send date in my query

**Comment by skHollywood** [comment]
---------------person.graphql---------------------------------
scalar Date

person(fst_nm: String, lst_nm: String, bth_dt: Date)

-------------query.graphql----------------
query PersonExists ($fst_nm: String, $lst_nm: String, $bth_dt: Date) {
    person(where: {fst_nm: {_eq: $fst_nm}, lst_nm: {_eq: $lst_nm}, bth_dt: {_eq: $bth_dt}}) {
        person_id
        fst_nm
        lst_nm
        bth_dt
    }
}

--------------------- Java class ----------------

person.setBirthDate(LocalDate(1990, 03, 10))

**Comment by rsmckinney** [comment]
@skHollywood, is the error on the client or the server? Is there a stack trace? Have you compared your application's project configuration to the manifold [sample graphql application](https://github.com/manifold-systems/manifold-sample-graphql-app)?

**Comment by skHollywood** [comment]
It was server error. I did not save error.

changing  from 'Date'  to  'date' worked.
using java.time.LocalDate to send value to server

**Comment by rsmckinney** [comment]
Ok, that makes sense.  The server's scalar definitions must match the client's, in this case "date".  The server's published graphql schema should contain the scalars.

>If you don't have the server's schema, you can download it using a graphql reflection query, which is made easy from IntelliJ or Android Studio using the JS GraphQL plugin.
