### ISSUE TITLE
Is it possible to make SQL DSL like this?

### ISSUE THREAD

**Issue by kozeretskovsky** [manifold-systems/manifold#272]
`
InventTable inventTable = new InventTable(); //Table model
InventSalesModule ism = new InventSalesModule() //Another model

//DSL LIKE THIS

select id, name from inventTable
  join price from ism
     where inventTable.id == ism.InventTableId {
     print ("Price %1, %2", inventTable.name, ism.price);
}
`
Under the hood i want to process SQL query and need some callbacks from manifold engine to refer DSL variables and real java model. Something like this. Is it possible?

**Comment by kozeretskovsky** [comment]
Thank you for answer @rsmckinney !

Is it possible to realise my DSL with pure Java Compiler Plugin API?

**Comment by rsmckinney** [comment]
With manifold in its current form, no.

Apart from manifold, If you mean to build your own compiler plugin, yes it's _possible_, but probably not justifiable based on the amount of work involved.

**Comment by kozeretskovsky** [comment]
Thank you for answer!
