### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by masfbeca** [manifold-systems/manifold#274]
When  I build my test project with intellij IDEA, I got this "java: java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider manifold.internal.javac.JavacPluginBootstrap could not be instantiated" error.   
More detail is:
java: java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider manifold.internal.javac.JavacPluginBootstrap could not be instantiated
java: 	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
java: 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
java: 	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
java: 	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1393)
java: 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:220)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
java: 	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:231)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:514)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:560)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:512)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:355)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:280)
java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:234)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1464)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1101)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1247)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1066)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:832)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:419)
java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)
java: 	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
java: 	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:301)
java: 	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)
java: 	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)
java: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
java: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
java: 	at java.base/java.lang.Thread.run(Thread.java:831)
java: Caused by: java.lang.NoClassDefFoundError: manifold/rt/api/util/StreamUtil
java: 	at manifold.internal.javac.JavacPlugin.loadJavacParserClass(JavacPlugin.java:1273)
java: 	at manifold.internal.javac.JavacPlugin.<clinit>(JavacPlugin.java:129)
java: 	at manifold.internal.javac.JavacPluginBootstrap.<init>(JavacPluginBootstrap.java:37)
java: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
java: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
java: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
java: 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
java: 	... 29 more
java: Caused by: java.lang.ClassNotFoundException: manifold.rt.api.util.StreamUtil
java: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
java: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
java: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
java: 	... 38 more
java: Compilation failed: internal java compiler error
Checking dependencies... [ManifoldTest]
Dependency analysis found 0 affected files
Errors occurred while compiling module 'ManifoldTest'
javac 16.0.1 was used to compile java sources
Finished, saving caches...
Compilation failed: errors: 1; warnings: 0
Executing post-compile tasks...
Loading Ant configuration...
Running Ant tasks...
Synchronizing output directories...

=====================================================

The manifold version is :2021.1.12 
Plugin version is : 2021.1.10

**Comment by rsmckinney** [comment]
@masfbeca Hi. Is your test project shared on github or similar?

**Comment by masfbeca** [comment]
@rsmckinney 
I change my project's  Java SDK to 11, then slove the problem.
Now it's works perfect for me.
Thank for your excellent product.
