### ISSUE TITLE
Bearer Authorization broken when calling graphQL server

### ISSUE THREAD

**Issue by YJa4u9** [manifold-systems/manifold#279]
When calling graphQL query like this:

```
var results = query.request(queryUrl)
  .withTimeout(20000)
  .withBearerAuthorization(openIdRefreshToken)
  .withHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
  .withHeader(HttpHeaders.ACCEPT, "application/json")
  .post();
```

I get this error:

`java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode`

I believe it is coming from **HttpURLConnection** in **ManUrlExt.java**. The [HttpURLConnection javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/HttpURLConnection.html#setChunkedStreamingMode(int)) says:

> When output streaming is enabled, authentication and redirection cannot be handled automatically. A HttpRetryException
> will be thrown when reading the response if authentication or redirection are required. This exception can be queried for
 > the details of the error.

I am using authentication, as you can see from the call to `withBearerAuthorization()`

**Comment by rsmckinney** [comment]
@YJa4u9  Bearer authorization works fine, many manifold graphql clients use it.  Here's a snippet using the GitHub GraphQL API:
```java
            Endpoint PROXY_ENDPT = new Endpoint("https://api.github.com/graphql");
            . . .
            var repos = queries.OwnerRepos.builder(org, 2)
                    .withAfterCursor(cursor)
                    .build()
                    .request(PROXY_ENDPT)
                    .withBearerAuthorization("<your-token-here>")
                    .post()
                    .getRepositoryOwner()
                    .getRepositories();
```
