### ISSUE TITLE
IntelliJ 2021.2 Community Edition / Manifolg Plugin 2020.3.37: Null Ptr Exceptions

### ISSUE THREAD

**Issue by schittli** [manifold-systems/manifold#281]
**Describe the bug**

Good evening
it's really a pity that you no longer provide Manifold for non-profit organisations for free. Before I delete it, I'll send a bug report: 
After updating to IntelliJ Community Edition 2012.2, the IDE reports Fatal Errors. I attach the stacktrace files here.

**To Reproduce**
1. Open IntelliJ
2. Install the Manifold Plugin 2020.3.37

**Desktop (please complete the following information):**
- OS Type & Version: Win 10 2004
- Java/JDK version: 1.8
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ CE
- Manifold version: 2021.1.14
- Manifold IntelliJ plugin version: Manifold Plugin 2020.3.37

**Stack trace**
I add all the Stacktraces which I've got.

Kind regards,
Thomas

[stacktrace1.txt](https://github.com/manifold-systems/manifold/files/6927340/stacktrace1.txt)
[stacktrace2.txt](https://github.com/manifold-systems/manifold/files/6927343/stacktrace2.txt)
[stacktrace3.txt](https://github.com/manifold-systems/manifold/files/6927344/stacktrace3.txt)
[stacktrace4.txt](https://github.com/manifold-systems/manifold/files/6927345/stacktrace4.txt)
[stacktrace5.txt](https://github.com/manifold-systems/manifold/files/6927346/stacktrace5.txt)
[stacktrace6.txt](https://github.com/manifold-systems/manifold/files/6927347/stacktrace6.txt)
[stacktrace7.txt](https://github.com/manifold-systems/manifold/files/6927348/stacktrace7.txt)

**Comment by rsmckinney** [comment]
@schittli Hi Tom.  Manifold always has been and always will be free for non-profits, students, faculty, etc.  Not sure what's happened with your personal environment.  I do know JetBrains recently (finally) extended their product discounts and deals to plugins with full and automatic support from within IDEA. Perhaps there's a glitch with that?  In any case Manifold is free regardless of what JetBrains does -- it still operates after the trial period ends, you can ignore the message when you load your project.  JetBrains is working on a cleaner solution for "paid" plugins like mine that are just using the JetBrains Marketplace as a quasi-donation platform. We'll see.

As for 2021.2 support, yes that'll come soon.

Cheers.

**Comment by schittli** [comment]
Hello Scott (@rsmckinney)

thank you **very much** that we can still use your great work for the non-profit work for free! I thought it changed because the plugin website lists the "Discounted and Complimentary Licenses":
https://plugins.jetbrains.com/plugin/10057-manifold/pricing

I am really happy because developing with Manifold and Java is finally almost as much fun as with C# ;-)

**Comment by schittli** [comment]
# Regarding the stack traces…

Hello Scott (@rsmckinney)

> Regarding the stack traces, do any of these cause actual problems as you use IDEA / Manifold?

You are right with your supposition!, I was intimidated by the exceptions, but I can work normally.

After a few months break, I just started working last night with IntelliJ and Manifold again, so it could be that I haven't noticed yet that it is causing a problem.

If you want, you can close this issue and I'll get back to you if I notice anything else.

Kind regards, Tom
