### ISSUE TITLE
IntelliJ Plugin, exception: `manifold.ij.extensions.ResourceToManifoldUtil: Access is allowed from event dispatch thread only`

### ISSUE THREAD

**Issue by schittli** [manifold-systems/manifold#286]
Good evening

I suspect that this issue predates the Plugin version 2021.2.16. Except for this new issue here, 2021.2.16 is really great. 

**Describe the bug**
When working, IntelliJ keeps reporting this exception (two stacktraces are at the end):
`Access is allowed from event dispatch thread only`

I guess that this exception _never_ happens if the compiler is started by hand 😊, because I have tested:
- Calling 10x Build » Recompile current File
- Calling 5x Build » Rebuild Project

The compiler always perfectly worked.
Therefore, it looks like a 'background compiler' issue.

I've collected the Stacktrace-Files provided by IntelliJ for two exceptions, see below.

**To Reproduce**
I have not yet found a way to enforce the error.

**Desktop (please complete the following information):**
- OS Type & Version: Window 10, 2004, x64 
- Java/JDK version: 1.8.0_162
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
- Manifold version: 2021.1.16
- Manifold IntelliJ plugin version: 2021.2.16

**Stack trace**
Exception #1
[1 - stacktrace.txt](https://github.com/manifold-systems/manifold/files/7086946/1.-.stacktrace.txt)
[1 - threadDump.txt](https://github.com/manifold-systems/manifold/files/7086947/1.-.threadDump.txt)
[1 - induced.txt](https://github.com/manifold-systems/manifold/files/7086945/1.-.induced.txt)

Exception #2
[2 - stacktrace.txt](https://github.com/manifold-systems/manifold/files/7086948/2.-.stacktrace.txt)
[2 - threadDump.txt](https://github.com/manifold-systems/manifold/files/7086949/2.-.threadDump.txt)

**Comment by schittli** [comment]
Hello @rsmckinney 

thank you very much for your support and your note about the resource files mapping!
I am indeed using a json file as a resource, but it is mapped in IJ:

![image](https://user-images.githubusercontent.com/8282673/131895589-912c7e0a-b624-41e7-8bf8-e5d9ae195ecf.png)


Therefore, I thought, I check if all file types in my project are mapped in IJ, but my project actually has 111 file types 😅 

Among the file types that are referenced as resources (and not as source or unit test code) in the Java project, I also have e.g. wav, word and excel files and I suspect that it is quite common that such file types are present as resources for which IJ does not have a viewer and therefore, I guess, that those files are not mapped in IJ.

Therefore I am confident that your updated version has a good solution.

Thanks a lot, kind regards,
Thomas

**Comment by rsmckinney** [comment]
Hey Tom, that's a lotta resources.  I was really only referring to resource files you *use* in IJ, ones you view or edit.  I imagine that set of files is much smaller. In any case, yes, the new release fixes this issue so no intervention is required on your part, and thanks for reporting it!
