### ISSUE TITLE
Generic issues with Intellij 

### ISSUE THREAD

**Issue by cyberpwnn** [manifold-systems/manifold#287]
The extension class

```java
package extensions.java.util.List;

import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.Self;
import manifold.ext.rt.api.This;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

@Extension
public class XList {
    public static <T> @Self List<T> copy(@This List<T> self)
    {
        return new ArrayList<>(self);
    }

    public static <T> @Self List<T> copy(@This List<T> self, Supplier<List<T>> factory)
    {
        List<T> t = factory.get();
        t.addAll(self);
        return t;
    }
}
```

Using it 
```java
package art.arcane.amulet;

import java.util.ArrayList;
import java.util.List;

public class Amulet {
    public static void main(String[] a)
    {
        List<String> f = new ArrayList<>();
        f.add("a");
        f.add("b");

        List<String> c = f.copy(); // Half of the time ITJ suggests i change the type to List<T>
    }
}
```

Build.gradle
```gradle
plugins {
    id 'java'
    id 'java-library'
}

group 'art.arcane'
version '1.0'

targetCompatibility = 16
sourceCompatibility = 16

repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

configurations {
    // give tests access to annotationProcessor dependencies
    testImplementation.extendsFrom annotationProcessor
}

jar {
    manifest {
        attributes('Contains-Sources':'java,class')
    }
}

dependencies {
    implementation 'systems.manifold:manifold-ext-rt:2021.1.16'
    annotationProcessor group: 'systems.manifold', name: 'manifold-ext', version: '2021.1.16'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}

if (JavaVersion.current() != JavaVersion.VERSION_1_8 &&
        sourceSets.main.allJava.files.any {it.name == "module-info.java"}) {
    tasks.withType(JavaCompile) {
        // if you DO define a module-info.java file:
        options.compilerArgs += ['-Xplugin:Manifold', '--module-path', it.classpath.asPath]
    }
}
```

:build
```
6:01:17 PM: Executing tasks ':testClasses :classes'...


> Task :compileJava FAILED
1 actionable task: 1 executed
C:\Users\arcane\Documents\development\workspace\Amulet\src\main\java\art\arcane\amulet\Amulet.java:13: error: cannot find symbol
        List<String> c = f.copy();
                          ^
  symbol:   method copy()
  location: variable f of type List<String>
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 154ms
6:01:17 PM: Tasks execution finished ':testClasses :classes'.
```

![image](https://user-images.githubusercontent.com/10619135/131922285-c2fd0caa-2bc6-4470-b596-230c153ddce2.png)

* This happens with or without @Self
* Cleaning doesnt fix it
* Invalidate caches/reset doesnt fix it

**Comment by rsmckinney** [comment]
Hi @cyberpwnn. The short answer is you need to change the name of your type variable from `T` to `E`. This has to do with the way manifold generates code internally and is explained in the [docs](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#generics):

>## Generics
>
>You can extend generic classes too and define generic methods. This is how Manifold extension libraries
>work with collections and other generic classes. For example, here is the `first()` extension method on
>`Iterable`:
>
>```java
>public static <T> T first(@This Iterable<T> thiz, Predicate<T> predicate) {
>  for (T element: thiz) {
>    if (predicate.test(element)) {
>      return element;
>    }
>  }
>  throw new NoSuchElementException();
>}
>```
>
>Notice the extension is a generic method with the same type variable designation as the
>extended class: `T` from `Iterable<T>`. Since extension methods are static this is how we convey type
>variables from the extended class to the extension method. Note type variable names must match the 
>extended type's type variables and must be declared in the same order.
>
>To define a generic extension method you append the type variables of the method to the list of the
>extended class' type variables. Manifold's `map()` extension illustrates this format:
>
>```java
>public static <E, R> Stream<R> map(@This Collection<E> thiz, Function<? super E, R> mapper) {
>  return thiz.stream().map(mapper);
>}
>```
>
>Here `map` is a generic extension method having type variable `R` and conveying `Collection`'s type
>variable `E`.

Additionally, if you ever find that IJ is not working with extensions, sometimes it gets out of sync, so you need to refresh the project e.g., using the Maven or Gradle refresh button.

**Comment by cyberpwnn** [comment]
I am assuming I need to match the same generic variable name as the class im extending? Such that

```java
class Thing<X> {}
```

Extending it must use **X**?

**Comment by cyberpwnn** [comment]
Though, Replacing that method with E still gives cannot find symbol, again after refreshing gradle, invalidating / cleaning etc

```java
C:\Users\arcane\Documents\development\workspace\Amulet\src\main\java\art\arcane\amulet\Amulet.java:13: error: cannot find symbol
        List<String> c = f.copy();
                          ^
  symbol:   method copy()
  location: variable f of type List<String>
```

With

```java
public static <E> @Self List<E> copy(@This List<E> self)
{
    return new ArrayList<>(self);
}
```

Though... oddly enough IJ doesnt complain about it in the editor, its just when building or trying to execute.

**Comment by rsmckinney** [comment]
With the correct type variable name, your example works fine for me.

**Comment by cyberpwnn** [comment]
Still not really sure what i did but after tinkering for an hour its working now thanks for the help!
