### ISSUE TITLE
[IntelliJ Plugin] Incompatible types. required: 'manifold.rt.api.anno.any[]'

### ISSUE THREAD

**Issue by XiaoPangxie732** [manifold-systems/manifold#288]
**Describe the bug**
When adding annotations to a property's getter/setter, shows up errors in IntelliJ.

**To Reproduce**
1. Define a property and add annotations to its getter/setter.
2. IntelliJ shows up errors

**Expected behavior**
No errors show up.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).
![image](https://user-images.githubusercontent.com/47449269/132060265-073e0316-6734-4472-ba2d-ad57f800c20c.png)
**Both `annos` and `param` are affected.**

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 x64
- Java/JDK version: AdoptOpenJDK 16.0.1 
- IDE version (IntelliJ IDEA or Android Studio): 2021.2.1
- Manifold version: 2021.1.16
- Manifold IntelliJ plugin version: 2021.2.17

**Comment by rsmckinney** [comment]
Hi @XiaoPangxie732.  Yes, this is a known issue exclusive to the IntelliJ plugin, it will compile just fine.  I will fix this asap.  Thanks for reporting it.

**Comment by rsmckinney** [comment]
Fix available in Manifold IntelliJ plugin release 2021.2.18

**Comment by XiaoPangxie732** [comment]
It works for me. Thanks!
