### ISSUE TITLE
@Self not working with annotation processors such as lombok

### ISSUE THREAD

**Issue by YounesRahimi** [manifold-systems/manifold#29]
Hi 

This is an extension method with `@Self` type from Manifold Docs:
```java
public static <K,V> @Self Map<K,V> add(@This Map<K,V> thiz, K key, V value) {
  thiz.put(key, value);
  return thiz;
}
```
If I use this extension method it will throw a compile time error:
```java
// Will throw Error: java: incompatible types: java.util.Map<java.lang.Integer,java.lang.String> cannot be converted to java.util.HashMap<java.lang.Integer,java.lang.String>
HashMap<Integer,String> map1 = new HashMap<Integer, String>().add(1, "One").add(2, "Two").add(3, "Three");
```
I use Manfold version RELEASE and JDK 8.

**Comment by rsmckinney** [comment]
Hi Younes.

I can't reproduce this issue, it works fine for me with Java 8 (and 11).  Maybe try a specific Manifold release, the latest is `0.28-alpha`.  If that doesn't help, you can post your project here for me to test.

**Comment by YounesRahimi** [comment]
[https://github.com/YounesRahimi/java-extensions](https://github.com/YounesRahimi/java-extensions)

Run `RunMe.java`

**Comment by WilliamStone** [comment]
I have problem making lombok and manifold work together, either in Intellij Idea, or in maven.
I tried to clone above code sample (https://github.com/YounesRahimi/java-extensions) and modify manifold version in its pom.xml to 0.39-alpha and run: 

    mvn -e clean package

Maven reports error as follows:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project java-extensions: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    ..................
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1219)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:188)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    ......................

```

I can't  figure out anything wrong in pom.xml. Am I missing something?

**Comment by rsmckinney** [comment]
The java-extensions project works, but you have to make some changes in the pom:
* You must use the [lombok edge](https://projectlombok.org/download-edge) release, it has at least one bug fix dealing with in-memory files that is required to work with manifold 
* You also must use Manifold version 0.41-alpha or later
* If you are using Java 11, use Maven 3.8.x
* If you use Maven 3.8.x, you should also change `<path>` to `<processorPath>` inside `<annotationProcessorPaths>`

**Comment by rsmckinney** [comment]
regression with release 0.48-alpha
