### ISSUE TITLE
Create interface for access to generated filter Builder classes

### ISSUE THREAD

**Issue by djchapm** [manifold-systems/manifold#293]
**Is your feature request related to a problem? Please describe.**
Have many objects with same field - coding each one is tedious when I need to do something like set the default 'statusCode' to a standard query of int eq 0.  Looking for a leaner way to do bulk query initialization in code.

**Describe the solution you'd like**
Change the generated inner class on objects from "public static class Builder {" to something like "public static class Builder implements **QBuilder**" or some interface name of your choosing.  This way with my 20 builder objects that I'm setting up - instead of calling builderX.setStatusCode(...) on every one I can create a method that accepts a list of **QBuilder** interfaces and call a generic version of the set methods that are generated.  Here's an example of the common set method implementation:
```
public schema.queryObj_filter.Builder withStatusCode(schema.INTEGERQueryArgument $value) {
                ((schema.queryObj_filter)RuntimeMethods.constructProxy(this._result, schema.queryObj_filter.class)).getBindings().put("statusCode", RuntimeMethods.coerceToBindingValue($value));
                return this;
            }
```

new interface method could be something like 
```
@Override
public QBuilder setBinding (String $key, Object $value) {
  ((schema.queryObj_filter)RuntimeMethods.constructProxy(this._result, schema.queryObj_filter.class)).getBindings().put($key, RuntimeMethods.coerceToBindingValue($value));
  return this;
}
```
Generated code for all the set methods then could be changed to:
```
public schema.queryObj_filter.Builder withStatusCode(schema.INTEGERQueryArgument $value) {
                return setBinding("statusCode", $value);
}
```

**Describe alternatives you've considered**
Reflection on client side would be too slow.  only alternative is to have chunky code that sets the same thing on every strongly typed Builder class.

**Additional context**
This will allow me to create code like 
```
void setDefaultCriteria (String fieldName, IBindingsBacked query, QBuilder... filterBuilders) {
    Arrays.stream(filterBuilders).forEach(f -> f.setBinding(fieldName, query));
}
```

**Comment by rsmckinney** [comment]
Hi @djchapm. Not a bad idea, I will definitely consider this.  In the meantime you might try using [structural interfaces](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#structural-interfaces-via-structural) to accomplish this. This way you can define an interface with the common methods you use and use it without it being directly implemented anywhere.

**Comment by djchapm** [comment]
Thanks @rsmckinney for the quick reply - structural interfaces are great and would be a great addition to java itself.  Thanks for pointing me to it!  I'll play with this and update you.

**Comment by djchapm** [comment]
Tried out the Structural interface - one issue I had was for proxying a builder.withXXX method I had a function like:
void setStatus(StructuredBuilder builder, string status) {
   builder.withStatus(status);
}
My StructuredBuilder was like:
void withStatus(String);

I received 'inErrant' runtime exception because the return type in my @Structural was void, so my method match score was 126.  Setting to void should basically ignore I'd think.  So I changed to return Object and that solved the issue.

Anyway - didn't really work out because I'd have to define an interface for all the various 'with' methods in a huge schema.

What I eneded up doing is not using the builder - instead - call .build() on my schema object, cast to IJsonBindingsBacked and call like:
IJsonBindingsBacked builder = schemaObject.builder().build();
builder.getBindings().put("fieldName", RuntimeMethods.coerceToBindingValue(value));

This is nice - but a little ugly.  I found that there's no real safety though - if you set a fieldName that doesn't exist on the schema, there won't be any complaints and sure enough the graphql output will contain whatever you passed in for fields.  Kind of like circumventing the whole framework.  But - this will save us thousands of lines of code.

So - I still think some class heirarchy on builders and allowing access for us to set by fieldName and object value would be nice - to include field name validation.

Let me know if any questions.

**Comment by rsmckinney** [comment]
@djchapm see change 8feb8ece33f233c3828ba9225dbbc0510e6e25b1. Some structural changes were made to reduce the generated code size among them:  `Builder` classes are now interfaces and extend the `GqlBuilder` interface. Hope this helps.

**Comment by djchapm** [comment]
Hey this is great!
Version 2021.1.20: 272,420 bytes for schema.class
Version 2021.1.23: 123,088 bytes for schema.class

Great improvement!

**Comment by djchapm** [comment]
Regarding structural interfaces - I see that the new code requires slight code change on our side... one of the methods we are using to be able to call similar method on multiple builders is:
```
    protected void setPrice (String name, Consumer<schema.LONGQueryArgument> priceConsumer) {
        var price = priceFactory.apply(name);
        if (price != null) {
            priceConsumer.accept(price);
        }
    }
```

Caller side is:
`setPrice("MyMessage", myMessageBuilderInstance::withPrice);`

Error:
`java: Structural interface method 'withPrice' must be invoked as a lambda expression here`

Which was fine before changes - so I guess we have to call like:
`setPrice("MyMessage", price -> myMessageBuilderInstance.withPrice(price));`

instead of a method reference.  Any way to tackle java method refs with your structural interfaces?

**Comment by rsmckinney** [comment]
@djchapm sorry about the inconvenience.  As you've discovered method refs are not supported on structural interfaces, see https://github.com/manifold-systems/manifold/issues/30.  This may be addressed in a future release, but for now lambdas are the workaround.

**Comment by rsmckinney** [comment]
For future reference, IntelliJ has a "quick fix" to automatically convert a method ref to a lambda expression. Handy for this case.

**Comment by djchapm** [comment]
GqlBuilder interface working great for us - thanks!!  This can be closed.
