### ISSUE TITLE
AbstractMethodError using property syntax in an interface default method

### ISSUE THREAD

**Issue by shoaniki** [manifold-systems/manifold#296]
**Describe the bug**
Consider the following trivial code:
```java
public interface Foo {
    int getFoo();  // "@val int foo" behaves identically

    default int succeed() {
        return getFoo();
    }

    default int fail() {
        return foo;
    }
}
```
`succeed` and `fail` should be identical.  However, `fail` actually throws an AbstractMethodError.

Examining the bytecode generated for each suggests that the cause is `fail` using `invokespecial` rather than `invokeinterface` to call `getFoo`.

**To Reproduce**
1. Create the interface above.
2. Implement it.
3. Attempt to call the default methods.

**Expected behavior**
Property syntax should work within default methods.

**Desktop (please complete the following information):**
- OS Type & Version: macOS 11.6
- Java/JDK version: OpenJDK 11.0.9.1
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA Ultimate 2021.2.2
- Manifold version: 2021.1.19
- Manifold IntelliJ plugin version: 2021.2.18

**Comment by rsmckinney** [comment]
Fix available in release 2021.1.20
