### ISSUE TITLE
Expired certificate for https://manifold.systems/

### ISSUE THREAD

**Issue by haisi** [manifold-systems/manifold#320]
**Describe the bug**
The certificate of https://manifold.systems/ has been expired since 04.11.2021.

**To Reproduce**
1. Visit: https://manifold.systems/

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5666773/141976178-a55c63f7-c7fe-4d02-9db7-4e54a9cb0841.png)

**Comment by rsmckinney** [comment]
Hi @haisi. Thanks for reporting, will be remedied soon.

**Comment by rsmckinney** [comment]
Could not remedy the problem with squarespace, reverted to no cert for now.
