### ISSUE TITLE
Intellij Build fails for multi-module maven project

### ISSUE THREAD

**Issue by djchapm** [manifold-systems/manifold#331]
**Describe the bug**
This is a priority for us as it is blocking progress for a Q1 release.
I have moved our graphql schemas to a sub module, so I have:

- parent/
  - pom.xml
  - GraphQlModule
    - pom.xml
  -  MainModule
      - pom.xml (dependency on GraphQlModule)

In the java editor for a class in MainModule, imports and manifold generated classes from 'GraphQlModule' show up fine, and I can Cmd+Click into them etc... however the intellij Build -> Rebuild Project consistently complains that 'package does not exist'.

I've recreated this on both Mac and Windows.

Screenshot of my IDE - here you can see in editor no complaints but at bottom in build status the errors are shown:
![image](https://user-images.githubusercontent.com/9857153/146789408-960c8acb-dad9-4c33-952b-22554c8cd2bb.png)

**To Reproduce**
1. Create multi-module maven project with one submodule depending on another submodule with graphql schemas.
2. Access manifold generated classes in main submodule.
3. Confirm command line maven compile works fine.
4. Observe Build error in intellij.

**Expected behavior**
Intellij doesn't complain.

**Desktop (please complete the following information):**
- OS Type & Version: macOS Big Sur 11.6.1
- Java/JDK version: openjdk 17.0.1
- IDE version (IntelliJ IDEA or Android Studio): Intellij 2021.3 Ultimate Edition
- Manifold version: 2021.1.34
- Manifold IntelliJ plugin version: 2021.3.38

**Additional context**

**Stack trace**
Please include a stack trace if applicable

**Comment by rsmckinney** [comment]
Have you synced maven with IJ using the maven UI?
![image](https://user-images.githubusercontent.com/588843/146796731-454cf2f7-6633-48c4-8d4f-e0caf459e257.png)

**Comment by rsmckinney** [comment]
Additionally, check that your manifold-mrx module's pom.xml has the following compiler arguments:

```xml
    <compilerArgs>
        <arg>-Xplugin:Manifold</arg>
        <arg>-Amanifold.source.graphql=.*</arg>
    </compilerArgs>
```

Note, the second argument instructs the compiler to compile all .graphql files. Normally manifold only compiles resources that are directly referenced from .java files in the module, thus this argument is necessary if that is not the case.

**Comment by djchapm** [comment]
If I remove the java directory from src/main - and provide the argument -Amanifold.source.graphql=.*, the compile puts the graphql files into the resulting jar file but does not generate the java class files....??

If I create the following java class.. it ends up creating all the graphql manifold generated java classes:
![image](https://user-images.githubusercontent.com/9857153/146828207-abe678cc-fff2-4d8e-a7e5-f38f7ad78045.png)

**Comment by djchapm** [comment]
Sort of figured out the original issue... Intellij has the ability to "Load/Unload Modules".  Which effectively allows you to have a project in the project explorer, but 'turned off'.  So any dependencies on that module come from your local maven repo instead of directly from the active module.  I had this unloaded for a while - when I 'loaded' it back to active status - intellij was confused as best I can tell.  So I went to File -> InvalidateCaches... clicked everything and restarted.  When I brought it back up - the module was still loaded and looked the same - but the pom.xml now had a line through it which marks as "Maven -> Ignore".  So then I unignored it.

This was hard to see because it didn't show up as ignored until I refreshed the cache and restarted - so I think intellij was messed up somehow with it's active vs cache representation of the current build.

Providing what I know in case it comes up again... basic solutions are to try combinations of 

- Invalidate Cache
- Refresh Maven
- Load/Unload Module
- Ignore/Unignore Maven
- Restarting IDE

Please let me know on the -Amanifold.source.graphql setting... I'm not able to get manifold to build off those schemas in screenshot above without that class where I import something at a high level in our schemas.  But I'm afraid there will be some graphql components missed w/ this strategy.

Cheers,
  Dan C.

**Comment by rsmckinney** [comment]
The `-Amanifold.source.graphql=.*` compiler argument defined in the manifold-mrx pom.xml file should work for you. However, you do still need a dummy.java file defined in that module, but it does not need to reference any graphql files. Otherwise, without the dummy file the Java compiler won't start a compilation phase, only the resources will be copied.

**Comment by djchapm** [comment]
I see - Thanks!
