### ISSUE TITLE
does manifold support for text blocks (multiline strings) in Java8?

### ISSUE THREAD

**Issue by GG-A** [manifold-systems/manifold#339]
does manifold support for text blocks (multiline strings) in Java8?

**Comment by rsmckinney** [comment]
@GG-A No, text blocks are standard beginning with Java 15. Note, Manifold supports text blocks with [String Templates](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-strings)  and [Fragments](https://github.com/manifold-systems/manifold/tree/master/manifold-core-parent/manifold#embedding-with-fragments-experimental) beginning with Java 13.
