### ISSUE TITLE
Manifold Structural interfaces and Avro Framework

### ISSUE THREAD

**Issue by mehmetsalgar** [manifold-systems/manifold#34]
Hi,

in a project that I am involved at the moment, we are using Apache Avro Framework (specialised on schema based byte serialisation/deserialisation) unfortunately due to nature of this framework, it does not support that schema defined classes inheriting form interfaces.

To solve this problem, I thought Manifold and Structural interfaces could be good solution, so I build something from existing examples but now I getting an exception that I can't do anything about. The question is this a bug or I am using the manifold wrongly... the exception that I am getting is the following.

`[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /org/salgar/avro/DemoAvro.java:[102,7] reference to SpecificRecordBuilderBase is ambiguous
  both constructor SpecificRecordBuilderBase(org.apache.avro.specific.SpecificRecordBuilderBase<T>) in org.apache.avro.specific.SpecificRecordBuilderBase and constructor SpecificRecordBuilderBase(T) in org.apache.avro.specific.SpecificRecordBuilderBase match
[ERROR] /org/salgar/avro/DemoAvro.java:[105,7] reference to SpecificRecordBuilderBase is ambiguous
  both constructor SpecificRecordBuilderBase(org.apache.avro.specific.SpecificRecordBuilderBase<T>) in org.apache.avro.specific.SpecificRecordBuilderBase and constructor SpecificRecordBuilderBase(T) in org.apache.avro.specific.SpecificRecordBuilderBase match
[ERROR] /org/salgar/avro/DemoAvro.java:[108,7] reference to SpecificRecordBuilderBase is ambiguous
  both constructor SpecificRecordBuilderBase(org.apache.avro.specific.SpecificRecordBuilderBase<T>) in org.apache.avro.specific.SpecificRecordBuilderBase and constructor SpecificRecordBuilderBase(T) in org.apache.avro.specific.SpecificRecordBuilderBase match
[INFO] 3 errors `

I produced two maven project to reproduce the problem...one is responsible to create Avro classes 'avro-demo' (must run first
[manifold_avro_demo.zip](https://github.com/manifold-systems/manifold/files/2764438/manifold_avro_demo.zip)
) and the other to make Manifold extension and some logic 'manifold-demo' but it crashes during the 'mvn clean install'..

Thx for feedback

**Comment by rsmckinney** [comment]
Hi.  The avro demo you put together exposes a bug with manifold's extension framework. I've identified the problem, it's a simple fix.  I will include the fix in a release by the end of the day.  I'll update this issue when the release is generally available, probably by 8pm PST.

Thanks for reporting this issue!
