### ISSUE TITLE
Allow Jailbreak to work when casting

### ISSUE THREAD

**Issue by uchagani** [manifold-systems/manifold#345]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use `@Jailbreak` when casting objects.

**Describe the solution you'd like**
To be able to use `@Jailbreak` when casting to an object that is not normally accessible.  I'm personally using this when creating extensions for other libraries and then testing to ensure everything is working correctly.

**Describe alternatives you've considered**
N/A

**Comment by rsmckinney** [comment]
Implemented in release 2022.1.7
