### ISSUE TITLE
Can't use manifold with test scope

### ISSUE THREAD

**Issue by uchagani** [manifold-systems/manifold#346]
**Describe the bug**
I'm using manifold's `@Jailbreak` to do some testing.  It is only being used in tests but I can't compile code with the scope set to `test`.  I get the error `package manifold.rt.api does not exist`.  If i change the scope to `compile` it works fine.  I have created a test project here: https://github.com/uchagani/manifold-jailbreak-test

**To Reproduce**
1. clone [project](https://github.com/uchagani/manifold-jailbreak-test)
2. build

**Expected behavior**
Manifold works with scope set to test.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version:  macOS Monterey 
- Java/JDK version: 11
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2021.3.3 (Community Edition)
- Manifold version: 2022.1.7
- Manifold IntelliJ plugin version: 2022.1.7

**Comment by rsmckinney** [comment]
@uchagani Just add the `test` scope to the path in annotationProcessorPaths. Also, since you are using manifold exclusively in tests you can add the no-bootstrap modifier to the manifold compiler argument.
```xml
                    <compilerArgs>
                        <!-- Configure manifold plugin, using no-bootstrap because using manifold only for tests-->
                        <arg>-Xplugin:Manifold no-bootstrap</arg>
                    </compilerArgs>
                    <!-- Add the processor path for the plugin -->
                    <annotationProcessorPaths>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-ext</artifactId>
                            <version>${manifold.version}</version>
                            <!-- using manifold only for tests -->
                            <scope>test</scope>
                        </path>
                    </annotationProcessorPaths>
```

**Comment by uchagani** [comment]
@rsmckinney i added what you recommended.  For some reason it builds fine in intellij but when i run `mvn clean compile` it fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project manifold-jailbreak-test: Unable to parse configuration of mojo org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile for parameter scope: Cannot find 'scope' in class org.apache.maven.plugin.compiler.DependencyCoordinate -> [Help 1]
```

**Comment by rsmckinney** [comment]
Ah, that was too simple ;)  If you want to limit manifold to just testing, you can remove the `test` scope and instead add a `testCompile` goal. But keep the no-bootstrap modifier, otherwise you'll need to include manifold as a production dependency.

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <goals>
                    <goal>testCompile</goal>
                </goals>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <encoding>UTF-8</encoding>
                    <compilerArgs>
                        <!-- Configure manifold plugin -->
                        <arg>-Xplugin:Manifold no-bootstrap</arg>
                    </compilerArgs>
                    <!-- Add the processor path for the plugin -->
                    <annotationProcessorPaths>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-ext</artifactId>
                            <version>${manifold.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
```

**Comment by uchagani** [comment]
@rsmckinney that did the trick.  thank you!
