### ISSUE TITLE
"this" on static extension methods

### ISSUE THREAD

**Issue by joseaio** [manifold-systems/manifold#348]
Already known that static method in Java don't have a "this" context. But this is not true with other OO languages ("this" on class method referenced the called Class).

   I like a static logging method `warn()` declared on `Object`, for use on any class

If "static extension methods" allows an optional (for retrocompatibility) first parameter with the called class, as this one:

```
package <your-project>.extensions.java.lang.Object;

@Extension
public class MyObject {

  private static final String jdk_logger_packages = "jdk.logger.packages";
  protected static final Map<Class, Logger> logs = new HashMap<>();

  static {
    // Ignore logger wrappers, as this, when writes class and method on log traces
    System.setProperty(jdk_logger_packages, MyObject.class.getPackageName());
  }

  private static Logger log(Class clazz) {
    if (!logs.containsKey(clazz)) {
      logs.put(clazz, Logger.getLogger(clazz.getName()));
    }
    return logs.get(clazz);
  }

  @Extension
  protected static void warn(@This Class clazz, String msg) {
    log(clazz).warning(msg);
  }
```

Now, I can write logs, on any class, calling to static method: `warn("message")`

note: this solution centralize logging framework dependency on single class (I don't like imports of logging framework on all classes)

**Comment by joseaio** [comment]
A possible workaround (I don't known if cause a poor performance):

  Please note the use of `StackWalker` on every on `warn` method to determine the caller.

```
public class MyObject {

  private static final **StackWalker walker** = StackWalker.getInstance(RETAIN_CLASS_REFERENCE);
  private static final String jdk_logger_packages = "jdk.logger.packages";
  protected static final Map<Class, Logger> logs = new HashMap<>();

  static {
    System.setProperty(jdk_logger_packages, MyObject.class.getPackageName());
  }

  private static Logger log(Class<?> clazz) {
    if (!logs.containsKey(clazz)) {
      logs.put(clazz, Logger.getLogger(clazz.getName()));
    }
    return logs.get(clazz);
  }

  @Extension
  public static void warn(String msg) {
    log(**walker.getCallerClass()**).warning(msg);
  }
}
```

**Comment by rsmckinney** [comment]
See ["Smart" static methods](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#smart-static-methods-with-thisclass) with `@ThisClass`.  Paired with `@Self` I think you can accomplish what you are looking for with static methods here.

**Comment by joseaio** [comment]
Great example: generic factory with static methods. In the past i have also needed this...
