### ISSUE TITLE
Support AST transformation providers

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#350]
This is a feature request that grew from a [Slack discussion](https://manifold-group.slack.com/archives/C012W174Z7V/p1648835825742829?thread_ts=1648664729.747929&cid=C012W174Z7V) about making a SQL-like API using manifold.

Given a conventional API like this:
```java
Query query = select( Person )
  .where( Name ).is( age )
  .and( Age ).is( age );
```
the idea is to support a where clause expressions that is more readable:
```java
Query query = select( Person )
  .where( Name == name )
  .and( Age == age );
```
To achieve that we would should support a "transformation provider" interface so that the author of the API could implement the code necessary to transform the more readable syntax to back to his conventional API that captures the query information.

Off hand there are a couple of ways to tackle this.  One is to define an annotation. Something like `@Transformer`:
```java
@Transformer(MyWhereTransformer.class)
public Query where(boolean expr) {...}
```
As such manifold delegates AST processing of calls to `where()` to `MyWhereTransformer#transform(whereAST)` for transformation to the original AST.

Another approach is to define a `Transformer` service provider interface (SPI). This way the API author can register a service implementation and have the opportunity to transform method calls as the compiler encounters them. Advantages of this approach include the ability to transform method calls anywhere in a compilation pass and avoiding having to tag methods in the API with annotations.

**Comment by joseaio** [comment]
After re-read your message, I like to do some proposal:  `where( <booblean-condition>)`

This allows this syntax: 

    `where( Name == name  && Age == age )`

And Allows grouping precedence:   

   `where( Name == name  && Age == age || ( Age >= 21 && Surname != surname) )`

note: allow and/or instead of &&/|| can be a convenient syntax-sugar...

   `where( Name == name  && Age == age || ( Age >= 21 && Surname != surname) )`

Please note, that all boolean conditions are Comparable.compareTo() compatibles

**Comment by rsmckinney** [comment]
Absolutely!  That’s where I’m going with this. Combine this feature with binding expressions and you have nearly complete type-safe SQL syntax in Java.

**Comment by joseaio** [comment]
With this Java Query Language (JQL), near to SQL, you can generate SQL/JPQL/HQL/MongoQL/GraphQL... or use to filter a collection/list of java objects in memory...

**Comment by rsmckinney** [comment]
If you’re familiar with LINQ in C#, this feature is generally the same thing.

**Comment by rsmckinney** [comment]
Experimented with adding a special extension for this, but found that the existing `ICompilerComponent` SPI was sufficient and more flexible. Will post a sample query API using this technique.

**Comment by rsmckinney** [comment]
See example project https://github.com/manifold-systems/manifold-simple-query
