### ISSUE TITLE
Annotation not repeatable

### ISSUE THREAD

**Issue by DesertFoxHU** [manifold-systems/manifold#362]
**Describe the bug**
I get 'org.jetbrains.annotations.Nullable is not a repeatable annotation type' when I try to build. 

**To Reproduce**
1. Compile or install the attached project

**Screenshots**

![kép](https://user-images.githubusercontent.com/40893862/168645558-dd901837-94b2-4274-85c5-dfa5dcccb355.png)
![kép](https://user-images.githubusercontent.com/40893862/168645608-13bfb035-ea12-4be9-b546-6105c8d9f23b.png)

**Desktop (please complete the following information):**
- IDE version (IntelliJ IDEA or Android Studio): 2022.1.1
- Manifold version: 2022.1.11
- Manifold IntelliJ plugin version: 

**Additional context**
In the attached file the PlayerExt extension class is extending a Player class (from a Maven dependency), can be this the issue?

**Stack trace**
org.jetbrains.annotations.Nullable is not a repeatable annotation type

[Test.zip](https://github.com/manifold-systems/manifold/files/8702031/Test.zip)

**Comment by rsmckinney** [comment]
Thanks for reporting this and thanks for the zipped project!  Issue is fixed with release 2022.1.13.
