### ISSUE TITLE
Add @Duplicates(Class declaringType, SourceVersion sinceJavaVersion) annotation so that extension method authors can tag known semantically duplicate methods

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#364]
Add `@Duplicates(Class declaringType, SourceVersion sinceJavaRelease)` annotation so that extension method authors can tag known semantically duplicates methods.
```java
@Extension
public class ManifoldStreamCollectionsExt {
  @Duplicates(Stream.class, RELEASE_16)
  public static <T> List<T> toList(@This Stream<T> thiz) {
    return thiz.collect(Collectors.toList());
  }
}
```

**Comment by joseaio** [comment]
This annotation, can be used with isEmpty() on manifold.text.extensions.java.lang.CharSequence.ManCharSequenceExt:

Duplicate extension method. 'isEmpty(java.lang.CharSequence)' from 'manifold.text.extensions.java.lang.CharSequence.ManCharSequenceExt' duplicates a method in the extended class 'java.lang.CharSequence'

**Comment by CC007** [comment]
I see that you're implementing this with the `@Expires` annotation for `Iterable.reversed()`.

Could you also add this to:
-  `Stream.toList()` in `ManifoldStreamCollectionsExt` in manifold-collections (since java 16)
- `CharSequence.isEmpty()` in `ManCharSequenceExt`  manifold-text (since java 15)

**Comment by rsmckinney** [comment]
Marking this issue as fixed with the `@Expires` annotation
