### ISSUE TITLE
Does manifold preprocessor works with Checkstyle

### ISSUE THREAD

**Issue by xxks-kkk** [manifold-systems/manifold#377]
I like the plugin idea but I find when I used it with checkstyle (e.g., `#define`), I got 

```
antlr.TokenStreamRecognitionException: Unexpected character 0x23 in identifier
```

I guess this should be a common issue but I couldn't find the documentation from manifold on how to tweak checkstyle to work with plugin. Can you please provide some pointers?

Thanks!

**Comment by rsmckinney** [comment]
Copied from your question in the [slack channel](https://manifold-group.slack.com/archives/C012UDB4FT7/p1657498946510229):


>Manifold overrides IntelliJ's Java lexer so the preprocessor directives tokenize as standard Java PSI tokens, such as comments for masked out code. So my guess is checkstyle is not using standard IntelliJ APIs, but is instead parsing Java itself using Antlr. 

>

>One thing you can try is ["dumping source"](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-preprocessor#dumping-source).  This way you aim checkstyle at this preprocessed source directory instead of the original one.
