### ISSUE TITLE
Automatically call extension method on initialization

### ISSUE THREAD

**Issue by eye2web** [manifold-systems/manifold#383]
What i'm triying to achieve is creating branded types. What I want to do is the following:

`
VerifiedEmail email = "hello@hello.com";
`
And call a Extended method on VerifiedEmail initialization.

**Comment by eye2web** [comment]
@rsmckinney Hi rsmckinney.

What I want to achieve is the following. I want to see if it is possible to use branded types in Java using Manifold. More information of Branded types (in this case in Typescript) here: https://medium.com/@KevinBGreene/surviving-the-typescript-ecosystem-branding-and-type-tagging-6cf6e516523d
But it is also common in several Functional languages.

The main idea is to validate and type primitives.

I know that this is possible in Manifold. 
`VerifiedEmail email = "hello@hello.com".VerifyEmail();`
But if i implement it this way. The following is still allowed.
`VerifiedEmail email = "Notvalid";`
I want to make sure that if the String is of type VerifiedEmail (interface). It is already validated. So that interface VerifiedEmail (String) cannot be anything else then a validated email adres. Which is a String.

In my view this can be solved in two ways.
1: Using `VerifiedEmail email = "hello@hello.com".VerifyEmail();` But making sure that VerifiedEmail cannot be set with a String directly.

2: Using `VerifiedEmail email = "hello@hello.com";` And under the hood configure a method or constructor that is called when (casting) the String to VerifiedEmail.

My preference would be option 2.

Hope this is a bit more clear. Please reach out if you have any questions.

Thanks :)

**Comment by rsmckinney** [comment]
@eye2web thanks for the clarification. I didn't know about _Branded_ types, interesting. It feels more like it's solving an issue with typescript's type system. At the same time it could make sense as a more general language feature to naturally coerce a string or primitive value to a more strictly typed one.

The conventional Java way is to simply create a constructor on VerifiedEmail:
```java
public VerifiedEmail(String address) {
  validate(address);
  this.address = address;
}
```
And then use this directly.
```java
VerifiedEmail email =  new VerifiedEmail("hello@hello.com");
```

But I'm assuming you don't like the verbose nature constructors here, right?  I can understand that.  So, perhaps another way to achieve the "Branded" syntax is to more straightforwardly support coercion for this particular use-case.

For instance, a class constructor having a single parameter and marked with a manifold-provided annotation, say `@Coercer`, supports automatic coercion from values of the parameter type to the class type.
```java
@Coercer
public VerifiedEmail(String address) {
  validate(address);
  this.address = address;
}

VerifiedEmail email =  "hello@hello.com"; // manifold calls the constructor here

// coercion works here too
foo("hello@hello.com");
. . .
public void foo(VerifiedEmail email) {. . .}
```

If you don't own VerifiedEmail, you can still add the @Coercer annotation using manifold extension classes. The Coercer annotation could also include optional parameters for a method to be called following the constructor call.
```java
@Coercer("com.example.MyClass","myMethod")
```

Personally, I'm not a big fan of coercion. So maybe a less crafty approach is to simply provide an abbreviated constructor call syntax.
```java
VerifiedEmail email = new ("hello@hello.com");
```

These are just idea off the top of my head.

**Comment by eye2web** [comment]
@rsmckinney Thanks for your response. 

Indeed A Coercer annotation could be the answer to this.

For me the main goal would be as follows.
Example Option 1:
`
VerifiedEmail email = "hello@hello.com".VerifyEmail();
VerifiedEmail email = "hello@hello.com"; // Should not compile since it is not verified
VerifiedEmail email = "Notvalid".VerifyEmail(); // Throws (runtime) exception since it isn't a valid email
`
But still I would like VerifiedEmail to act as a String.

Example Option 2:
`
VerifiedEmail email = "hello@hello.com"; // Call a Coercer method / constructor.
VerifiedEmail email = "Notvalid"; // Throws (runtime) exception since it isn't a valid email
`

Bonus example :
`
Email email = "hello@hello.com";  // Call a Coercer method / constructor. Regex check on email.
VerifiedEmail verifiedEmail = email; // Call a Coercer method / constructor. to Check if the email adres is already verified.
`

Personally I think that option 2 is easier to implement. Not sure how we would handle VerifiedEmail as a String but not accept setting the String directly.

**Comment by rsmckinney** [comment]
There is perhaps an even better approach that manifold already supports using [Binding Expressions](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#unit-expressions).

You could, for example, define email qualifier constants such as `em` and `vem`.
```java
import static com.example.email.EmailVerifier.*;

Email email = em "hello@hello.com";
VerifiedEmail verifiedEmail = vem email;
```
Where:
```java
public class EmailVerifier {
  public static final EmailRegex em = new EmailRegex();
  public static final EmailVerifier vem = new EmailVerifier();

  public VerifiedEmail prefixBind(String address) {
    return verify(address);
  }
  public VerifiedEmail prefixBind(Email email) {
    return verify(email.getAddress());
  }

  private VerifiedEmail verify(String address) {...}

  public class EmailRegex {
    public Email prefixBind(String address) {
      return match(address);
    }

    private Email match(String address) {...}  
  } 
}
```
Of course, you could forgo binding expressions and just use static methods instead:
```java
import static com.example.email.EmailVerifier.*;

Email email = em("hello@hello.com");
VerifiedEmail verifiedEmail = vem(email);
```
Where you replace `em` and `vem` with static methods.

In my view the qualifier constants look nicer, but static methods are simpler to implement and perhaps less confusing to the uninitiated.

**Comment by rsmckinney** [comment]
Since there are reasonable workarounds and since coercion between non-primitive types  is generally a bad idea, I’ve decided against going forward with this proposal. Please let me know if you have questions. Thanks for the discussion!
