### ISSUE TITLE
Cannot use extension from maven dependency in Java 8

### ISSUE THREAD

**Issue by BorkenTech** [manifold-systems/manifold#384]
**Describe the bug**
When trying to use extensions from a maven dependency, error is reported of 'cannot find symbol'. This seems similar to the issue found in https://github.com/manifold-systems/manifold/issues/245.

I have created a minimal repro at https://github.com/BorkenTech/ExtensionFail

The following appears when I attempt to run the test found in the Test project.

...\TestExtensions\Test\src\test\java\ExtensionTest.java:12:30
java: cannot find symbol
  symbol:   method sayHello()
  location: variable input of type java.lang.String

From what I understand of how things should work, in this particular setup, only the Extension project should need the manifold extensions reference. I first attempted with the -ext but due to the similarity with issue 245, I tried manifold-all instead but not even that worked properly.

**To Reproduce**
1. Get mentioned project code
2. Build it
3. Run Test in the Test project

**Expected behavior**
I'd expect the call from the test project to succeed, showing that the extension method is being called from a project that has just a dependency on the class that actually furnishes the extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/7655006/189610315-3f33cdf4-51bf-42a7-9789-fea55672cd7d.png)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 7 (because I'm stubborn)
- Java/JDK version: Java 8 / Open-J9-1.8
- IDE version (IntelliJ IDEA or Android Studio): 2022.1.3 CE
- Manifold version: 2022.1.19
- Manifold IntelliJ plugin version: 2022.1.21

**Additional context**
Can't think of any at the moment

**Stack trace**
N/A

**Comment by rsmckinney** [comment]
Hi @BorkenTech.

Couple of things.  First, I have you project working with a minor config change to one of your pom files, patch included below. The core problem deals with bundling parts of manifold from manifold-all using the shade tool. More generally, the manifold-all dependency is deprecated in favor of using manifold statically and using dependencies selectively.  Please follow the Setup sections from the manifold readme files, they detail how to use each of the manifold dependencies. You can see the difference from the patch below.

You can copy this patch and apply it from the clipboard in intellij:
```
Index: TestExtensions/Extension/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/TestExtensions/Extension/pom.xml b/TestExtensions/Extension/pom.xml
--- a/TestExtensions/Extension/pom.xml	(revision 48cb9c164567ee4266fc35d6f69ccdb5cb291407)
+++ b/TestExtensions/Extension/pom.xml	(date 1662999287630)
@@ -18,7 +18,7 @@
     <dependencies>
         <dependency>
             <groupId>systems.manifold</groupId>
-            <artifactId>manifold-all</artifactId>
+            <artifactId>manifold-ext-rt</artifactId>
             <version>${manifold.version}</version>
         </dependency>
         <dependency>
@@ -40,35 +40,35 @@
 
     <build>
         <plugins>
-            <plugin>
-                <groupId>org.apache.maven.plugins</groupId>
-                <artifactId>maven-shade-plugin</artifactId>
-                <executions>
-                    <execution>
-                        <phase>package</phase>
-                        <goals>
-                            <goal>shade</goal>
-                        </goals>
-                    </execution>
-                </executions>
-                <configuration>
-                    <minimizeJar>false</minimizeJar>
-                    <filters>
-                        <filter>
-                            <artifact>huh.stuff:Function</artifact>
-                            <includes>
-                                <include>huh/stuff/**</include>
-                            </includes>
-                        </filter>
-                    </filters>
-                    <relocations>
-                        <relocation>
-                            <pattern>huh.stuff</pattern>
-                            <shadedPattern>huh.stuff</shadedPattern>
-                        </relocation>
-                    </relocations>
-                </configuration>
-            </plugin>
+<!--            <plugin>-->
+<!--                <groupId>org.apache.maven.plugins</groupId>-->
+<!--                <artifactId>maven-shade-plugin</artifactId>-->
+<!--                <executions>-->
+<!--                    <execution>-->
+<!--                        <phase>package</phase>-->
+<!--                        <goals>-->
+<!--                            <goal>shade</goal>-->
+<!--                        </goals>-->
+<!--                    </execution>-->
+<!--                </executions>-->
+<!--                <configuration>-->
+<!--                    <minimizeJar>false</minimizeJar>-->
+<!--                    <filters>-->
+<!--                        <filter>-->
+<!--                            <artifact>huh.stuff:Function</artifact>-->
+<!--                            <includes>-->
+<!--                                <include>huh/stuff/**</include>-->
+<!--                            </includes>-->
+<!--                        </filter>-->
+<!--                    </filters>-->
+<!--                    <relocations>-->
+<!--                        <relocation>-->
+<!--                            <pattern>huh.stuff</pattern>-->
+<!--                            <shadedPattern>huh.stuff</shadedPattern>-->
+<!--                        </relocation>-->
+<!--                    </relocations>-->
+<!--                </configuration>-->
+<!--            </plugin>-->
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-compiler-plugin</artifactId>
@@ -83,7 +83,7 @@
                     <annotationProcessorPaths>
                         <path>
                             <groupId>systems.manifold</groupId>
-                            <artifactId>manifold-all</artifactId>
+                            <artifactId>manifold-ext</artifactId>
                             <version>${manifold.version}</version>
                         </path>
                     </annotationProcessorPaths>
```

**Comment by BorkenTech** [comment]
I have applied the changes via the _Git_ -> _Patch_ -> _Apply Patch From Clipboard..._ (nice feature! I didn't know about this) and the pom file now has the shade plugin commented out, the dependency referencing -ext-rt, and the plugin using -ext. This is now as I had originally (before I tried -all which was mentioned in issue 245) though without the Shade plugin included. The errors still come up with a "build failed" with the errors continuing.

![image](https://user-images.githubusercontent.com/7655006/189822230-a4da45ff-6ad4-46a9-aef3-8c378e77425b.png)

I have tried reloading the projects (Maven -> Reload project), Build Project, Building the individual modules, Building the individual modules with reloading the projects in-between, reloading from disk, and closing and reopening IDEA. For whatever the reason, it still shows the same errors.

I have uploaded the changes to the project if you wish to compare.

Given that the suggested change is to remove the shade plugin, I removed that from the dependencies but it didn't make a difference.

If you don't mind me asking, what system are you testing this on?

**Comment by rsmckinney** [comment]
Ah, my bad. I only ran `mvn clean compile` after my changes, which ignores the test code you have. There's one more config change to make, attached, same drill. Because compiler settings are not inherited, your Test project must provide the manifold plugin argument and the manifold-ext processor path.

```
Index: TestExtensions/Test/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/TestExtensions/Test/pom.xml b/TestExtensions/Test/pom.xml
--- a/TestExtensions/Test/pom.xml	(revision 6d94454788c7982cd599b35948e62f02113cfbdc)
+++ b/TestExtensions/Test/pom.xml	(date 1663086137482)
@@ -11,6 +11,7 @@
     <properties>
         <maven.compiler.source>8</maven.compiler.source>
         <maven.compiler.target>8</maven.compiler.target>
+        <manifold.version>2022.1.19</manifold.version>
         <junit.jupiter.version>5.8.2</junit.jupiter.version>
         <junit.platform.version>1.9.0</junit.platform.version>
         <jacoco.version>0.8.2</jacoco.version>
@@ -55,8 +56,18 @@
                 <version>3.8.0</version>
                 <configuration>
                     <encoding>UTF-8</encoding>
+                    <compilerArgs>
+                        <!-- Configure manifold plugin-->
+                        <arg>-Xplugin:Manifold</arg>
+                    </compilerArgs>
+
                     <!-- Add the processor path for the plugin -->
                     <annotationProcessorPaths>
+                        <path>
+                            <groupId>systems.manifold</groupId>
+                            <artifactId>manifold-ext</artifactId>
+                            <version>${manifold.version}</version>
+                        </path>
                         <path>
                             <groupId>org.openjdk.jmh</groupId>
                             <artifactId>jmh-generator-annprocess</artifactId>
```

**Comment by BorkenTech** [comment]
Thanks for the quick responses. Though I have more experience with Java, I had a stint of working in C# and got a little spoiled. Finding Manifold made me reevaluate how Java could be used. I believe this could really be a great boon to my future hobby projects. Now it's just a matter to figure out how it can be used and what I need to keep in mind when doing so.

In the original post:
"
From what I understand of how things should work, in this particular setup, only the Extension project should need the manifold extensions reference.
"

So, may I understand that my original thinking was wrong and that for extensions to work, both the module with the extension and the module trying to utilize that extension need to have the manifold-ext?

Part of the goal of this exercise is to understand how transient manifold is to the dependency chain (hence why the test is in the Test module separated from the actual code). The idea was to test if I made an UberJar via the Shade plugin to the manifold'ed JAR with extensions, if that output could still be treated as a single JAR without requiring additional work by the recipient for it to work.

The question appeared after I read this portion of the documentation:
"
You can create your own custom extension libraries. There's nothing special about a "library", it's just a normal dependency in a project. However for manifold to recognize extensions, as a performance measure, the library must declare it has extensions to process. Do that using the Contains-Sources manifest entry.
"

I see that when I export the JAR from IDEA for a different project that I'm using Manifold, the extensions reference brings in several namespace clusters -
    com.google: common, inject
    javax: annotation, decorator, enterprise, inject
    org: aopalliance, apache, codehaus, eclipse, iq80.snappy, objectweb.asm, sonatype, tukaani.xz
and manifold ext.rt, rt.api, and util.

It would make sense if in order to consume the extensions all of those libraries need to be available to the utilizing codebase. Is that the case that all of those are necessary? Or is there some dead code elimination feature I'm not properly utilizing in my setup?

Thanks again for the responses!

**Comment by rsmckinney** [comment]
I'll attempt to paraphrase your question.

Q. Does a project using extension methods defined in a dependency need to use the manifold compiler plugin?

A. Yes. Although the dependency transfers the manifold-ext-rt dependency, a small collection of utility classes and runtime annotations, the project still needs to compile with manifold. The -Xplugin:Manifold compiler argument and manifold-ext processor path are still required so manifold can translate logical calls to extension methods as direct calls to static methods defined in extension classes. Note, this requirement only affects the project's compile-time space -- manifold-ext is not present in the project's runtime.

**Comment by rsmckinney** [comment]
Regarding your other question about dead code, manifold only brings in the manifold packages you listed. The others are included because your Extension project declares dependencies on maven-jar-plugin and maven-shade-plugin, neither are required in order to use those plugins. If you remove those dependencies, your shaded jar will be tiny.

**Comment by BorkenTech** [comment]
I spent some time mulling over your words and messing with the test project. Maybe I'm just too dense in the cranial bone mass but I wasn't able to UberJar the code in a functional way. I went ahead and just checked in my test project as it currently stands - which I feel is creating the same problem in a different manner.

Original:
Function -> Extension -> Test

New:
Function -> Extension -> Test
                          |
                         +-------> UberJar -> UberJarTest

Thanks again for sharing your expertise! I am really enjoying the capabilities of the framework though I'm fighting the actual integration of it.

**Comment by rsmckinney** [comment]
Ah. I think I see where you would have some trouble with an uber jar. If used statically, the manifold-ext and manifold components must be used exclusively as processor paths; it must not be used as a runtime dependency. The util and rt components are for both compile-time and runtime. So, you could exclude manifold-ext and manifold components from the uber jar, but then what would be the point if the idea is to provide a completely self-contained jar?  Perhaps you could create two uber jars: one for compile-time and one for runtime?

Typically, transitive dependencies accomplish what you want without having to create uber jars. Maven (and gradle) automatically include all the dependencies needed. Or is there some other aspect of uber jars you require?

**Comment by rsmckinney** [comment]
Closing this issue as resolved, please reopen if you have more questions, thanks.
