### ISSUE TITLE
Allow extension methods as property access

### ISSUE THREAD

**Issue by DAmNRelentless** [manifold-systems/manifold#400]
**Is your feature request related to a problem? Please describe.**
When using extensions to add a setter to a class that already has a getter, the setter can't be used with property access because it will complain that the property is read-only as it doesn't detect the extension method as prop.

**Describe the solution you'd like**
Extension methods should be accessible via properties.

**Describe alternatives you've considered**
Call the extension method instead.

**Comment by rsmckinney** [comment]
@DAmNRelentless Note, this is a limitation of the IntelliJ plugin. Your code will compile fine. Working on a fix for the intellij plugin. Thanks for reporting this.

**Comment by rsmckinney** [comment]
Fixed and documented in release 2022.1.32
