### ISSUE TITLE
Template strings don't count towards usages

### ISSUE THREAD

**Issue by DAmNRelentless** [manifold-systems/manifold#401]
**Describe the bug**
A template string doesn't count towards the usage of a variable when used inside of it.

**To Reproduce**
1. Create a class with some string constants
2. Use the constants from the class in string templates

**Expected behavior**
It should count towards the usage of the constants.
The problematic thing here is that if you have an IDE setting like "Optimize imports", it will get rid of constant imports although it's used in the template string because it can't find any usages for it.

**Desktop (please complete the following information):**
- OS Type & Version: Windows 11 Pro
- Java/JDK version: JetBrains Java Runtime 17.0.4
- IDE version (IntelliJ IDEA or Android Studio): IDEA 2022.2.3
- Manifold version: 2022.1.27
- Manifold IntelliJ plugin version: 2022.2-1.5.21

**Comment by BluCobalt** [comment]
Works backwards, too; trying to go to the definition of a template string acts like you're just clicking on normal (albeit with different syntax highlighting) text.

**Comment by rsmckinney** [comment]
@BluCobalt can you explain further?  Are you referring to Ctrl+Click (go to definition)?  That should work for you. Please provide an example if not. Thanks!

**Comment by rsmckinney** [comment]
@BluCobalt Tests okay for both local and class references. Please log a separate issue for this detailing your particular use-case. Thanks!

**Comment by rsmckinney** [comment]
I've just tested this and cannot reproduce. All tests having references to fields and locals from string templates work both ways. Find usages works and navigation also works to and from references.

@DAmNRelentless Is there is specific use-case you are having trouble with?  Thanks.

**Comment by rsmckinney** [comment]
@DAmNRelentless it may be that this was fixed as a side-effect of some recent changes. Please test with latest plugin release. Thanks.

**Comment by DAmNRelentless** [comment]
Will do after Christmas. Thanks.
