### ISSUE TITLE
Class cannot be converted Issue

### ISSUE THREAD

**Issue by NextdoorPsycho** [manifold-systems/manifold#417]
**Describe the bug**
So Forgive me in my ignorance as for what this might be as I could totally be doing something wrong. But I was updating from an older manifold version (using the IntelliJ plugin, and it in my Gradle as per the setup guide.)

So I'm coming from `2022.1.21` to now the latest `2022.1.33`.
and I'm no longer able to compile my project.

Here's the Gradle I'm using
https://github.com/VolmitSoftware/Adapt/blob/main/build.gradle
and on my local im just changing the local manifold version up `def manifoldVersion = '2022.1.33'`

**To Reproduce**
1. Clone the Adapt Repo (if you want)
2. Run the Task adapt/setup, go get a coffee, its restitching a whole bunch of repos into a jar (its a pain in the ass) 
3. get a coffee this will take a minute or so
4. Run Task adapt/adapt
5. Observe failure to compile or success depending on version.

**Expected behavior**
It should be able to compile unless something integral was changed that i now need to change

**Screenshots**
![image](https://user-images.githubusercontent.com/29320316/212557455-81f52da6-7d25-40c4-8920-96a0c5617a58.png)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 11
- Java/JDK version: JDK 17 Temurin
- IDE version (IntelliJ IDEA or Android Studio): Intelij 2022.3.1
- Manifold version: `'2022.1.21'` --> `'2022.1.33'`
- Manifold IntelliJ plugin version:  2022.3.34

**Stack trace**
Please include a stack trace if applicable
https://pastebin.com/syz5HLnC

Lastly, Sorry if this seems ignorant, fairly new to Manifold but I'm loving its capabilities and this is a hitch I'm having Thank you again :)

**Comment by rsmckinney** [comment]
Not sure how that compiled in the earlier version, lots of changes between 21 & 33. In any case the error is correct, Class != Class[]. Any reason why you cast it like that?

**Comment by NextdoorPsycho** [comment]
here's an example of where I'm using Class<?>[] 
https://gist.github.com/9cf66a9d1ec3079ec8a883ceb514a650

**Comment by NextdoorPsycho** [comment]
There is no place in my project where I intend to do this, Yet I'm still getting this on 35, as opposed to 21. I can probably go up bit by bit and see where it borked, but that's up in the air

**Comment by rsmckinney** [comment]
Gotcha. I'm getting an error running the adapt task:

Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find org.bukkit:craftbukkit:1.19.3-R0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/scott/.m2/repository/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/scott/.m2/repository/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/craftbukkit-1.19.3-R0.1-SNAPSHOT.pom
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/maven-metadata.xml
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/craftbukkit-1.19.3-R0.1-SNAPSHOT.pom
       - https://arcanearts.jfrog.io/artifactory/archives/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/maven-metadata.xml
       - https://arcanearts.jfrog.io/artifactory/archives/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/craftbukkit-1.19.3-R0.1-SNAPSHOT.pom
       - https://repo.extendedclip.com/content/repositories/placeholderapi/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.extendedclip.com/content/repositories/placeholderapi/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/craftbukkit-1.19.3-R0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/craftbukkit-1.19.3-R0.1-SNAPSHOT.pom
       - https://jitpack.io/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/org/bukkit/craftbukkit/1.19.3-R0.1-SNAPSHOT/craftbukkit-1.19.3-R0.1-SNAPSHOT.pom
     Required by:
         project :

**Comment by NextdoorPsycho** [comment]
It's annoying you need to run setup first

**Comment by rsmckinney** [comment]
Fixed with release 2022.1.36.  Thanks for reporting this

**Comment by NextdoorPsycho** [comment]
I love you platonically with deep gratitude

**Comment by rsmckinney** [comment]
👍🏻lol
