### ISSUE TITLE
Include use cases / case studies

### ISSUE THREAD

**Issue by ORESoftware** [manifold-systems/manifold#43]
I think it would be a great addition to the documentation to include user stories or case studies. Like:

"Ben wanted to create a library for Java, but he was afraid other people couldn't use it because of nominative typing limitations, so he decided to use `@structural` annotations from the manifold Java library".

In my case, yes, I am creating a Java library - but I want to make it easy for my users to incorporate the library into their existing code, and structural typing makes that a lot easier as far as I can tell.

**Comment by rsmckinney** [comment]
I like the idea, it goes along with persona-based marketing themes, which apparently work pretty well.  Thanks!

**Comment by ORESoftware** [comment]
Yes I think the "case study" approach helps people, will help with traction. Maybe 3 or 4 "testimonials" or use cases, for each feature of the library.

Another tangent - maybe in the future break the library apart? It seems like the structural-typing `@structural` annotation is quite different than the `@Jailbreak` annotation  or what not.

For you own sanity, you can put all the libraries in one git repo, so it's easier to manage, but they would just be different .jar files.

**Comment by rsmckinney** [comment]
RE: break the library apart.  The architecture is already designed this way, you can use specific parts of Manifold as illustrated in the Maven/Gradle part of the [Setup docs](http://manifold.systems/docs.html#maven). You can see this reflected in the [repo](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent).  But I should probably make this more apparent somehow...

**Comment by rsmckinney** [comment]
Before I forget, please let me know if you have more suggestions regarding breaking the library up, or rather making this more apparent.  Thanks again!

**Comment by ORESoftware** [comment]
Yeah once I use the library, will give you more feedback, I especially interested in the `@Structural` features.

**Comment by rsmckinney** [comment]
Hi @ORESoftware.  Just touching base for feedback with structural typing, if you have any.  Good or bad, both are valuable.  Thanks!

**Comment by ORESoftware** [comment]
will use this eventually for sure, still working on a library that might need this, but havent got there yet. is there an explanation of how each feature is implemented in this library? maybe write a medium.com article on this lib and link to that article in the readme of the project. if you write a medium article might get more adopters and convince people to use it.
