### ISSUE TITLE
IllegalAccessError JavaParser GraphQL

### ISSUE THREAD

**Issue by ZeyoYT** [manifold-systems/manifold#437]
hi i have been trying to solve this error for a long time now and cannot get my head around on how to fix this, the program works fine when i run it in my pc in intellij but when i use shadow and send it to my vps and try to run there it shows me this error

```
java.lang.IllegalAccessError: class manifold.internal.javac.JavaParser (in unnamed module @0x1a814726) cannot access class com.sun.tools.javac.api.JavacTool (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x1a814726
```

here are my gradle imports for manifold : -

```
implementation group: 'systems.manifold', name: 'manifold-graphql', version: '2023.1.5'
annotationProcessor 'systems.manifold:manifold-graphql:2023.1.5'
implementation 'systems.manifold:manifold-props-rt:2023.1.5'
annotationProcessor 'systems.manifold:manifold-props:2023.1.5'
```

my java version : -

My Pc (in Intellij) : openjdk-19 Oracle OpenJDK 19.0.2
My Vps (cli ubuntu) : java 20 2023-03-21 and javac 20

**Comment by rsmckinney** [comment]
Change `manifold-graphql` to `manifold-graphql-rt`:
`implementation group: 'systems.manifold', name: 'manifold-graphql-rt', version: '2023.1.5'`

**Comment by ZeyoYT** [comment]
> Change `manifold-graphql` to `manifold-graphql-rt`: `implementation group: 'systems.manifold', name: 'manifold-graphql-rt', version: '2023.1.5'`

HI, it fixed the error i had, can you please go in details about what was the issue and what is graphql-rt and how its different to the graphql library i was using

**Comment by rsmckinney** [comment]
Many manifold libraries are split into two modules, one for compile-time and and one runtime with naming convention `manifold-xxx` and `manifold-xxx-rt`.

`manifold-xxx` is typically used as a compiler plugin and is the meat of the library. It performs the main body of work such projecting types corresponding with GraphQL files, or enhancing the compiler to provide operator overloading. Normally, this module applies exclusively to compile-time in the annotation processor path.

`manifold-xxx-rt` is the part of the library that is needed for runtime and is lighter weight. Usually it defines public API interfaces and may contain runtime utilities.
