### ISSUE TITLE
Cannot invoke "manifold.rt.api.util.Pair.getFirst()" because "classSymbol" is null

### ISSUE THREAD

**Issue by skHollywood** [manifold-systems/manifold#447]
**Describe the bug**
I am using manifold version 2023.1.3, when trying to connect to graphql server, getting below error 

Cannot invoke "manifold.rt.api.util.Pair.getFirst()" because "classSymbol" is null

**To Reproduce**
1. Try to connect to graphql server using version 2023.1.3,.
2.
3.

**Expected behavior**
No error should is thrown. 

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version:  Kubernetes Linux
- Java/JDK version: 17 
- IDE version (IntelliJ IDEA or Android Studio):
- Manifold version: 2023.1.3
- Manifold IntelliJ plugin version: 

**Additional context**

**Stack trace**
Please include a stack trace if applicable
\Error message : [Exception occured while processing input message.] and root cause : [java.lang.NullPointerException: Cannot invoke "manifold.rt.api.util.Pair.getFirst()" because "classSymbol" is null
    at manifold.ext.DynamicProxyFactory.hasCallHandlerFromExtension(DynamicProxyFactory.java:117)
    at manifold.ext.DynamicProxyFactory.hasCallHandlerMethod(DynamicProxyFactory.java:102)
    at manifold.ext.DynamicProxyFactory.makeProxyFactory(DynamicProxyFactory.java:52)
    at manifold.ext.rt.RuntimeMethods.createProxy(RuntimeMethods.java:415)
    at manifold.ext.rt.RuntimeMethods.createNewProxy(RuntimeMethods.java:387)
    at manifold.ext.rt.RuntimeMethods.constructProxy(RuntimeMethods.java:63)
    at manifold.json.rt.BindingsCoercer.coerce(BindingsCoercer.java:61)
    at manifold.ext.rt.RuntimeMethods.callCoercionProviders(RuntimeMethods.java:329)
    at manifold.ext.rt.RuntimeMethods.coerce(RuntimeMethods.java:118)
    at manifold.ext.rt.RuntimeMethods.coerceFromBindingsValue(RuntimeMethods.java:77)

**Comment by rsmckinney** [comment]
This could be caused by not configuring dependencies correctly. Can you provide your build configuration files (pom.xml, build.gradle, etc.)?

**Comment by skHollywood** [comment]
Here is snapshot of libs 

<manifold.version>2023.1.3</manifold.version>

*********Dependencies***************


<dependency>
    <groupId>systems.manifold</groupId>
    <artifactId>manifold-graphql</artifactId>
    <version>${manifold.version}</version>
</dependency>

<dependency>
    <groupId>systems.manifold</groupId>
    <artifactId>manifold-props-rt</artifactId>
    <version>${manifold.version}</version>
</dependency>


<dependency>
    <groupId>systems.manifold</groupId>
    <artifactId>manifold-exceptions</artifactId>
    <version>${manifold.version}</version>
</dependency>


<dependency>
    <groupId>systems.manifold</groupId>
    <artifactId>manifold-collections</artifactId>
    <version>${manifold.version}</version>
</dependency>
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java</artifactId>
    <version>18.3</version>
</dependency>
<dependency>
    <groupId>com.graphql-java</groupId>
    <artifactId>graphql-java-extended-scalars</artifactId>
    <version>20.0</version>
    <scope>compile</scope>
</dependency>

**********Plugins*********************
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.10.1</version>
    <configuration>
        <source>17</source>
        <target>17</target>
        <encoding>UTF-8</encoding>
        <compilerArgs>
            
            <arg>-Xplugin:Manifold</arg>
        </compilerArgs>
        
        <annotationProcessorPaths>
            <path>
                <groupId>systems.manifold</groupId>
                <artifactId>manifold-graphql</artifactId>
                <version>${manifold.version}</version>
            </path>
            <path>
                <groupId>systems.manifold</groupId>
                <artifactId>manifold-exceptions</artifactId>
                <version>${manifold.version}</version>
            </path>
            <path>
                <groupId>systems.manifold</groupId>
                <artifactId>manifold-collections</artifactId>
                <version>${manifold.version}</version>
            </path>
            <path>
                <groupId>systems.manifold</groupId>
                <artifactId>manifold-strings</artifactId>
                <version>${manifold.version}</version>
            </path>
            <path>
                <groupId>systems.manifold</groupId>
                <artifactId>manifold-json</artifactId>
                <version>${manifold.version}</version>
            </path>
            <path>
                <groupId>com.graphql-java</groupId>
                <artifactId>graphql-java-extended-scalars</artifactId>
                <version>16.0.1</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>

**Comment by skHollywood** [comment]
Closing.  removed not required libraries.
