### ISSUE TITLE
Java 16+ instanceof pattern matched variable can't be used in the same condition expression

### ISSUE THREAD

**Issue by raphaelNguyen** [manifold-systems/manifold#450]
**Describe the bug**
In java 16+, an instanceof pattern matched variable (`child` in this example) should be usable in the same conditional expression (`child.childField`). (Please see code snippet below from [sample](https://github.com/Integrated-Application-Development/instanceof/blob/984f5e2ce3a72dfaee82a06e908969d67c6618c9/src/main/java/instance/of/Main.java#L6-L8)).

```
    if (parent instanceof Child child && child.childField) {
      System.out.println(parent.parentField);
    }
```

However, with manifold on, this triggers a compile error.

```
[ERROR] [...]/instanceof/src/main/java/instance/of/Main.java:[6,42] cannot find symbol
  symbol:   variable child
  location: class instance.of.Main
```

**To Reproduce**
To reproduce the behavior, compile code with the described pattern ([sample project](https://github.com/Integrated-Application-Development/instanceof)) with manifold turned on (on by default in sample project).

**Expected behavior**
Code should compile without any compilation error as this is a vanilla java feature.

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: 17
- IDE version (IntelliJ IDEA or Android Studio): n/a
- Manifold version: 2022.1.5
- Manifold IntelliJ plugin version: n/a

**Comment by rsmckinney** [comment]
Manifold supports LTS releases of the JDK. Currently, these are 8, 11, and 17. Manifold also supports the latest release, right now this is 20. 

Have you tried using JDK 17?

**Comment by raphaelNguyen** [comment]
Yes. I am using the 17 LTS

**Comment by rsmckinney** [comment]
You're project is using an old version of manifold (2022.1.5). Pattern matching is supported in newer versions, the latest is 2023.1.10.

**Comment by raphaelNguyen** [comment]
Thank you for your prompt response. I've tried it with the new version and it worked.

I've noticed that these new 2023.x versions are not put on the github releases. Can I ask if new releases will no longer be put on github. I'll adjust my processes accordingly. Thank you again for your time.

**Comment by rsmckinney** [comment]
I need to update the release page. Thanks for reminding me!
