### ISSUE TITLE
Extensions Not Visible in Gradle Sub-projects

### ISSUE THREAD

**Issue by gudenau** [manifold-systems/manifold#459]
**Describe the bug**
When a Gradle project has a sub-project defines an extension other Gradle sub-projects/the root project can not see the extensions.

**To Reproduce**
1. Create a new Gradle project
2. Create a sub-project
3. Make the root project depend on the sub-project
4. Create an extension in the sub project
5. Attempt to use extension in another project
6. javac can't see the extension and can not compile the class that uses the extension

**Expected behavior**
The extensions should be available in all projects that depend on the project that contains the extensions.

**Screenshots**
![image](https://github.com/manifold-systems/manifold/assets/5642329/246a52b8-22d4-4c73-a31e-3a23d2ad4956)
![image](https://github.com/manifold-systems/manifold/assets/5642329/a76f4629-d582-4890-b00c-27a1fd0a6648)
![image](https://github.com/manifold-systems/manifold/assets/5642329/5853e4e4-d9f3-4b70-9011-11ad77b3c1c0)
(Plugin issue for lint problems is at manifold-systems/manifold-ij#16)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: 20
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2023.1.3 (Community Edition)
- Manifold version: 2023.1.10
- Manifold IntelliJ plugin version: 2023.1.10

**Additional context**
[Minimal project to reproduce the issue: ManifoldBug.zip](https://github.com/manifold-systems/manifold/files/11924387/ManifoldBug.zip)

**Stack trace**
```
8:51:51 PM: Executing ':RootTest.main()'...

> Task :sub:compileJava UP-TO-DATE
> Task :sub:processResources NO-SOURCE
> Task :sub:classes UP-TO-DATE
> Task :sub:jar UP-TO-DATE

> Task :compileJava FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0/userguide/command_line_interface.html#sec:command_line_warnings
3 actionable tasks: 1 executed, 2 up-to-date
C:\Users\gudenau\IdeaProjects\ManifoldBug\src\main\java\root\RootTest.java:5: error: cannot find symbol
        new Object().subExtension();
                    ^
  symbol:   method subExtension()
  location: class Object
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
8:51:52 PM: Execution finished ':RootTest.main()'.
```

**Comment by rsmckinney** [comment]
If you want the extensions to be accessible from your jar, you must add the `Contains-Sources` manifest attribute.
```groovy
jar {
 manifest {
   attributes('Contains-Sources':'java,class')
 }
}
```
See the documentation for [Extension Libraries](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-libraries).
