### ISSUE TITLE
Does manifold support properties files in the "default package"?

### ISSUE THREAD

**Issue by cschabl** [manifold-systems/manifold#46]
In my Gradle project I have a properties file `src/main/resources/abc-info.properties`.  Code completion with Intellij doesn't work for this properties file, neither an `import abc_info;`. Moving `abc-info.properties` to a subfolder `abc`, code completion works as documented in the manifold doc.

Is this a known limitation?

**Comment by rsmckinney** [comment]
Hi @cschabl.  Yes, Manifold supports the default package, however there is a Java limitation where a Java class cannot import a type from the default package unless the class is also in the default package.  This is likely what you are seeing.  Basically, if you want to use the default package, all your classes must reside in the default package.
