### ISSUE TITLE
Invalid syntax even after IDE plugin installed

### ISSUE THREAD

**Issue by nagkumar** [manifold-systems/manifold#464]
<img width="721" alt="image" src="https://github.com/manifold-systems/manifold/assets/332234/5320a986-75af-4805-a8a4-e719660e2227">

```
  // manifold-collections dependency
    @SuppressWarnings("unused")
    private static void useRanges()
    {
	out.println("\n\n### Use Ranges with `RangeFun` ###\n");

	// Work with ranges using binder constants from manifold.collections.api.range.RangeFun

	// Easily make ranges on sequential endpoints using 'to'
	for (int i : to 10)
	{
	    out.println(i);
	}

	// Use with lambdas
	(to 10).forEach(out::println);

	// Strong typing
	IntegerRange range = to 10;

	// Reverse the endpoints
	for (int i : 10 to)
	{
	    out.println(i);
	}

	// Use 'step' to define an increment
	for (Rational i : r to 10 r step 2 r)
	{
	    out.println(i);
	}

	// Use variations of 'to' ('_to', '_to_', 'to_') to exclude range endpoints
	for (Rational i : r _to 10 r)
	{
	    out.println(i);
	}

	// Iterate a range of measures with a 'unit'
	for (Mass mass : 5 kg to 6 kg step2.7r unit oz)
	{
	    out.println(mass); // increments of 2.7 oz starting with 5kg
	}

	// Use 'inside' to check for containment on Comparable endpoints
	if ("le matos"inside"a"to"m~")
	{
	    out.println("le matos");
	}
    }
```

IDE shows this as invalid syntax

**Comment by nagkumar** [comment]
<img width="620" alt="image" src="https://github.com/manifold-systems/manifold/assets/332234/ebd6926a-b917-4e49-81c8-22cd3d2b921f">

**Comment by nagkumar** [comment]
Oops.. not sure how this code was manipulated to such wrong form.. will observe it again what steps in IDE with plugin has resulted this code to loose 1 and other errors

https://github.com/manifold-systems/manifold-sample-project/blob/master/src/main/java/abc/RunMe.java

In any case, I still see these errors in this file, when opened in IDE

![image](https://github.com/manifold-systems/manifold/assets/332234/85548136-350a-40aa-9d01-63ff262b5df7)

**Comment by rsmckinney** [comment]
there is an issue in the IDE plugin where ext methods are not recognized/completed. you can workaround that when you see it simply by editing the call site e.g., put a space after the dot and then remove it.  there is a fix for this coming soon
