### ISSUE TITLE
Deprecated class usage results in compilation error in IntelliJ IDEA

### ISSUE THREAD

**Issue by monteragi** [manifold-systems/manifold#466]
**Describe the bug**
Compilatation fails if @Deprecated class is used in the source code.
It fails using Intelliji Idea for build. Maven compiles with no error...
I reproduced it on two different PCs. Tried different JDKs - result is the same.

**To Reproduce**
1. Install IntelliJ IDEA 2023.2 (Community Edition)
2. Checkout and open project: https://github.com/monteragi/manifold-test
3. Select "Build Project" or Run from the IntelliJ IDEA toolbar. 

**Expected behavior**
Project is built / executed sucessfully.

**Actual behavior**
It fails with compilation error:
```
\src\main\java\mytest\MM.java:6:34
java: unexpected type
  required: class
  found:    variable

```
**Screenshots**
I recorded the short video. It shows the problem clearly. Please check
https://www.youtube.com/watch?v=CfGud1mHHBQ

**Desktop (please complete the following information):**
- OS Type & Version:  Windows 10 Pro
- Java/JDK version:  OpenJDK Temurin 17 and others.. Language Level 11
- IDE version (IntelliJ IDEA or Android Studio):  IntelliJ IDEA 2023.2 (Community Edition)
- Manifold version: 2023.1.10
- Manifold IntelliJ plugin version: 2023.1.10

**Additional context**
Project uses: manifold-ext-rt and manifold-ext
Compiliation via Maven works fines.

**Stack trace**
\src\main\java\mytest\MM.java:6:34
java: unexpected type
  required: class
  found:    variable

**Comment by monteragi** [comment]
It's something related to the deprecation warning... If I suppress it by "@SuppressWarnings("deprecation")" then compilation goes fine....

**Comment by rsmckinney** [comment]
@monteragi Thanks for this info, good to know. I think I know the problem, should have a fix ready for a release eod tomorrow.

**Comment by rsmckinney** [comment]
Fixed available with release 2023.1.11

**Comment by monteragi** [comment]
@rsmckinney  Thanks a lot for the fix!

**Comment by monteragi** [comment]
@rsmckinney Thanks a lot for the fix!
