### ISSUE TITLE
Issue in using props

### ISSUE THREAD

**Issue by souravdalal** [manifold-systems/manifold#468]
Hi,
I am using Manifold props in a legacy system in Java 8. In a class file there are multiple classes are defined. While adding Manifold props getting the below error at the compile time.
Manifold @var properties are not supported in sidecar classes, consider nesting the class instead
Is there a way to get rid of the error. I don't want to create nested class also will not apply manifold related fetaure on those classes. Is there a way to ignore this error.

Thanks

**Comment by rsmckinney** [comment]
Hi @souravdalal. A fix for this issue will be available in a new release scheduled for Monday 8/7. Thanks for reporting this!

**Comment by rsmckinney** [comment]
Fix available with release 2023.1.14.  Thanks for reporting this!
