### ISSUE TITLE
`@Jailbreak` fails to compile when used on method that returns `short`

### ISSUE THREAD

**Issue by PlatinPython** [manifold-systems/manifold#470]
**Describe the bug**
When using `@Jailbreak` to access a method (static or instance) that returns a `short` the class fails to compile with "Unable to find method invokeStatic_short" or "Unable to find method invoke_short" respectively.

**To Reproduce**
1. Use `@Jailbreak` on any class that has a method that returns a `short`
2. Call said method
3. Try to compile

**Expected behavior**
The class should compile without errors and the method call should run without problems.

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 Pro 22H2
- Java/JDK version: Adoptium JDK 17.0.5.8
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2023.2
- Manifold version: 2023.1.13
- Manifold IntelliJ plugin version: 2023.1.11

**Additional context**
The cause of that, as far I can tell, seems to be that those two methods (`invoke_short` and `invokeStatic_short`) just do not exist in `ReflectionRuntimeMethods`.

**Stack trace**
[Output from compileJava task](https://gist.github.com/PlatinPython/b5edd41d0ce3000671bdef7e13600e77)

**Comment by rsmckinney** [comment]
Fix available with release 2023.1.14.  Thanks for reporting this!
