### ISSUE TITLE
Velocity is a vector, speed is a scalar

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#475]
**Describe the bug**
The name of the `Velocity` class is incorrect. Since it is implemented like a scalar, the name should be `Speed`. 
Velocity should refer to a vector, eg a speed in a certain direction.

**To Reproduce**
 - Write the expression `100 mph` or `100 km/h`
 - Assign the expression to a variable

**Expected behavior**
The variable should be of type `Speed`, however it is of type `Velocity`

**Desktop (please complete the following information):**
- Java/JDK version: 20
- Manifold version: 2023.1.15

**Additional context**
https://www.physicsclassroom.com/class/1DKin/Lesson-1/Speed-and-Velocity

**Comment by rsmckinney** [comment]
Hi @CC007. Good point! However, the SI unit for velocity is m/s, the directional part is considered “understood.” This is standard nomenclature in physics, which is the context for this library.

If the directional attribute is significant in the calculations, [manifold-science](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-science/README.md) provides vector support. For instance, check out [VelocityVector](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-science/src/main/java/manifold/science/vector/VelocityVector.java).
