### ISSUE TITLE
[Bug] unintended behavior when using both manifold-delegation and manifold-props

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#479]
**Describe the bug**
With manifold-delegation, overridden delegated methods don't work properly when accessed with the field access notation with the use of manifold-props

**To Reproduce**
1. Create an interface `Vehicle` with a `getName()` method
2. Create a class `Car` annotated with `@part` that implements `Vehicle` and overrides the `getName()` method, without a field named `name`, for instance with the literal string `"car"`
3. Create a class `Suv` that implements `Vehicle` and has a `Car` field that is annotated with `@link` and overrides the `getName()` method, without a field named `name`, for instance with the literal string `"SUV"`
4. Create a class with a `main()` method.
5. Inside the main method, create an object named suv of type `Suv`
6. print out the name field of the suv object using `suv.getName()` and then using `suv.name`

**Expected behavior**
I expect both the print of `suv.getName()` and `suv.name` to return `"SUV"`, however while `suv.getName()` indeed does this, `suv.name` returns `"car" instead

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: openjdk-20.0.2
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ 2023.1.5
- Manifold version: 2023.1.18
- Manifold IntelliJ plugin version: 23.1.15

**Additional context**
This example explores the same issue, but is slightly less minimalistic:
https://github.com/CC007/ManifoldDemo/blob/master/src/main/java/com/github/cc007/Demo5.java

**Comment by CC007** [comment]
Correction: when calling `suv.name` from outside the class, It works properly, as if `getName()` was called.

The problem arises when `name` gets used from inside the `Car` class.

**Comment by rsmckinney** [comment]
Fix available with release 2023.1.19. Thanks for reporting this!

**Comment by CC007** [comment]
Fix confirmed
