### ISSUE TITLE
[Bug] compile-time error when having multiple classes in the same file

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#484]
**Describe the bug**
When using multiple classes in one source file (one being public, the rest package-private, like is allowed in Java), I get the following compile-time error:
```
java: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Symbol$VarSymbol.getAnnotation(java.lang.Class)" because "tree.sym" is null
```

**To Reproduce**
Steps to reproduce the behavior: compile code from gist

**Expected behavior**
I expected these classes to compile as if they were package-private classes that were specified in separate files, with all Manifold features working without issue. 

**Screenshots**
![afbeelding](https://github.com/manifold-systems/manifold/assets/5381337/d0409a07-0c0b-4e9f-b4d7-7fa28a539bfd)

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: openjdk-20.0.2
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ 2023.1.5
- Manifold version: 2023.1.18
- Manifold IntelliJ plugin version: 23.1.15

**Additional context**
See gist: https://gist.github.com/CC007/13c6211b20c3c64dfb023415fc98cf2c
The code here uses manifold-props, but I also noticed a `... because "tree.sym" is null` error when using other manifold dependencies.

**Comment by rsmckinney** [comment]
Unfortunately, "piggyback" classes are not supported. This feature of Java is a pet peeve of mine; manifold will probably never support it. Sorry this tidbit is missing from the documentation.

**Comment by CC007** [comment]
I expected as much. Just tried to use it, because java's nested class field access rules are a bit wack and prevented me from demoing how the `Private` and `Protected` parameter for manifold-props annotations work, so I tried to use these. I'll just use a package with multiple source files instead then.

**Comment by rsmckinney** [comment]
> I'll just use a package with multiple source files instead then.

Right. Or, you can use static inner classes, whichever is most suitable. In my view piggyback classes are pointless at best. :/

**Comment by CC007** [comment]
That's what I meant with nested classes above. Field access is unintuitive, considering you can access fields from nested classes both from the parent and from sibling classes.
