### ISSUE TITLE
Can not build with lombok

### ISSUE THREAD

**Issue by sj0102** [manifold-systems/manifold#486]
**Describe the bug**

maven build(install) failed.

**To Reproduce**
0. checkout the project (https://github.com/manifold-systems/manifold.git)
1. add the lombok dependency at pom.xml
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.28</version>
      <scope>provided</scope>
    </dependency>
2. add the lombok at module-info.java
   requires lombok;
3. make a java file using lombok.
import lombok.Getter;
import lombok.Setter;
@Getter
@Setter
public class TestVo {
    private String testId;
}
4. add source code at RunMe.java
    TestVo  vo = new TestVo ();
    vo.setTestId("asdf");
    System.out.println(vo.getTestId());
5. maven install

**Expected behavior**
build and run success

**Screenshots**

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/dev/rpa/manifold-sample-project/src/main/java/abc/RunMe.java:[73,26] cannot find symbol
  symbol:   method getTestId()
  location: variable vo of type abc.stuff.vo.TestVo
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.156 s
[INFO] Finished at: 2023-08-31T14:23:52+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project manifold-sample-project: Compilation failure
[ERROR] /D:/dev/rpa/manifold-sample-project/src/main/java/abc/RunMe.java:[73,26] cannot find symbol
[ERROR]   symbol:   method getTestId()
[ERROR]   location: variable vo of type abc.stuff.vo.TestVo
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 Enterprise 1903
- Java/JDK version: openjdk-17
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ  2022.1 Build #IU-221.5080.210, built on April 12, 2022
- Manifold version: 2023.1.19
- Manifold IntelliJ plugin version: 2022.2.41

**Additional context**

**Stack trace**
Please include a stack trace if applicable

**Comment by rsmckinney** [comment]
Hi @sj0102. 

Since manifold is enabled via `annotationProcessorPaths` all annotation processors must be added there as well.

```xml
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.28</version>
                        </path>
```

**Comment by sj0102** [comment]
Hello @rsmckinney 
Thank you for rapid reply.

I added lombok to annotationProcessorPaths you suggestion, and I found a new error.
I didn't find any similar errors on Google. Have you ever experienced such as this error?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project common: Fatal error compiling: java.lang.NullPointerException: Cannot read field "tsym" because "tree.type" is null

**Comment by rsmckinney** [comment]
I just tested adding lombok to manifold-sample-project. Worked fine for me. Are you using the correct jdk to build the project?

**Comment by sj0102** [comment]
Sorry. It works well for your project.
But I applied it to my project, of course jdk build path is fine (if except both compileArgs and AnnotationProcessorPaths, it works well), it still had issue.
I asked if you had similar experience like this.

Thank you!!!

**Comment by rsmckinney** [comment]
Is your project available on GitHub or similar? I would be happy to help diagnose the problem.

**Comment by CC007** [comment]
Maybe you can try to reproduce it in a more minimal project, like mine? https://github.com/CC007/ManifoldDemo

That one already uses lombok in some places, so it would be interesting to see what triggers the issue.

**Comment by rsmckinney** [comment]
Hi @sj0102. I can't reproduce what you are experiencing. I tried your steps above integrating lombok with the manifold sample app, adding the TestVo class etc. All works fine for me. I did have to reopen the project after making lombok-related build and source changes, but the project does build and execute okay for me. I've also tried different variations on a smaller project.  I did experience some odd compile errors from lombok occasionally, but these were always temporary and cleared up after reapplying the lombok build changes. In the end, I could not make lombok @Getter/@Setter integration with manifold fail.

At this point I need a test project, or at least a build config, that reproduces the error you see. Would be great if you could provide that.  Thanks.
