### ISSUE TITLE
Code Completion on Gradle Projects does not work

### ISSUE THREAD

**Issue by Xedon** [manifold-systems/manifold#49]
Intelij does not show the extension methods.

build.grade
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    // -- All manifold, includes all other dependencies listed here --
    compile group: 'systems.manifold', name: 'manifold-all', version: '0.48-alpha'
    compile files("\${System.getProperty('java.home')}/../lib/tools.jar")
}

tasks.withType(JavaCompile) {
    options.compilerArgs += '-Xplugin:Manifold'
    options.fork = true
}

![image](https://user-images.githubusercontent.com/6977872/54203680-ff62d980-44d2-11e9-81d0-3291f385b8f8.png)

![image](https://user-images.githubusercontent.com/6977872/54203612-dc382a00-44d2-11e9-8658-6ef985acacf7.png)

Whats wrong here?
Normal Projects without gradle works.

**Comment by Xedon** [comment]
If i define a extension Funktion for String, Intelij knows the Funktion after first compilation but the code runs event if the Intelij mark it as error.
I use Gradle 5.2 and my target is JDK 8 with the latest plugin version and jar version

**Comment by rsmckinney** [comment]
Hi @Xedon 

The following `build.gradle` works fine with Manifold extensions (and all other features):
```gradle
plugins {
    id 'java'
}

group 'com.example'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'systems.manifold', name: 'manifold-all', version: '0.48-alpha'
    testCompile group: 'junit', name: 'junit', version: '4.12'

    // tools.jar dependency (for Java 8 only)
    compile files("\${System.getProperty('java.home')}/../lib/tools.jar")
}

tasks.withType(JavaCompile) {
    options.compilerArgs += '-Xplugin:Manifold strings'
    options.fork = true
}
```
Also, because you are using Java 8, be sure to define your `java.home` environment variable.

Let me know if you continue to have trouble.

**Comment by rsmckinney** [comment]
Update:

There is a newly discovered bug introduced in the last version of the IntelliJ plugin where a project is not notified after adding a new extension class, thus extension methods in the new class would not be available unless the project is reloaded.  This is now fixed and awaiting JetBrains approval, which usually takes a day or two.  You can get the update immediately from [here](https://plugins.jetbrains.com/plugin/download?updateId=59362&pluginId=10057&version=0.48-alpha).

**Comment by Xedon** [comment]
The new Plugin Version fixes the Problem.
Thank you for Helping me 👍 
I will show my colleagues this awesome Project on Friday, i am sure they will love it.

**Comment by Xedon** [comment]
Ok i figured out wat´s wrong in my case,
If i add my DB Verndor classes The Manifold Plugin stops to show the extension methods from the manifold-all package.
![image](https://user-images.githubusercontent.com/6977872/54294511-ccdbde00-45b1-11e9-836a-5b8cac6df5c1.png)
![image](https://user-images.githubusercontent.com/6977872/54294576-d9603680-45b1-11e9-93c7-51908e0bc280.png)

Are there problems known on Projects with many External Libraries ?

**Comment by rsmckinney** [comment]
It looks like the recent Self type changes have broken compatibility with lombok, so this may be the same type of error you are seeing.  I am working on a solution.

**Comment by Xedon** [comment]
i am not using lombok.

**Comment by rsmckinney** [comment]
Right.  There is definitely a general problem, however, with any library performing annotation processing, which lombok does.  Do you know if the library you're using has an annotation processor?  Can you provide a sample application on github, or post the library you are using?

**Comment by DPUkyle** [comment]
Just throwing this out there since @Xedon said he's using Gradle 5.

Gradle 5 ignores annotation processors unless they are added to a special configuration, see more [here](https://docs.gradle.org/5.0/userguide/java_plugin.html#sec:java_compile_avoidance).

I doubt it's related to manifold, but maybe good to know for future troubleshooting.

**Comment by Xedon** [comment]
I dont think they provide an annotation processor but to be sure how could i check that?
The libraries that i am using are sadly not public accessible, i will try to provide you with a working sample.

**Comment by rsmckinney** [comment]
Thanks, @DPUkyle, for the info re gradle 5.  Good to know.

Regarding the regression wrt annotation processors, I have identified the problem and have a fix locally.  I'll prepare a new release later today.

**Comment by Xedon** [comment]
I am sure that the library's cause the problem, if i remove them and restart InteliJ the plugin works again and shows the extension methods on string. Interesting is here that i have to restart InteliJ! A grade project refresh ist not enough.
Sadly it is very complex because the library´s are added in an gradle plugin.

**Comment by rsmckinney** [comment]
Looking further into the problem as you've explained it.  Do you see any errors reported from IntelliJ?

**Comment by rsmckinney** [comment]
No luck reproducing the issue.  If it's not too much trouble, a sample application demonstrating the problem would be great.  Or if you can share the libraries privately via [email](mailto:scott@manifold.systems) or dropbox that would work too.

**Comment by Xedon** [comment]
Here is an Dropbox linkt to the project with all dependency included: https://www.dropbox.com/s/6fjl2ta7ql0v8wp/ManifoldDemo-gradle.7z?dl=0

**Comment by rsmckinney** [comment]
@Xedon, thanks for the project link.  The "bad" news is that it works for me.  The Manifold plugin works ok with the extension methods you have:

![image](https://user-images.githubusercontent.com/588843/54376157-b1b7af80-463f-11e9-9dff-5870ea72ea47.png)

Perhaps you have another IJ plugin enabled that somehow interferes?

**Comment by rsmckinney** [comment]
There is one error on my side, however, with the gradle build:
![image](https://user-images.githubusercontent.com/588843/54376818-1a535c00-4641-11e9-9fb3-1d55b18300c0.png)

Not sure if this making a difference.  The "abas" libraries are a bit unusual as well regarding the deployment scheme.

**Comment by Xedon** [comment]
> @Xedon, thanks for the project link. The "bad" news is that it works for me. The Manifold plugin works ok with the extension methods you have:
> 
> ![image](https://user-images.githubusercontent.com/588843/54376157-b1b7af80-463f-11e9-9dff-5870ea72ea47.png)
> 
> Perhaps you have another IJ plugin enabled that somehow interferes?

That works on my side to but if i try to use String extension they don´t show up.
Do they work on your side ?

The missing dependencies are ok.

**Comment by rsmckinney** [comment]
Ah.  Yes, I've reproduced that.  I'll keep you posted.

**Comment by rsmckinney** [comment]
Good news.  Found the issue and have a fix published in a new plugin release.  Note Jetbrains can take a couple days to approve a new release, so if you need it sooner, you can grab it [here](https://plugins.jetbrains.com/plugin/download?updateId=59490&pluginId=10057&version=0.50-alpha) and install the zip file directly from disk via IJ Settings.  Note also the IJ plugin and Manifold framework are on the same release schedule, both are release `0.50-alpha`.  Adjust your build files accordingly.

**Comment by rsmckinney** [comment]
reopen (auto-closed)

**Comment by Xedon** [comment]
Nice it works!
Thank you 🥇
