### ISSUE TITLE
[Inconsistency] Iterable.mapIndexed/mapNotNull/mapIndexedNotNull method name not aligned with other methods

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#492]
**Describe the inconsistency**
The class ManIterableExt contains (among others) the following extension methods:
- `filterToList(predicate)`
- `filterTo(destination, predicate)`
- `filterIndexedToList(indexedPredicate)`
- `filterIndexedTo(destination, indexedPredicate)`

These are nice and consistent, with a `List<T>` or a chosen destination `Collection<? super T>` as a result and still allowing for a `filter` and `filterIndexed` to be implemented, which would return a `Stream<T>`.

If you look at the `map` variants though, I would expect:
- `mapToList(transform)`
- `mapTo(destination, transform)`
- `mapIndexedToList(indexedTransform)`
- `mapIndexedTo(destination, indexedTransform)`

However instead of `mapIndexedToList`, the method is named `mapIndexed`. As a result, it is impossible to create your own extension method that is called `mapIndexed` that would return a stream.

The same is true for `mapNotNull`, which should have been `mapNotNullToList` and `mapIndexedNotNull`, which should have been `mapIndexedNotNullToList`

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: openjdk-20.0.2
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ 2023.1.5
- Manifold version: 2023.1.20
- Manifold IntelliJ plugin version: 23.1.15

**Comment by CC007** [comment]
It would also be nice if the IntelliJ plugin showed these method signature conflict issues before compilation.

**Comment by rsmckinney** [comment]
Yep, I agree with you here regarding the naming, they should have been more specific, or perhaps should have just worked with streams. Renaming these could bother some folks, however. I haven't received much feedback around collection extensions etc., so I'll consider renaming and asking for forgiveness or back out the changes if need be.

**Comment by CC007** [comment]
You could maybe add the correct name as well and mark the old one as @Deprecated(forRemoval = true) and wait for your next major release to actually remove it.
