### ISSUE TITLE
IntelliJ Idea: Cannot resolve symbol 'item1'

### ISSUE THREAD

**Issue by ojecborec** [manifold-systems/manifold#500]
Following code compiles just fine but IntelliJ Idea is reporting 3 problem.

```java
package com.example.demo;

import manifold.ext.rt.api.auto;

public class DemoApplication {

	public static void main(String[] args) {
		var t = tuple();

		System.out.println(t.item1);
		System.out.println(t.item2);
	}

	private static auto tuple() {
		return 1, 2;
	}

}
```

1. Autocomplete is not showing item1 and item2.

![image](https://github.com/manifold-systems/manifold/assets/11238639/f6edb943-e51d-4fa6-866a-43935f2a7912)

2. `return 1, 2` is marked as red.

![image](https://github.com/manifold-systems/manifold/assets/11238639/1b9f0c40-55ad-4dcd-ae29-53adf129abd7)

3. Reported problems.

![image](https://github.com/manifold-systems/manifold/assets/11238639/5c96337c-3ae3-476a-ad99-a5cf408829a4)

IntelliJ Idea Community Edition 2023.2.2
Manifold plugin 2023.2.2

**Comment by ojecborec** [comment]
[demo.zip](https://github.com/manifold-systems/manifold/files/12652048/demo.zip)

**Comment by rsmckinney** [comment]
Are you using the manifold-tuple / manifold-tuple-rt dependency in your build config?

**Comment by rsmckinney** [comment]
Just opened your demo.zip project, all works fine for me:

![image](https://github.com/manifold-systems/manifold/assets/588843/4eb0d767-7479-4c90-93f1-79c027528883)

**Comment by ojecborec** [comment]
Hmm. That must me my local problem. I'm going to close this issue.

**Comment by rsmckinney** [comment]
Let me know if the issue persists, thanks.

**Comment by ojecborec** [comment]
Seems like invalidating cache has helped.
