### ISSUE TITLE
Docs: Properties Files sections: property names not consistent

### ISSUE THREAD

**Issue by kaffeeumeins** [manifold-systems/manifold#51]
In the section http://manifold.systems/docs.html#properties-files the property file example contains the wrong properties. The following will be consistent with the  examples:
```
my.chocolate = Chocolate
my.dark.chocolate = Dark Chocolate
my.milk.chocolate = Milk Chocolate
```

**Comment by rsmckinney** [comment]
Hi @kaffeeumeins.

Thanks for report the issue.  Actually, the file is correct, the expression is wrong. S/b: `my.chocolate.dark` etc.  Corrected now.. Thanks again!
