### ISSUE TITLE
Object copy( @This Object array, int newLength ) method in ManArrayExt call is unusable!

### ISSUE THREAD

**Issue by rwperrott** [manifold-systems/manifold#510]
It's package is `manifold.ext.rt.extensions.manifold.rt.api.Array.ManArrayExt`

It throws ArrayIndexOutOfBoundsException when newLength >=0 and newLength < Array.getLength( array ) 

**To Reproduce**

Object[] array = new Object[10];
array.copy(1)

**Expected behavior**

No ArrayOutOfBoundsException thrown.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS Type & Version: Linux Mint 21.2 MATE 64-bit
- Java/JDK version: 1.8
- IDE version (IntelliJ IDEA or Android Studio):
- Manifold version: 2023.1.27
- Manifold IntelliJ plugin version: 2023.2.4

**Additional context**

This is a ridiculously dumb bug, which should have been spotted by a JUnit test!

It does this because line 89 is
`System.arraycopy( array, 0, dest, 0, length );` !
when it should be:
`System.arraycopy( array, 0, dest, 0, Math.min(length,dest.length) );`

I've noticed that `public static @Self Object copyTo( @This Object array, @Self Object to )` also looks broken, because it doesn't check the `to` length, WTF! Suffice to say, I can't trust this class yet.

**Stack trace**
```java
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at manifold.ext.rt.extensions.manifold.rt.api.Array.ManArrayExt.copy(ManArrayExt.java:89)
	at rwperrott.stringtemplate.v4.MemberInvoker.subArray(MemberInvoker.java:49)
	at rwperrott.stringtemplate.v4.MemberInvoker$ForMethod.invoke(MemberInvoker.java:381)
	at rwperrott.stringtemplate.v4.AbstractInvokeAdaptor$ArgsAdaptor.invoke
...
```

**Comment by rsmckinney** [comment]
Supported with release 2023.1.28
