### ISSUE TITLE
Packaging failed in Maven multi module project

### ISSUE THREAD

**Issue by zcfire2017** [manifold-systems/manifold#523]
In maven multi-module, only the module that writes extension method will not report an error when packaging. Other modules that reference this module and use the extension method will report an error when packaging, and then they can be packaged successfully after regeneration, and the sequence is repeated.
There are three modules: A, B, and C. A references B and B references C. The extension method is defined in C, and then B uses C's extension method. A also uses C's extension method, which can generate and run normally. However, an error will be reported during packaging. Only C can package successfully, and both B and A report an error: the symbol cannot be found, that is, the extension method cannot be found, but after regeneration, another module can be successfully packaged, That is to say, after cleaning up the project, module C can succeed during the first packaging, but modules A and B will fail. Then, generate the project and perform packaging, and module B will succeed, but module A will fail. Why is this?

**Comment by zcfire2017** [comment]
If the project does not write extension methods, then all modules will be generated, run, and packaged without any issues. After writing extension methods and calling them, they can only be generated and run, but packaging will result in an error

**Comment by rsmckinney** [comment]
Please read the section on [Extension Libraries](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-libraries), particularly the part about `Contains-Sources`:
>
> With Maven use the maven-jar-plugin to add the Contains-Sources manifest entry to your Jar file:
>```xml
><build>
> <plugins>
>   <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-jar-plugin</artifactId>
>     <configuration>
>       <archive>
>         <manifestEntries>
>           
>           <Contains-Sources>java,class</Contains-Sources>
>         </manifestEntries>
>       </archive>
>     </configuration>
>   </plugin>
> </plugins>
></build>
>```
>Similarly with Gradle add the Contains-Sources manifest attribute:
>```groovy
>jar {
>   manifest {
>       attributes('Contains-Sources':'java,class')
>   }
>}
>```

**Comment by zcfire2017** [comment]
> [请阅读扩展库](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#extension-libraries)部分，特别是以下部分`Contains-Sources`：
> 
> > 对于 Maven，使用 maven-jar-plugin 将 Contains-Sources 清单条目添加到您的 Jar 文件中：
> > ```
> > <build>
> > <plugins>
> >   <plugin>
> >     <groupId>org.apache.maven.plugins</groupId>
> >     <artifactId>maven-jar-plugin</artifactId>
> >     <configuration>
> >       <archive>
> >         <manifestEntries>
> >           
> >           <Contains-Sources>java,class</Contains-Sources>
> >         </manifestEntries>
> >       </archive>
> >     </configuration>
> >   </plugin>
> > </plugins>
> > </build>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 与 Gradle 类似，添加 Contains-Sources 清单属性：
> > ```groovy
> > jar {
> >   manifest {
> >       attributes('Contains-Sources':'java,class')
> >   }
> > }
> > ```

**Comment by zcfire2017** [comment]
@rsmckinney  thank you very much, the problem is solved
