### ISSUE TITLE
@var error

### ISSUE THREAD

**Issue by zcfire2017** [manifold-systems/manifold#524]
```java
package com.kc.controller.rule_engine;


import manifold.ext.props.rt.api.get;
import manifold.ext.props.rt.api.set;
import manifold.ext.props.rt.api.var;

public class MyTest {
	@var String name;
	@var Integer age;
	@var String sex;
	@set String address;
	@get String gg = "";
}
``` 

The @var above will report an error, but it can be used normally. IDEA will have a red underline on it. How can this be resolved?
and only @var reports errors, @get, @set, and all of these are fine

**Comment by sxpynu** [comment]
这个问题我也碰到过，很可能是 Manifold 插件与 IDEA 的版本不匹配导致的，把 IDEA 升级到当前最新版（v2023.2.5）后此问题消失。

**Comment by rsmckinney** [comment]
Hi @zcfire2017. This is pretty standard stuff and works/tests fine for me. As @sxpynu suggests, there is likely configuration issue. Your version info (IJ, Java, Manifold, etc.) will help to diagnose the problem, and your build file[s] too for a quicker diagnosis.  Thanks.

**Comment by zcfire2017** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.3</version>
		<relativePath/> 
	</parent>

	<groupId>com.kc</groupId>
	<artifactId>webapi</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<modules>
		<module>m1</module>
	</modules>

	<properties>
		<source.version>17</source.version>
		<target.version>17</target.version>
		<encoding>UTF-8</encoding>
		<spring.boot.version>3.1.3</spring.boot.version>
		<smart-doc.version>2.7.6</smart-doc.version>
		<manifold.version>2023.1.27</manifold.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>${spring.boot.version}</version>
		</dependency>
		<dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>2.2</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
		<dependency>
			<groupId>systems.manifold</groupId>
			<artifactId>manifold-science</artifactId>
			<version>${manifold.version}</version>
		</dependency>
		<dependency>
			<groupId>systems.manifold</groupId>
			<artifactId>manifold-strings</artifactId>
			<version>${manifold.version}</version>
		</dependency>
		<dependency>
			<groupId>systems.manifold</groupId>
			<artifactId>manifold-tuple</artifactId>
			<version>${manifold.version}</version>
		</dependency>
		<dependency>
			<groupId>systems.manifold</groupId>
			<artifactId>manifold-props-rt</artifactId>
			<version>${manifold.version}</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>${source.version}</source>
					<target>${target.version}</target>
					<encoding>${encoding}</encoding>
					<skip>true</skip>
					<compilerArgs>
						
						<arg>-Xplugin:Manifold no-bootstrap</arg>
						<arg>-implicit:class</arg>
					</compilerArgs>
					
					<annotationProcessorPaths>
						<path>
							<groupId>systems.manifold</groupId>
							<artifactId>manifold-props</artifactId>
							<version>${manifold.version}</version>
						</path>
						<path>
							<groupId>systems.manifold</groupId>
							<artifactId>manifold-collections</artifactId>
							<version>${manifold.version}</version>
						</path>
						<path>
							<groupId>systems.manifold</groupId>
							<artifactId>manifold-ext</artifactId>
							<version>${manifold.version}</version>
						</path>
						<path>
							<groupId>systems.manifold</groupId>
							<artifactId>manifold-strings</artifactId>
							<version>${manifold.version}</version>
						</path>
						<path>
							<groupId>systems.manifold</groupId>
							<artifactId>manifold-tuple</artifactId>
							<version>${manifold.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<archive>
						<manifestEntries>
							
							<Contains-Sources>java,class</Contains-Sources>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.3.1</version>
			</plugin>
		</plugins>
	</build>
</project>_`

**Comment by zcfire2017** [comment]
![2](https://github.com/manifold-systems/manifold/assets/34852479/478e8889-79b1-4abb-bf27-1cf2ef001f04)

**Comment by zcfire2017** [comment]
> Hi @zcfire2017. This is pretty standard stuff and works/tests fine for me. As @sxpynu suggests, there is likely configuration issue. Your version info (IJ, Java, Manifold, etc.) will help to diagnose the problem, and your build file[s] too for a quicker diagnosis. Thanks.

I know what's going on, it's a problem with the Chinese package
![image](https://github.com/manifold-systems/manifold/assets/34852479/5f7404ed-984a-4624-bf47-43df9a91e611)

Disabling this plugin will prevent errors from occurring

**Comment by rsmckinney** [comment]
Interesting. I can suppress the error so that you can continue using the Chinese plugin. I’ll need to reproduce the error though. What is the Chinese plugin you are using?
