### ISSUE TITLE
IDE plugin does not recognise symbols provided by a custom SymbolProvider

### ISSUE THREAD

**Issue by PORTB** [manifold-systems/manifold#525]
**Describe the bug**
I have tried to replicate the android build symbol provider for my own purposes. While compilation is working as expected, the intellij  plugin does not seem to be recognising the symbols from the symbol provider. I'm unsure if this is a supported feature, or if I have done something wrong.

**To Reproduce**

Here is some code that demonstrates my issue:
Demo SymbolProvider project: https://codeberg.org/PORTB/ManifoldCustomSymbolProvider
Demo project that uses the symbol provider: https://codeberg.org/PORTB/ManifoldProjUsesCustomSymbols

If you want to build/run the programs, publish the symbol provider project to maven local first, then run/build the second project.

**Expected behavior**
IDEA plugin to show that a symbol from a SymbolProvider has been defined 

**Screenshots**
IDE does not detect symbols:
![image](https://github.com/manifold-systems/manifold/assets/34615701/8f245d51-7638-48fd-b94f-227fbf0d6a19)
However, program compilation and output is correct:
![image](https://github.com/manifold-systems/manifold/assets/34615701/37b853c5-d07d-4c5f-953f-cfca86e2a29d)

**Desktop (please complete the following information):**
- OS Type & Version: Linux mint 21.2
- Java/JDK version: 17.0.8
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2023.2.2 (Community Edition)
- Manifold version: 2023.1.30
- Manifold IntelliJ plugin version:  2023.2.6

**Comment by rsmckinney** [comment]
Hi @PORTB. Just getting around to this, apologies for the delay. You are not at fault here, there is an issue with resolving SymbolProvider services from the IDE. I'll have a fix for this available in the next release sometime next week. Thanks for reporting this!
