### ISSUE TITLE
Issue with multiple module project and Extension Methods

### ISSUE THREAD

**Issue by aikar** [manifold-systems/manifold#53]
**Describe the bug**
I have module "Empire" and module "EmpireCraft-API"
org.bukkit.entity.Player is in EmpireCraft-API
I created extensions.org.bukkit.entity.Player; in the Empire module which depends on EmpireCraft-API

I receive the following warning:
https://i.imgur.com/P6bxIHr.png

**Expected behavior**
To not get this warning as it's in a different module

**Desktop (please complete the following information):**
- OS Type & Version:  Linux Mint 19
- Java/JDK version: 8/202
- IntelliJ IDEA version: 2019.1
- Manifold version: RELEASE
- Manifold IntelliJ plugin version: .53 alpha

**Additional context**
Trying to use "New Extension class" gives same issue.

**Comment by aikar** [comment]
Hmm, if you can't reproduce close, as i cleared my caches and rebuilt project setup and the issue is gone now.

**Comment by aikar** [comment]
hmm, ok it only worked because my project was 'busted' and the other modules were no longer considered properly in the project.

Once I fixed my project back to normal the error has returned.

it still works, just gives me an annoying error as shown that I cant ignore.

**Comment by rsmckinney** [comment]
I'm having trouble reproducing this one.  Can you change your Manifold version from `RELEASE` to `0.53-alpha` or later?  Thanks.

**Comment by aikar** [comment]
@rsmckinney the issue is with the IDEA plugin. it compiles fine, it's just the IDE telling me something untrue. 

https://i.imgur.com/nVj0ORj.png

**Comment by rsmckinney** [comment]
Fix on the way

**Comment by rsmckinney** [comment]
Fixed with Manifold IJ plugin 0.56-alpha
