### ISSUE TITLE
`ProcessCanceledException` thrown by Manifold IDEA plugin

### ISSUE THREAD

**Issue by rlnt** [manifold-systems/manifold#531]
**Describe the bug**
When opening my project which is using Manifold-ext, IDEA is throwing an internal error.

**Desktop (please complete the following information):**
- OS Type & Version: Windows 11 Pro 22H2
- Java/JDK version: JetBrains Runtime 17.0.8
- IDE version: IntelliJ IDEA 2023.2.5 Ultimate
- Manifold version: 2023.1.31
- Manifold IntelliJ plugin version: 2023.2.9

**Stack trace**
https://pastebin.com/wMJbBWq5

**Comment by rsmckinney** [comment]
Fix available with latest plugin release.

**Comment by rlnt** [comment]
yup, no more error is being thrown, thanks 👍🏼
