### ISSUE TITLE
The String Template plugin will false alert on SpEL expressions with default values.

### ISSUE THREAD

**Issue by sxpynu** [manifold-systems/manifold#532]
**Describe the bug**
After using the "string template" plugin, it does not correctly recognize the default value of the SpEL expression in the @Value annotation.

**To Reproduce**
1. Add `manifold-strings` to POM.xml
2. Use the @Value annotation with a default value like below Screenshots

**Expected behavior**
Should not parse a SpEL expression as a String Template.

**Screenshots**
<img width="339" alt="iShot_2023-12-05_00 41 36" src="https://github.com/manifold-systems/manifold/assets/57227961/464050fd-92ad-4126-86c4-68530259772a">

**Desktop (please complete the following information):**
- Java/JDK version: 17
- IDE version (IntelliJ IDEA or Android Studio): IDEA 2023.2.5
- Manifold version: 2023.1.31
- Manifold IntelliJ plugin version: 2023.2.10

**Comment by rsmckinney** [comment]
@sxpynu Note, this is just an IntelliJ editor error, the compiler plugin correctly excludes string template processing from annotations such as SpEL; your project will compile as it should. This issue will be fixed in the next IntelliJ plugin release later in the week. Thanks for reporting this!

**Comment by sxpynu** [comment]
Nice！Looking forward to the next update!
