### ISSUE TITLE
IDEA 2023.3 error

### ISSUE THREAD

**Issue by zcfire2017** [manifold-systems/manifold#534]
![image](https://github.com/manifold-systems/manifold/assets/34852479/8d0f2a62-2d10-4767-8c83-edec1a6078da)
![image](https://github.com/manifold-systems/manifold/assets/34852479/a56f1870-b6bc-4d9d-9362-ca2c0db9fb3c)
![image](https://github.com/manifold-systems/manifold/assets/34852479/46a44de8-7329-4b12-a261-954d942519a3)

After upgrading the idea to version 2023.3, the extension method started to report errors and could run, but the code prompt did not appear. The error was also displayed in the code, and the plugin version was the latest

**Comment by rsmckinney** [comment]
Hi @zcfire2017.  Have you tried closing and reopening the project? If the error persists, is there a way I can reproduce this error? For instance, is your project available for cloning?  Thanks

**Comment by zcfire2017** [comment]
@rsmckinney 
![image](https://github.com/manifold-systems/manifold/assets/34852479/75c0faa0-52e7-4934-b06c-0275a1d119ef)
![image](https://github.com/manifold-systems/manifold/assets/34852479/22ec0299-e9ea-4359-bf4b-898c889d6cb2)

清除缓存后就好了！真的太坑人了！找了一下午的bug

**Comment by rsmckinney** [comment]
Sometimes the IJ cache can become corrupt, have you tried invalidating caches?

**Comment by zcfire2017** [comment]
> Sometimes the IJ cache can become corrupt, have you tried invalidating caches?

Yes, I just need to clear the cache and it will be fine

**Comment by rsmckinney** [comment]
Hi @zcfire2017. I'll close this issue if everything has cleared up on your end. Okay?
