### ISSUE TITLE
Suppress "Non-final field" warning when using @val

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#535]
**Is your feature request related to a problem? Please describe.**
When using `@val` (which is inherently final), Intellij warns me that I'm using a non-final field.  
![image](https://github.com/manifold-systems/manifold/assets/32986779/b07a2eac-1fd1-4a97-9b1f-f477a30a6eca)
Adding the final keyword removes the warning, but this 'workaround' is applying the `final` keyword to the getter, which is not what should be done.

**Describe the solution you'd like**
No warning should be displayed.

**Comment by rsmckinney** [comment]
Hi @EotT123. I am unable to reproduce this issue. Is there any context missing?  It also helps to know the version of manifold, java, intellij your project uses.  Thanks.

**Comment by EotT123** [comment]
- Manifold 2023.1.31
- Intellij 2023.3
- Java 21

To see this warning, you should enable `non-final field in enum`:
<img src="https://www.imgdumper.nl/uploads9/6579ed9ba5c6e/6579ed9ba3d1a-screenshot.32.png" alt="6579ed9ba3d1a-screenshot.32" />

results in:
<img src="https://www.imgdumper.nl/uploads9/6579eb7d0ce6b/6579eb7d0a676-screenshot.28.png" alt="6579eb7d0a676-screenshot.28" />

However, I also get this warning for fields in non-enum classes. But in that case, there is an option which 'fixes' the problem. (although I'm not sure why, as this should only suppress warnings about unused fields if I'm correct)
<img src="https://www.imgdumper.nl/uploads9/6579ee1cb38b1/6579ee1cb10a3-screenshot.31.png" alt="6579ee1cb10a3-screenshot.31" />

**Comment by rsmckinney** [comment]
Still not able to reproduce.
![image](https://github.com/manifold-systems/manifold/assets/588843/d5d302b1-1c3d-4b1e-b239-b8889732574d)
Can you supply a sample application with build file (maven, gradle) so I can reproduce this? Or, just having your build file[s] handy will help reproduce and diagnose the issue.  Thanks!

**Comment by EotT123** [comment]
I've created a minimal project, which produces the warning: https://github.com/EotT123/manifold-test

In you screenshot, `value` isn't initialized by a constructor. It seems that's the difference.

<img src="https://www.imgdumper.nl/uploads9/657d85c57edbc/657d85c57ca8e-screenshot.33.png" alt="657d85c57ca8e-screenshot.33" /> <img src="https://www.imgdumper.nl/uploads9/657d8604dcbc0/657d8604da1c6-screenshot.35.png" alt="657d8604da1c6-screenshot.35" />

**Comment by rsmckinney** [comment]
Fix available in latest IJ plugin releases
