### ISSUE TITLE
Bootstrap.init() called multiple times

### ISSUE THREAD

**Issue by aikar** [manifold-systems/manifold#54]
**Describe the bug**
See decompiled output: https://i.imgur.com/L4QzuUx.png

OS Type & Version: Linux Mint 19
Java/JDK version: 8/202
IntelliJ IDEA version: 2019.1
Manifold version: RELEASE
Manifold IntelliJ plugin version: .53 alpha

**Comment by rsmckinney** [comment]
Change included with release '0.58-alpha`
