### ISSUE TITLE
manifold-ext with rxjava3 failed.

### ISSUE THREAD

**Issue by yueliangwen** [manifold-systems/manifold#546]
**Describe the bug**
I wanna extend the Flowable of rxjava(3.1.8), but cannot be compiled. The errors:

io/reactivex/rxjava3/core/Flowable.java:307: error: NonNull is not a repeatable annotation type
  public static <T>io.reactivex.rxjava3.core. @io.reactivex.rxjava3.annotations.NonNull() Flowable<T> fromArray(@io.reactivex.rxjava3.annotations.NonNull() @io.reactivex.rxjava3.annotations.NonNull() T... arg0) {
                                                                                                                                                            ^
io/reactivex/rxjava3/core/Flowable.java:2431: error: NonNull is not a repeatable annotation type
  public final io.reactivex.rxjava3.core. @io.reactivex.rxjava3.annotations.NonNull() Flowable<T> startWithArray(@io.reactivex.rxjava3.annotations.NonNull() @io.reactivex.rxjava3.annotations.NonNull() T... arg0) {

**Screenshots**
<img width="562" alt="image" src="https://github.com/manifold-systems/manifold/assets/1107708/b59f981a-585a-4fca-aaa3-feeae948e5db">

**Desktop (please complete the following information):**
- Manifold version: 2024.1.1

**Comment by rsmckinney** [comment]
Fix in progress. Will be available in next release EOD Sunday.

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.3. Thanks for reporting this!
