### ISSUE TITLE
Remove manifold yellow pop up

### ISSUE THREAD

**Issue by aikar** [manifold-systems/manifold#55]
The yellow popup about manifold not being setup for project, can we please default this off and only warn if the project uses manifold and detects a problem.

it is super annoying seeing this on projects that do not use manifold.

**Comment by rsmckinney** [comment]
This is fixed in the private repo for the Manifold IJ plugin project.  A new plugin release will be available from the Jetbrains plugins repo within two business days.

**Comment by rsmckinney** [comment]
Fixed with Manifold IJ plugin 0.56-alpha
