### ISSUE TITLE
[Question] SQL: Why are fetchBy<Name>() methods only generated for non-null columns? 

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#552]
Why are `fetchBy<Name>()` methods only generated for non-null columns? I think it would be useful to have those methods for all columns, regardless if they are nullable or not. 

There is no difference when writing an sql query for nullable or non-nullable columns, so in my opinion, it would be logical that there is also no difference in the generated methods.

**Comment by rsmckinney** [comment]
> Why are fetchBy<Name>() methods only generated for non-null columns?

It was an attempt at keeping the API tidy, but I think your suggestion is  justified, all columns should have fetchBy methods.  Thanks for reporting this.

Fix available with release 2024.1.5

**Comment by EotT123** [comment]
Thanks, it's working!
