### ISSUE TITLE
[Question] Difference between <Database>.addSqlChange(...) and <Database>.newScope().addSqlChange(...)

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#554]
There is a difference between `<Database>.addSqlChange(...)` and `<Database>.newScope().addSqlChange(...)`: The former throws an [SQLException](https://github.com/manifold-systems/manifold/blob/31608f073ea9c7cb085031c816ccc9801428dc0d/manifold-deps-parent/manifold-sql/src/main/java/manifold/sql/schema/type/SchemaParentType.java#L171), whereas the latter doesn't. As far I am aware, both methods are not actually commiting the changes, but only when the `commit` method is called (which obviously can throw an `SQLException`).

So why can `<Database>.addSqlChange(...)` throw an `SQLException`? Is this needed? Or can the throw declaration be removed?
If I'm understanding the code correctly, `<Database>.addSqlChange(...)` is calling [this method](https://github.com/manifold-systems/manifold/blob/31608f073ea9c7cb085031c816ccc9801428dc0d/manifold-deps-parent/manifold-sql-rt/src/main/java/manifold/sql/rt/impl/BasicTxScope.java#L127), which isn't throwing an `SQLException`.

**Comment by rsmckinney** [comment]
Hi @EotT123. Yep, you're right.  The `<Database>.addSqlChange()` is generated and the throws list is a vestige from a time when `TxScope.addSqlChange()` also had thrown the exception. That will be cleaned up in the next release in a couple of days. Thanks for reporting this. You're providing a lot of great feedback!

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.6

**Comment by EotT123** [comment]
Thanks!
