### ISSUE TITLE
SQL: properties not working for generated getters for boolean fields

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#557]
**Describe the bug**
[Properties](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-props) for generated setters for database objects (using SQL manifold) for boolean fields are not working.

* normal getters (both working):
  * `[Object].getNonBooleanValue()`
  * `[Object].isBooleanValue()`

* Properties:
  * `[Object].nonBooleanValue`
  * `[Object].booleanValue`  --> not working

However, Intellij (wrongly) suggests the following: `[Object].isBooleanValue`, but that isn't compiling. The following compilation errors are displayed: 
* `Cannot access write-only property 'isBooleanValue'` when accessing a property
* `Cannot assign read-only property 'isBooleanValue'` when setting a property.

'is'-getters were introduced in this PR: https://github.com/manifold-systems/manifold/commit/6cd7584ac7d28ad84f0b9bcd0598dfdd00c85ecb

**Desktop (please complete the following information):**
- Manifold version: 2024.1.9
- Manifold IntelliJ plugin version: 2023.3.20

**Comment by rsmckinney** [comment]
I'm not able to reproduce this. Testing with (H2) tables each having boolean column variations.
```sql
CREATE TABLE test1(
  foo BOOLEAN NOT NULL,
...
)
```
and
```sql
CREATE TABLE test2(
  is_foo BOOLEAN,
...
)
```
Both compile and function as designed, including IJ plugin behavior.
```java
...
var test1= "[.sql/] select * from Test1".fetch();
for(var t: test1) {
    out.println(t.isFoo);
    t.isFoo = true;
```
and
```java
var test2 = "[.sql/] select * from Test2".fetch();
for(var t: test2) {
    out.println(t.isFoo);
    t.isFoo = true;
```

Can you provide your table definition[s]?

**Comment by EotT123** [comment]
My table definition is exactly the same as yours:
```
CREATE TABLE test1(
  foo BOOLEAN NOT NULL,
...
)
```

However, in your example, you use `t.isFoo = true;`, but it should be `t.foo = true;`
Getter should use the 'is' prefix (e.g. `t.isFoo()`), but this prefix should not be used for properties (e.g. `t.foo`)
For non-boolean fields, getters use the `get` prefix (e.g. `t.getNonBoolean()`), and no prefix for properties  (e.g. `t.nonBoolean`), so in that case, it is correct.

`t.isFoo = true;` builds fine in intellij with the IJ plugin, but not when compiling with maven.

**Comment by rsmckinney** [comment]
Boolean getter/setter methods are kinda weird. There's no standard so you can have both `isBook()` and `getBook()` methods in the same type. Additionally, the naming convention is also up for grabs. You can have a `boolean` field `isBook` where the getter can be `isIsBook()` or just `isBook()`.

Other languages with properties often follow the naming convention to prefix booleans with "is". This heavily influenced my strategy for inferring property names. This is basically why I chose to infer boolean properties consistently as "isXxx". It many not be immediately intuitive, but I'm banking on IJ code completion to clarify: typing "xxx" will prominently display "isXxx". _shrug_

**Comment by EotT123** [comment]
I think you are missing the point here. 

Let me explain it in a different way. First let's have a look at a normal class with some fields:
```
public class Test{
  @val boolean booleanField;
  @val String stringField;

  ...
}
```

For this class, we have some getters:
* `test.isBooleanField()`
* `test.getStringField()`

When using properties, the following can be used:
* `test.booleanField`
* `test.stringField`


Let's now have a look at classes generated for database tables:
```
CREATE TABLE test(
  booleanField BOOLEAN NOT NULL,
  stringField VARCHAR(50)
)
```

I expect the same behaviour as the example above, i.e.
* 2 getters:
  * `test.isBooleanField()`
  * `test.getStringField()`

* And when using properties, the following should be usable:
  * `test.booleanField`
  * `test.stringField`

However, this is not the case. `test.booleanField` cannot be used. IntelliJ is suggesting `test.isBooleanField`, but there should not be a prefix when using properties! A prefix should only be used when using the 'getter' method to access the field (i.e. standard java behavior, no manifold). When using the non-boolean property field, no prefix is added, which is correct. 

So I'm not talking about naming conventions, but rather about the consistency of the names.

**Comment by rsmckinney** [comment]
Schema APIs are generated as just getters/setters, manifold-sql does not use properties, regardless of your project’s use of manifold-props. So there is no practical way to infer the would-be property name corresponding with method isBooleanField(). 

I considered adding an option to generate code using properties for manifold-sql, probably as a dbconfig preference.

**Comment by EotT123** [comment]
But I am using properties for schema generated files. So why is that working?

![image](https://github.com/manifold-systems/manifold/assets/32986779/cfa1efc6-70ab-482b-8835-f06794a376ce)
At the top, there you have the properties, and at the bottom, the normal getters. As you can see, the boolean properties are prefixed, whereas the non-boolean are not prefixed. 


Database table (SQLite)
```
CREATE TABLE IF NOT EXISTS occasion
    (
        occasion_id                              INTEGER PRIMARY KEY autoincrement NOT NULL,
        year                                     INTEGER NOT NULL,
        month                                    INTEGER NOT NULL,
        occasion_name                            text NOT NULL,
        use_customer_id                          BOOLEAN NOT NULL,
        use_multiple_orders                      BOOLEAN NOT NULL,
        number_of_columns                        INTEGER NOT NULL,
        number_of_rows                           INTEGER NOT NULL
    );
```

**Comment by rsmckinney** [comment]
Those are all _inferred_ from getters/setters in the generated schema API. When you use manifold-properties in a project _all_ classes with getter/setter methods will have corresponding inferred properties.

Again, manifold-sql does not use manifold-props; the code it generates for data access consists of plain getters/setters. Thus, all the properties you see in IJ corresponding with manifold-sql are inferred.

**Comment by EotT123** [comment]
Ok, thanks for you explanation. I'll use the getters instead. 
But it's still a bit weird that IntelliJ automcompletes the inferred properties and doesn't show any indication that they should not be used.

**Comment by rsmckinney** [comment]
No problem, all good questions.

Note, you can use either getters/setters or inferred properties, up to you. Of course, the inferred properties are only available if your project/module uses manifold-props.
