### ISSUE TITLE
Add support for jdk 22

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#565]
Compiling with jdk 22 (even if targeting 21) doesn't work at the moment, and is also not officially supported (see documentation: `All fully supported in JDK LTS releases 8 - 21`). Are you working on supporting it?

**Comment by rsmckinney** [comment]
It is supported and documented as "JDK LTS releases 8 - 21 + latest",  where "latest" is whatever the latest JDK is, currently 22.

What kind of trouble are you experiencing? If you are building with IntelliJ, make sure you are using IDEA 2024.1, which is the only IJ release that supports JDK 22.

**Comment by EotT123** [comment]
It doesn't work for me. Even when trying to build my [small sample project](https://github.com/EotT123/manifold-test) doesn't work.
Compiling with java 21 works fine, but errors when using java 22, both with maven and latest IntelliJ.

Output when building with maven:
```
[ERROR] Compilation failure: Compilation failure:
[ERROR] /java/net/URL.java:[264,35] package jdk.internal.misc does not exist
[ERROR] /java/net/URL.java:[21,29] cannot find symbol
[ERROR]   symbol:   class UrlDeserializedState
[ERROR]   location: package java.net
[ERROR] /java/lang/Object.java:[6,30] package jdk.internal.vm.annotation does not exist
[ERROR] /java/lang/Object.java:[10,30] package jdk.internal.vm.annotation does not exist
[ERROR] /java/lang/Object.java:[14,30] package jdk.internal.vm.annotation does not exist
[ERROR] /java/lang/Object.java:[21,30] package jdk.internal.vm.annotation does not exist
[ERROR] /java/lang/Object.java:[28,30] package jdk.internal.vm.annotation does not exist
[ERROR] /java/lang/Object.java:[32,30] package jdk.internal.vm.annotation does not exist
[ERROR] /java/net/URL.java:[264,78] package jdk.internal.misc does not exist
[ERROR] -> [Help 1]
[ERROR]
```

Maven info:
```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Java version: 22, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-latest
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

When removing all manifold related things, the build works.

Building other projects results in different (but similar) error messages.

But it seems that not all builds are failing in IntelliJ. However, they are always failing when building with maven.

**Comment by rsmckinney** [comment]
With maven you need to change your pom file to use

**Comment by EotT123** [comment]
Thanks, that [fixed it](https://github.com/EotT123/manifold-test/actions/runs/8583043314/job/23521813395)!
