### ISSUE TITLE
Extension method for Object object fails with interface receiver

### ISSUE THREAD

**Issue by 007idle** [manifold-systems/manifold#566]
**Describe the bug**
The Object object extends the method get Generic Type Of Interface, but when I pass in an object that is an interface, I receive a prompt of 'java. lang. No Such Method Error'. If the parameter is not an interface, I call it normally

**To Reproduce**
1.  my extends method is 
@SuppressWarnings("unchecked")
@Extension
public class ObjectExt {
  public static Class<?> getGenericTypeOfInterface(@This Object value, int index) {
    Type[] interfaces = value.getClass().getGenericInterfaces();
    Type[] var2 = interfaces;
    int var3 = interfaces.length;

    for (int var4 = 0; var4 < var3; ++var4) {
      Type type = var2[var4];
      if (type instanceof ParameterizedType) {
        ParameterizedType parameterizedType = (ParameterizedType) type;
        Type[] actualTypeArguments = parameterizedType.getActualTypeArguments();
        if (actualTypeArguments.length > 0) {
          Type genericType = actualTypeArguments[index];
          if (genericType instanceof Class) {
            return (Class) genericType;
          }
        }
      }
    }
    return null;
  }
}
3.
4.

**Expected behavior**
call it normally

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version:  windows 11
- Java/JDK version: jdk21
- IDE version (IntelliJ IDEA or Android Studio):  2023.3
- Manifold version: 2023.1.33
- Manifold IntelliJ plugin version:  2023.1.33

**Additional context**

**Stack trace**
java.lang.NoSuchMethodError: 'java.lang.Class com.baomidou.mybatisplus.core.mapper.BaseMapper.getGenericTypeOfInterface(int)'
	at com.z.bean.service.impl.LogServiceImpl.getEntityClass(LogServiceImpl.java:215) ~[classes/:?]
	at com.z.bean.service.impl.LogServiceImpl.recordUpdate(LogServiceImpl.java:128) ~[classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.12. Thanks for reporting this!

**Comment by 007idle** [comment]
Upgraded to April 12, 2021, my issue has been resolved.Thanks
