### ISSUE TITLE
fasterxml.jackson can't create an instance of a manifold JSON object 

### ISSUE THREAD

**Issue by dakotahNorth** [manifold-systems/manifold#567]
Trying to create an object to use with fasterxml/jackson 

This code worked when ExampleEvent was a concrete Java class that is simply a Java object for a JSON class. 

    private Consumer<JsonNode> createHandler(Method method, Class<?> eventClass, Object bean) {
        return jsonNode -> {
            try {
                Object event = objectMapper.treeToValue(jsonNode, eventClass);
                method.setAccessible(true);
                method.invoke(bean, event);
            } catch (Exception e) {
                throw new RuntimeException("Error invoking handler method: " + method.getName(), e);
            }
        };
      }

And the concrecte Java class 

    /**
     * 
     * This class should align with the JSON message structure being handled.
     *
     * Key Points:
     * - Default Constructor: Necessary for JSON deserialization. Frameworks like Jackson
     *   require a no-argument constructor to instantiate the object before populating its fields.
     * - Field with Getter and Setter: The `data` field represents the content of the event.
     *   Getters and setters are essential for accessing the field's value and for Jackson to
     *   deserialize JSON into this object.
     * - toString Method: Provides a string representation of the object, useful for logging
     *   and debugging purposes.
     */
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ExampleEvent {

        private String data; // The data field of the event

        /**
         * Default constructor is required for frameworks like Jackson to deserialize
         * JSON content into a MyEvent object.
         */
        public ExampleEvent() {
        }

        /**
         * Constructs a MyEvent with the specified data.
         * @param data The data content of the event.
         */
        public ExampleEvent(int data) {

        }

        /**
         * Gets the data content of the event.
         * @return The data content of the event.
         */
        public String getData() {
            return data;
        }

        /**
         * Sets the data content of the event.
         * @param data The data content to set.
         */
        public void setData(String data) {
            this.data = data;
        }

        /**
         * Returns a string representation of the MyEvent object, which includes its data content.
         * Useful for logging and debugging.
         * @return A string representation of the MyEvent object.
         */
        @Override
        public String toString() {
            return "MyEvent{" +
                "data='" + data + '\'' +
                '}';
        }
    }

But, this seemed like a perfect example to use manifold JSON schema to define the class. 

      {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "http://com.example.solace.springboot.starter.messaging.ExampleEvent.json",
        "title": "ExampleEvent",
        "type": "object",
        "properties": {
          "messageType": { "type": "string" },
          "data": { "type": "string" }
        },
        "required": ["messageType", "data"]
      }

But when using the Manifold class, the following error occrus. 
          
       Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of 
       `com.example.solace.springboot.starter.messaging.ExampleEvent`    
       (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, 
       have custom deserializer, or contain additional type information

Should JSON created object have a default constructor? 

How to handle the ability for `@JsonIgnoreProperties(ignoreUnknown = true)`?

**Comment by rsmckinney** [comment]
Have not used jackson with manifold-json, but the jackson documentation claims if you include the javac `-parameters` option, all the wiring annotations are not required. Have you tried that?

**Comment by rsmckinney** [comment]
Good to know re FastJSON. Curious to know why you aren't just using manifold-json, why FastJson at all?

**Comment by rsmckinney** [comment]
>Could I have done that with manifold?

From what I can gather, yes. You can use `manifold.json.rt.Json.fromJson(String)` in place of `JSON.parseObject(String)`.
```java
  void onMessageReceived(String messagePayload) {
    try {
      Bindings rootNode = (Bindings) Json.fromJson(messagePayload);
      String messageType = (String) rootNode.get("messageType");
      List<Consumer<Bindings>> handlers = messageTypeHandlers.get(messageType);
      if (handlers != null && !handlers.isEmpty()) {
        handlers.forEach(handler -> handler.accept(rootNode));
      } else {
        System.out.println("Unhandled messageType: " + messageType);
      }
    } catch (RuntimeException e) {
      e.printStackTrace();
    }
  }
```

Taking it to another level, the message payload could be made type-safe instead of using untyped JsonObject/Bindings. Given `messageType` can map to a Java type corresponding with manifold-json, consumers of events could be hardcore type-safe. Think `Consumer<T>` as opposed to `Consumer<JsonNode>`. But that may not make sense depending on your problem space.

This could be achieved using the `Xxx.load().fromJson(jsonString)` where `Xxx` is a manifold-json derived type. Since you are loading these dynamically, you would have to use this API reflectively.
```java
    String jsonJavaType = (String) rootNode.get("messageType");
    Loader<?> loader = (Loader<?>) ReflectUtil.method(jsonJavaType, "load").invokeStatic();
    Object typesafeObj = loader.fromJson(rootNode.get("message"));
    ...
    List<Consumer> handlers = messageTypeHandlers.get(messageType);
    handlers.forEach(handler -> handler.accept(typesafeObj)); // type-safe at method receiver
```
Where handler could be something like:
```java
public class MyMessageConsumer implements Consumer<MyMessageType> {
  public void accept(MyMessageType t) {
    . . .
  }
}
```

Anyhow, food for thought.
