### ISSUE TITLE
Preprocessor not working with the IntelliJ plugin

### ISSUE THREAD

**Issue by Hallilogod** [manifold-systems/manifold#569]
**Problem:**
Whenever i use any preprocessor directives like #define #if #else IntelliJ just complains about incorrect syntax like if the plugin wouldnt be there.

![grafik](https://github.com/manifold-systems/manifold/assets/129677832/4a8fd18d-05d3-4fc9-bffe-45741a1866c8)

I am using IntelliJ IDEA 2022.3.1 Community Edition.

**Comment by rsmckinney** [comment]
Hi @Hallilogod. Is your project using the `manifold-preprocessor` dependency in the annotation processor path as documented [here](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-preprocessor#setup)?

**Comment by Hallilogod** [comment]
Hi, adding the dependency fixed the issue, thanks! However IntelliJ still reports the preprocessor directives as syntax errors:

![grafik](https://github.com/manifold-systems/manifold/assets/129677832/d83ee157-ed08-4a1a-890b-fb55ebe029c4)

is there a way to fix this with the plugin or do i just have to disable this error?

**Comment by Hallilogod** [comment]
**Edit:** it works now, i think i just forgot to restart the ide or idk

![grafik](https://github.com/manifold-systems/manifold/assets/129677832/47d4c51e-fee4-44e4-b4b8-b04204fc1ef3)
