### ISSUE TITLE
Enum's without default constructor can't be extended

### ISSUE THREAD

**Issue by aikar** [manifold-systems/manifold#57]
**Describe the bug**
Given this ugly file:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Material.java
Simply trying to start the stub of extensions like this:
```java
package EMC.extensions.org.bukkit.Material;
import manifold.ext.api.Extension;
@Extension
public class MaterialExtensions {}
```
I can no longer compile as I get this error:
https://gist.github.com/aikar/9beca78a2fa7b6f9abc774aec31bdb45

Deleting the empty extension file fixes the issue. but I am prevented from extending this class.

Same issue happens to me on World.java here too:
https://gist.github.com/aikar/ac868af870375dca458d84ff2a32007c

**Expected behavior**
No errors

OS Type & Version: Linux Mint 19
Java/JDK version: 1.8.0_191
IntelliJ IDEA version: 2019.1
Maven Compiler Plugin 3.7.0
Manifold version: RELEASE
Manifold IntelliJ plugin version: .55 alpha

-Xplugin:Manifold strings

Relevant context: Lombok is also in use - but other Extensions work. Just specific classes giving trouble.

**Comment by aikar** [comment]
It seems to relate to enums without a default constructor. In World.java when I move Environment out of the World class, the error goes away.

If I stub in a default constructor to Environment leaving it in the world class, it also goes away.

**Comment by rsmckinney** [comment]
in progress

**Comment by rsmckinney** [comment]
Unable to reproduce this one. HOWEVER, I have a related fix in the works which may have fixed this issue.  I'll post here when it's ready (sometime later today).

>Note, if you are using Lombok, you must use the latest release (**v1.18.6**).  There are bug fixes in that release that address compatibility issues with Manifold.  You can also use the "edge" release if you prefer that.

>Also note, if you are using Java 11, use Maven 3.8.x.
If you use Maven 3.8.x, you should also change `<path>` to `<processorPath>` inside `<annotationProcessorPaths>`

**Comment by aikar** [comment]
Ok i'll try lombok .6 later when I get home. I am on .4 atm.

**Comment by aikar** [comment]
updating to lombok 1.18.6 did not fix it, as well as compiler to 3.8.0 and shade to 3.2.1, so waiting for the new build.

**Comment by rsmckinney** [comment]
Could I ask you to reduce this to a reproducible case?  Or a zipped project you can send via email?  I'd like to reproduce your case here to be sure I'm not missing anything.  Thanks.

**Comment by rsmckinney** [comment]
You can try the new manifold release 0.56-alpha with the new Manifold IJ pluign release also 0.56-alpha.  However the plugin is awaiting Jetbrains approval before it enters the repo.  You can get download it directly if you'd like to try it before it's available from inside IJ: [plugin release 0.56-alpha](https://plugins.jetbrains.com/plugin/download?updateId=60354&pluginId=10057&version=0.56-alpha)

**Comment by aikar** [comment]
@rsmckinney updated to 0.56-alpha and nothing has changed about the problem. 
please try adding:
```xml
        <repository>
            <id>papermc</id>
            <url>https://papermc.io/repo/repository/maven-public/</url>
        </repository>
```
With 
```xml
        <dependency>
            <groupId>com.destroystokyo.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.13.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```
Then try 

```java
package EMC.extensions.org.bukkit.Material;

import manifold.ext.api.Extension;
import manifold.ext.api.This;
import org.bukkit.Material;
import org.bukkit.Tag;

@Extension
public class MaterialExtensions {
    public static boolean is(@This Material material, Material... oneOf) {
        for (Material test : oneOf) {
            if (test == material) {
                return true;
            }
        }
        return false;
    }

    public static boolean is(@This Material material, Tag<Material> tag) {
        return tag.isTagged(material);
    }
}

```

**Comment by aikar** [comment]
I added in empirecraft-api (which is simply an extension of paper-api)
```java
package com.empireminecraft;

public enum Test {
    FOO(1);

    Test(int i) {
    }
}
```
and maven installed, then tried the following extension in Empire:
```java
package EMC.extensions.com.empireminecraft.Test;

import com.empireminecraft.Test;
import manifold.ext.api.Extension;
import manifold.ext.api.This;

@Extension
public class TestExtension {
    public static void helloWorld(@This Test thiz) {
        System.out.println("hello world!");
    }
}
```

And it replicates the issue: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Empire: Compilation failure
[ERROR] /com/empireminecraft/Test.java:[5,3] constructor Test in enum com.empireminecraft.Test cannot be applied to given types;
[ERROR] required: int
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length
```

However if Test enum is moved into same Empire package, things compile. Seems to only occur when extending from the api artifact.

This is the API artifacts POM for reference: https://gist.github.com/aikar/8f88356b1e2054838bd264df369b118b

**Comment by rsmckinney** [comment]
@aikar I'll have a look later today.  Thanks again for reporting this and providing the info.

**Comment by rsmckinney** [comment]
There is a change in release 0.57-alpha that should fix the issue.  Please give that a try, thanks.

**Comment by aikar** [comment]
Thank you!!! it works :dancing_men: :dancing_women: :+1:

**Comment by rsmckinney** [comment]
Good to hear!  Thanks.  I refined the change a bit and added more tests with `0.58-alpha`, if you'd like to try that one.
