### ISSUE TITLE
[Extension] Compilation failure when generic type name doesn't match.

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#575]
The following code doesn't compile. 
```
package extensions.javax.swing.JList;

import javax.swing.*;

import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.Self;
import manifold.ext.rt.api.This;

@Extension
public class JListExt {

    public static <T> @Self JList<T> testing(@This JList<T> jList) {
        return jList;
    }
}
```
Whereas this compiles fine (notice the change in generic type names from `T` to `E`)
```
package extensions.javax.swing.JList;

import javax.swing.*;

import manifold.ext.rt.api.Extension;
import manifold.ext.rt.api.Self;
import manifold.ext.rt.api.This;

@Extension
public class JListExt {

    public static <E> @Self JList<E> testing(@This JList<E> jList) {
        return jList;
    }
}
```

Javac error:
```
javax/swing/JList.java:309: error: cannot find symbol
  public javax.swing. @manifold.ext.rt.api.Self() JList<T> testing() {
                                                        ^
  symbol:   class T
  location: class JList<E>
  where E is a type-variable:
    E extends Object declared in class JList
```

Apparently, because of the extending class uses E as the name, I'm forced to use the same name?

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: openjdk 22
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2024.1 (Community Edition)
- Manifold version: 2024.1.12 (latest version at the moment)
- Manifold IntelliJ plugin version: 2023.3.24 (latest version at the moment)

**Comment by rsmckinney** [comment]
Yep, it’s an implementation shortcut. Doing the A+ solution where you define your own type var is over-the-top involved and imo not worth the trouble. _shrug_

Fwiw, this is documented in [manifold-ext docs](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-ext#generics) section on generics.

**Comment by EotT123** [comment]
I'm sorry, I didn't saw that in the documentation. Thanks for your answer.
