### ISSUE TITLE
Properties: dont call it type-safe if its not

### ISSUE THREAD

**Issue by avertx** [manifold-systems/manifold#581]
from Properties project README.md

"With the Properties type manifold we can access properties directly using simple, type-safe code:"

Calling a return of a String "type-safe"?  c'mon.  

I'm sure there's work to be done here regarding boilerplate casting, but the notion of type-safe properties means actually parsing the values...

**Comment by rsmckinney** [comment]
It is type safe in terms of naming. Without manifold you access properties using string literals, with manifold both property resource files and property names are directly referenced as identifiers. This is the essence of type-safety.
