### ISSUE TITLE
[manifold-sql] Code doesn't compile when using :: to cast a parameter or call function on parameter.

### ISSUE THREAD

**Issue by oldshensheep** [manifold-systems/manifold#589]
**Describe the bug**
Code doesn't compile when using `::` to cast a parameter.
```
error: method execute in interface Fragment_7963949495587867082 cannot be applied to given types;
              "[.sql/] insert into table_name(data) values(?::jsonb) ".execute(ctx,
                                                                                                  ^
  required: SqlChangeCtx
  found:    SqlChangeCtx,String
  reason: actual and formal argument lists differ in length
```
**To Reproduce**
`table_name(data)` is jsonb in postgresql
```java
            DB.addSqlChange(ctx -> {
              "[.sql/] insert into table_name(data) values(?::jsonb) ".execute(ctx,"string");
            });
```
```java
            DB.addSqlChange(ctx -> {
              "[.sql/] insert into table_name(data) values(to_hex(?)) ".execute(ctx,"string");
            });
```

**Expected behavior**
The code should work like the example below.
```java
    Class.forName("org.postgresql.Driver");
    Connection conn = DriverManager.getConnection(
        "jdbc:postgresql://localhost:5432/postgres");
    String insertSQL = "INSERT INTO table_name(data) VALUES (?::jsonb)";
    try (PreparedStatement pstmt = conn.prepareStatement(insertSQL)) {
      pstmt.setString(1, "{}");
      pstmt.executeUpdate();
    } catch (SQLException e) {
      e.printStackTrace();
    }
```
**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version: 
- Java/JDK version: 21
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 
- Manifold version: 2024.1.14
- Manifold IntelliJ plugin version:  2024.1.0

**Additional context**

**Stack trace**
Please include a stack trace if applicable

**Comment by rsmckinney** [comment]
Hi @oldshensheep.  Manifold uses named parameters prefixed with `:` where you would otherwise use JDBC `?`.
```java
 DB.addSqlChange(ctx -> {
              "[.sql/] insert into table_name(data) values(to_hex(:data)) ".execute(ctx,"string");
            });

DB.addSqlChange(ctx -> {
              "[.sql/] insert into table_name(data) values(:data::jsonb) ".execute(ctx,"string");
            });
```
See the Query [docs](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-sql/readme.md#queries) for this.

**Comment by oldshensheep** [comment]
I just tried, still the same error.
If I change the database schema, change the type of `table_name(data)` from `jsonb` to `text` and remove the `::jsonb` from code, then no error occurred.

**Comment by oldshensheep** [comment]
Or if I remove the `::jsonb` from SQL, the code compiles, but fails at runtime.
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "data" is of type jsonb but expression is of type character varying
```
Is this an expected error? JDBC standard can't map jsonb so it fallback to string.

**Comment by rsmckinney** [comment]
Ah, yes there appears to be an issue with the json/jsonb postgresql data type. Will have a deeper look. Thanks.

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.15.  Thanks for reporting this!

**Comment by oldshensheep** [comment]
using `::` to cast a parameter works now but call function on parameter failed with the same error

**Comment by rsmckinney** [comment]
If your app defines more than one dbconfig, you probably need to qualify your sql command. Instead of `“[.sql/]…”` try `”[.sql:DB/]`.

**Comment by oldshensheep** [comment]
Ah, I see the manifold plugin error `  ERROR: function to_hex(unknown) is not unique Hint: Could not choose a best candidate function. You might need to add explicit type casts. Position: 87` 
I change the `to_hex(?)` to `to_hex(?::int)` , the code can be compiled again.
