### ISSUE TITLE
 [Question] Are Manifold String Templates evaluated lazily?

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#600]
Are [String Templates](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-strings) evaluated eagerly or lazily?
When using logging statements with traditional replacements, lazy evaluation is beneficial because the evaluation depends on the logging level.

**Comment by rsmckinney** [comment]
A String template evaluates eagerly. There is no other way since there is a single expression that must evaluate to a String value.

Of course, you can add your own laziness.
```java
String pet = "dog";
logger.debug("{}", message(()-> "my $pet has fleas"));
. . .
Object message(Supplier<String> msg) {
  return new Object() {
    public String toString() {
      return msg.get();
    }
  };
}
```
Would be a good idea to add nicer extension methods to your logger class if you did go this route, so you could write:
```java
logger.debug(()-> "my $pet has fleas");
```

**Comment by EotT123** [comment]
Thanks for the suggestion!
