### ISSUE TITLE
Intellij IDEA doesnt detect manifold-collection extension methods

### ISSUE THREAD

**Issue by miladamery** [manifold-systems/manifold#602]
**Describe the bug**
Following guides on how to use manifold-collections project the Intellij IDEA doesn't provide code auto completion or detection of provided extension methods for collection project. The build process is ok, I mean build finishes successfully and generated classes contain Manifold methods but IDE doesn't detect this.
(Build tool is gradle)

**To Reproduce**
1. Create a project with gradle as build tool
2. follow [Tutorial](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-collections/README.md#gradle) to set things up
3. Try to use manifold-collections but IDE wont cooperate

**Expected behavior**
IDE should provide code completion and do not complain about missing methods

**Desktop (please complete the following information):**
- OS Type & Version: Windows 11
- Java/JDK version: JDK 21
- IDE version (IntelliJ IDEA or Android Studio): 2024.1.1 (Ultimate Edition)
- Manifold version: 2024.1.17
- Manifold IntelliJ plugin version: 2024.1.5

**Comment by rsmckinney** [comment]
Hi @miladamery. This should work for you. Did you try reloading the project? You can also check Gradle settings in IntelliJ: 
```
File | Settings | Build, Execution, Deployment | Build Tools | Gradle. 
```
Make sure `Gradle JVM` is JDK 21 or better.

If that fails, I'm happy to have a look at your project, or I can provide a zip file containing a working project.

**Comment by miladamery** [comment]
Thanks.
