### ISSUE TITLE
Attatching annotation to annotation on classes

### ISSUE THREAD

**Issue by superxiao** [manifold-systems/manifold#614]
**Is your feature request related to a problem? Please describe.**
This is related to a previous issue https://github.com/manifold-systems/manifold/issues/611
Now attatching an annotation to another annotation on fields works as expected, and I use this feature to annotate all `@JsonProperty` fields as `@Keep` for ErrorProne. Now I would like to annotate all `@Service` classes as `@SuppressWarnings("HidingField")`, and this does not seem to work. Could it be that the value "HidingField" is not passed to the annotated class?

**Describe the solution you'd like**
```java
package ai.extensions.org.springframework.stereotype.Service;

import manifold.ext.rt.api.Extension;

@Extension
@SuppressWarnings("HidingField")
public class ServiceExt {}
```

```java
@Service
class AService extends AServiceBase {
  private int a;
}
```

```java
class AServiceBase {
  public int a;
}
```

I'm hoping this would prevent an ErrorProne warning of HidingField.

**Describe alternatives you've considered**

Even better to solve this problem, is to be able to annotate all child classes of a given class with certain annotation:
```java
@AnnotateChildClasses
@SuppressWarnings("HidingField")
public class AServiceBaseExt{}
```
where `AnnotateChildClasses` is a variant of `Extension` that supports adding annotation to all children classes of the class `AServiceBase`, but this probably is far-fetched.

**Additional context**

**Comment by rsmckinney** [comment]
> I'm hoping this would prevent an ErrorProne warning of HidingField.

I'm not familiar with the inner workings of ErrorProne, but if you define an annotation extension as you describe, it will definitely be there and have all arguments present.

>  Even better to solve this problem, is to be able to annotate all child classes of a given class with certain annotation:

You can do that (in theory, I have not tried). Add the `@Inherited` annotation to `@SuppressWarnings` via extension and then add `@SuppressWarnings` to your base service class.

**Comment by superxiao** [comment]
Wow! I did not know `@Inherited` existed, you learn something every day. `@SupressWarnings` is not something we use a lot and it sounds fine to me that it becomes overall inherited. Anothe genius use of annotation extension.
