### ISSUE TITLE
Why is there `StackOverflowError` in IJ?

### ISSUE THREAD

**Issue by SettingDust** [manifold-systems/manifold#615]
There are so many stacks. Below are some of them.

https://gist.github.com/SettingDust/81a1b406bd929fb94b1543e6502f1d0a

**Comment by rsmckinney** [comment]
Can you provide steps to reproduce the exception? Also it helps to provide the versions of IJ,  manifold plugin, manifold, and java you are using. Thanks

**Comment by SettingDust** [comment]
I'm not quite sure how to reproduce. How can I find it?

IU-242.20224.300
jdk 21
Manifold IJ 2024.1.6
Manifold 2024.1.30

**Comment by rsmckinney** [comment]
Just to be clear. Are you saying you ran into the StackOverflowError don't know how it happened and also can't reproduce it?

**Comment by SettingDust** [comment]
I can reproduce but don't know hot to find out a minimal reproduce. It's throwing when typing in a file

**Comment by rsmckinney** [comment]
Can you provide some context? For instance, project build file[s], the file in question and where/what you edit in the file that causes the error. Thanks.

**Comment by SettingDust** [comment]
> Can you provide some context? For instance, project build file[s], the file in question and where/what you edit in the file that causes the error. Thanks.

https://gist.github.com/SettingDust/9bd8720adbc03a5ba099b1d86e02b2a6

**Comment by rsmckinney** [comment]
Your version of IJ is IU-242.20224.300, so you must use the latest manifold ij plugin 2024.1.7

**Comment by SettingDust** [comment]
> Your version of IJ is IU-242.20224.300, so you must use the latest manifold ij plugin 2024.1.7

Auto updated after submitted. Still erroring
