### ISSUE TITLE
Share fields and methods from other class

### ISSUE THREAD

**Issue by abccbaandy** [manifold-systems/manifold#616]
I want to do something like this
https://stackoverflow.com/questions/56041893/java-how-to-share-field-and-method-between-classes

And those Delegate pattern is not work well, because the class is used by many framework/lib (ex: Spring data, jackson)
So, I need a pure pojo in the runtime instead some magic method.

**Describe the solution you'd like**
I think have an annotation `@Extends`, so I can do something like this.
````java
@Extends(parent1.class)
@Extends(parent2.class)
public class Domain {
````

**Comment by rsmckinney** [comment]
Hi @abccbaandy. I read your stackoverflow link. If I understand correctly, essentially you would like to merge all the fields and get/set methods from one class into another. Manifold does not provide a feature for that, however there are workarounds involving manifold extension classes that may work for you.

For instance, you could use `@Extension` to add get/set methods. Since you can't add fields, you can store state in a thread-safe static map.

Something like this:
```java
package extensions.org.example.Domain1;

@import org.example.Domain1;

@Extension
public class MyDomain1Extension {
   private static final ThreadLocal<Map<String, Map<String, Object>>> _state = ThreadLocal.withInitial(WeakHashMap::new);

  public static Foo getFoo(@This Domain1 thiz) {
    return (Foo)getState(thiz, "Foo");
  }
  public static void setFoo(@This Domain1 thiz, Foo value) {
    setState(thiz, "Foo", value);
  }

  // more get/set methods
  // . . .

  // thread-safe state access

  private static Object getState(Domain1 thiz, String propertyName) {
     return _state.get().computeIfAbsent(thiz, __-> new HashMap<>()).get(propertyName);
  }

  private static void setState(Domain1 thiz, String propertyName, Object value) {
     _state.get().computeIfAbsent(thiz, __-> new HashMap<>()).set(propertyName, value);
  }
}
```

Another idea would involve modifying the JSON schema to include the additional state you need, if that suits your needs.

**Comment by rsmckinney** [comment]
Ah, after re-reading #617 I think what may be the answer here is [manifold-delegation](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-delegation/README.md). This lets you share properties via interface composition. Basically, just create interfaces for the classes you want to share and use `@link` to connect them to your domain.

```java
public class Domain implements Alpha, Beta {
  @link Alpha alpha = new AlphaImpl();
  @link Beta beta = new BetaImpl();
}

public interface Alpha {
  String getApple();
  void setApple(String value);

  String getBanana();
  void setBanana(String value);
}

// a class having shared state for a domain
public class AlphaImpl implements Alpha {
  private String apple;
  private String banana;

  String getApple() {return alpha;}
  void setApple(String value) {apple= value};

  String getBanana() {return banana;}
  void setBanana(String value) {banana= value};
}
. . .
```

Note, you can reduce Java's boilerplate wrt getters/setters etc. using [manifold-props](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-props).

```java
public class Domain implements Alpha, Beta {
  @link Alpha alpha = new AlphaImpl();
  @link Beta beta = new BetaImpl();
}

public interface Alpha {
  @var String apple;
  @var String banana;
}

// a class having shared state for a domain
public class AlphaImpl implements Alpha {
  @override @var String apple;
  @override @var String banana;
}
. . .
```

**Comment by rsmckinney** [comment]
That example should work without issue. I just created simple example to exercise it, which works well in IntelliJ.
```java
import manifold.ext.delegation.rt.api.link;
import manifold.ext.delegation.rt.api.part;

public class Whatevva {

    public static class Domain implements Alpha, Beta {
        @link Alpha alpha = new AlphaImpl();
        @link Beta beta = new BetaImpl();
    }

    public interface Alpha {
        String getApple();
        void setApple(String value);

        String getBanana();
        void setBanana(String value);
    }
    public interface Beta {
        String getPear();
        void setPear(String value);
    }

    // a class having shared state for a domain, note @part is optional, read docs for details
    @part public static class AlphaImpl implements Alpha {
        private String apple;
        private String banana;

        public String getApple() {return apple;}
        public void setApple(String value) {apple= value;};

        public String getBanana() {return banana;}
        public void setBanana(String value) {banana= value;};
    }

   @part public static class BetaImpl implements Beta {
        private String pear;

        public String getPear() {return pear;}
        public void setPear(String value) {pear= value;}
    }


    public static void main(String[] args) {
        Domain domain = new Domain();
        domain.setApple("apple");
        System.out.println(domain.getApple());
        domain.setPear("pear");
        System.out.println(domain.getPear());
    }
}

```
If this does not work for you, your build or IJ may have a config issue.

Note, this is probably the most concise and comprehensive way to mix in (or share) state and behavior from other classes with a domain class, esp. considering the domain class can override behavior. Also note, extension methods are really more for the case where you can't modify the domain class, thus it must be extended external to its definition, hence extension classes.

Please let me know if you have questions. Thanks.
