### ISSUE TITLE
Manifold CSV : "IllegalStateException: Token length < value length" if no value in last column of a row

### ISSUE THREAD

**Issue by TelKel81** [manifold-systems/manifold#622]
Fails 100% of time that there's no value in the last column of the CSV
Succeeds 100% of time if there's value in the last column.
	
Raw text :
col1;col2
1;
1;

That crashes. If I add a value in EACH col2, no crash.

**Comment by rsmckinney** [comment]
Fix available with version 2024.1.33.  Thanks for reporting this!
