### ISSUE TITLE
The manifold.systems site appears to be down

### ISSUE THREAD

**Issue by eoliphan** [manifold-systems/manifold#626]
Hi, I'm getting this when accessing the site:

![Screenshot 2024-10-14 at 10 51 45 AM](https://github.com/user-attachments/assets/4f137660-9632-4f60-ae92-fcffe61fa098)

**Comment by ByThePowerOfScience** [comment]
Seems like it's getting blocked by a popular content filter.  My university wifi (eduroam) is blocking the site as well.

**Comment by rsmckinney** [comment]
The filter may be blocking non-https sites. My domain provider makes it difficult to enable.
