### ISSUE TITLE
Compilation error: IntelliJ IDEA build tool and String Templates

### ISSUE THREAD

**Issue by marksto** [manifold-systems/manifold#67]
**Describe the bug**
[String Templates](http://manifold.systems/docs.html#templating) can't be turned off. This causes a compilation error in _IntelliJ IDEA_.

**To Reproduce**
Test project: https://github.com/marksto/spring-manifold-test

Open it in the _IntelliJ IDEA_.

Pay attention on how it highlights the syntax of the `@Value` annotation's value.

<img width="270" alt="Снимок экрана 2019-04-13 в 15 25 09" src="https://user-images.githubusercontent.com/29752171/56079918-76a5c900-5e03-11e9-87dc-8fd1809dabab.png">

Try to build or run the project with _IntelliJ IDEA_ built-in tools:

<img width="1035" alt="Снимок экрана 2019-04-13 в 15 42 42" src="https://user-images.githubusercontent.com/29752171/56079917-71487e80-5e03-11e9-8a49-da26182865f4.png">

**Expected behavior**
The absent `strings` plugin argument actively disables **Manifold**'s string templating.
Project compiles without errors.
There is no need in extra `@DisableStringLiteralTemplates` annotations (this is too invasive).

**Desktop (please complete the following information):**
- OS Type & Version: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"
- Java/JDK version: Java version: 1.8.0_172, vendor: Oracle Corporation
- IntelliJ IDEA version: 2018.1.2
- Manifold version: 0.59-alpha
- Manifold IntelliJ plugin version: 0.59-alpha

**Additional context**
The `mvn clean install` (and the test suite in particular) runs successfully.
One can mitigate this with extra `@DisableStringLiteralTemplates` annotations (see #44).

**Comment by rsmckinney** [comment]
There is a condition in the IJ plugin where the `strings` javac plugin argument is ignored, fixing this now...

**Comment by rsmckinney** [comment]
ad7766d1 scott on 4/19/2019 at 11:39 PM
Fix available in plugin release 0.63-alpha

**Comment by 2720851545** [comment]
Can add a configuration to change the `$` to another symbol?

**Comment by 2720851545** [comment]
@rsmckinney 

Can add a configuration to change the `$` to another symbol?

**Comment by rsmckinney** [comment]
@2720851545 There is no API to configure the `$` for this, however you can turn off `$` expressions so that only `${expr}` expressions are enabled. This strategy usually helps when the `$` conflicts with an existing codebase or library usage.  See https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-strings#disabling-simple-foo-expressions. 
Does that help?

**Comment by 2720851545** [comment]
Yes, this feature will be previewed in a future version
