### ISSUE TITLE
Support for Type Manifolds instantiation with reflection

### ISSUE THREAD

**Issue by marksto** [manifold-systems/manifold#69]
**Is your feature request related to a problem? Please describe.**
There are no easy-to-use means for Type Manifolds instantiation with the Java Reflection in case its backing JSON Schema has required properties, because of the absence of a no-args constructor in generated sources (which imho is a correct and expected behaviour).

**Describe the solution you'd like**
This would depend on some sort of utility for required properties enumeration retrieval. Then the instantiation will be possible with the `java.lang.reflect`, e.g.:

```
Object typeInstance;
try {
    Class clazz = Class.forName(typeClassName);

    Method creator = Arrays.stream(clazz.getDeclaredMethods())
            .filter(method -> method.getName().equals("create"))
            .findFirst().get();

    List<String> requiredProps = /* the missing piece */;
    
    Object[] args = /* end user app's business logic, using 'requiredProps' 
                       and retrieving them e.g. from a HTTP response params */;

    typeInstance = creator.invoke(null, args);
} catch (Exception e) {
    ...
}
```

The whole snippet, of course, may be provided as a dedicated type-safe instantiation utility for Type Manifolds backed by JSON Schema. This would play even nicer.

**Describe alternatives you've considered**
I've tried a general approach for such cases, an [Objenesis](http://objenesis.org/index.html) library, that makes it possible to bypass an absence of a no-arg constructor.

Unfortunately, the following exception is thrown when it tries to add an ad-hoc constructor with no arguments:

```
Exception in thread "main" java.lang.InstantiationError: com.tera.kulta.schemas.Design
	at sun.reflect.GeneratedSerializationConstructorAccessor1.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at com.tera.kulta.util.Utils.main(Utils.java:27)
```

It seems to me that it won't be possible to bypass this for Manifold's types that simple, right?

**Comment by rsmckinney** [comment]
Hi @marksto.

You may not have noticed but the Java classes corresponding with the JSON manifold are _interfaces_.  More specifically, they are _structural interfaces_ that work directly on JSON bindings -- there are no POJOs or other go-between classes.  This means you can directly cast any JSON bindings (or any `javax.script.Bindings` instance) to any structural interface:
```java
@Structural
public interface Person {
  String getName();
  void setName(String name);
...
} 

import manifold.ext.DataBindings;

DataBindings dataBindings = new DataBindings();
dataBindings.put("name", "Scott");

Person person = (Person) dataBindings;
String name = person.getName();
```

Therefore, you don't need a constructor at all, simply cast an empty `Bindings` to any JSON manifold type.  Voila!

```java
MyJsonSchemaType mine = (MyJsonSchemaType) new DataBindings(); // mic drop
...
```

**Comment by marksto** [comment]
Wow.
Indeed.
Applause! 👏
