### ISSUE TITLE
Indentation/Whitespace retention option

### ISSUE THREAD

**Issue by sporkisfaster** [manifold-systems/manifold#76]
Currently it appears that ManTL only supports stripping of indentation and whitespace on generation. There are some use cases where it would be preferred to keep or more specifically be able to set indentation on the template so the generated code will honor the spacing and indentation the user decides. An example of this is a feature covered in StringTemplate here: https://github.com/antlr/stringtemplate4/blob/master/doc/indent.md

**Describe the solution you'd like**
It is desired that there be some kind of syntax available to adjust indentation and whitespace as the user creating the template sees fit.

**Additional context**
Below is a snippet from the discussion of options in the manifold gtiter chat:

> after more consideration I think perhaps the one problem you'll have will be indentation
> 
> where I see the problem is when you'd be using include to nest a sub-template; when you're generating code you want to retain the indentation immediately preceding the <%@ include ... %>
> I can add support for that in a number of ways, not sure which, i'm thinking:
> 
> <%@ nest ... %>
> where it behaves exactly as include, but retains indentation
> i prefer this over adding an argument or some other overload for include

**Comment by rsmckinney** [comment]
In progress

**Comment by rsmckinney** [comment]
Feature available in release 0.65-alpha
