### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by Anuken** [manifold-systems/manifold#77]
I would like to ask if Manifold works in ordinary Android applications built using Gradle in IntelliJ. Specifically, I am planning on only using the `manifold` and `manifold-ext` modules in Static mode.

If Manifold is indeed compatible with Android, I am also curious which Java 8 language features are required in these modules, as Android only supports a subset of Java 8/7 language features up to Android API Level 24. If any of these Java 8 features are used, it would severely limit the number of phones that can be targeted-- see [this page](https://developer.android.com/studio/write/java8-support#supported_features) for more explanation.

**Comment by rsmckinney** [comment]
Hi @Anuken.  Currently Manifold works with standard Java JDKs 8 - 12, it does not yet work with Android. In theory the static features of Manifold, most of them, can work with Android, but at the moment they are not separated from non-static features. Once the Manifold officially releases and becomes non-beta software (sometime this summer) other projects, like Android and Kotlin support, will receive more attention.  Cheers.

**Comment by Anuken** [comment]
Alright, thanks for the answer!

**Comment by rsmckinney** [comment]
Reopen for consideration

**Comment by Clement-Jean** [comment]
Are there any news on this ?

**Comment by rsmckinney** [comment]
Hi @Clement-Jean.  Android support is on the radar now; it will be supported directly in the next major release, albeit with a subset of Manifold's existing features (most of them).  Are there specific features you are most interested in?

There's another feature on the horizon that may be useful for Android devs: https://github.com/manifold-systems/manifold/issues/95.  Essentially you could use the inlining tool to expand Manifold usage to boilerplate Java 8 code, which should be compatible with Android.

Neither of these features is in development just yet, but both are a priority for the next major release.

**Comment by Clement-Jean** [comment]
Hi, I’m interested in @Extension and @This for now.

I would like to help for android port (at least if you need)

**Comment by Anuken** [comment]
Any progress on this feature?

**Comment by rsmckinney** [comment]
@Anuken Hi.  Not yet :(

**Comment by rsmckinney** [comment]
work in progress...

**Comment by rsmckinney** [comment]
implemented in release 2020.1.13
