### ISSUE TITLE
Is an Netbeans extension on the roadmap?

### ISSUE THREAD

**Issue by 54446776** [manifold-systems/manifold#78]
Manifold is great and I hope to use it with Netbeans 11 IDE :)

Manifold Sample Project can be compiled and run(with test) in netbeans 11. 
Because these manifold class files don't have corresponding source files, so Netbeans complain these manifold generated packages and classes doesn't exist inside java code editor.

**Comment by rsmckinney** [comment]
@54446776 thanks!  [IntelliJ](https://www.jetbrains.com/idea/download) provides comprehensive Java IDE support for Manifold via the [Manifold plugin](https://plugins.jetbrains.com/plugin/10057-manifold).  At present there are no plans to support additional IDEs; the 1.0 release plan has room only for one IDE plugin.  After the 1.0 dust settles a new plan could include support for additional IDEs, mainly Eclipse and Netbeans.  Watch this issue for updates.  Thanks again.

**Comment by rsmckinney** [comment]
Eclipse is the only other IDE under consideration.

**Comment by WesleyKhoiVo** [comment]
IntelliJ is not free for enterprise, it just free for community use, so I think support NetBeans or Eclipse is better. I know IntelliJ is supported because it use same codebase with Android Studio, but IntelliJ is not free as Android Studio. I am a NetBeans user :)

**Comment by rsmckinney** [comment]
@WesleyKhoiVo Eclipse support is coming soon(ish). There are no plans to support Netbeans at this time.
