### ISSUE TITLE
Extension method navigate to definition in IntelliJ links to the extended class

### ISSUE THREAD

**Issue by elshimone** [manifold-systems/manifold#80]
**Describe the bug**
In IntelliJ, Ctrl-Clicking on a usage of an extension method which is not anotated with @This links to the decompiled source of the extended class, rather than the definition of the extension method.

**To Reproduce**
1. Add the following extension class definition to the sample rest application

```java
package abc.extensions.java.lang.String;

import manifold.ext.api.*;

@Extension
public class MyStringExtension {

  public static void print(@This String thiz) {
    System.out.println(thiz);
  }

  @Extension // required for static extension methods
  public static String lineSeparator() {
    return System.lineSeparator();
  }
}
```

2. Add some code which uses the lineSeparator() extension method, e.g.

```java
"borked".lineSeparator();
```

3. Ctrl-Click on the lineSeparator() method; the IDE navigates to the decompiled source of java.lang.String

**Expected behavior**
I would expect it to navigate to the lineSeparator method definition in MyStringExtension.java

**Screenshots**
N/A

Desktop (please complete the following information):

OS Type & Version: Mac OSX 10.13.6 (17G6030)

- Java/JDK version: Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
- IntelliJ IDEA version: IntelliJ IDEA 2019.1.1 (Community Edition) Build #IC-191.6707.61, built on April 16, 2019
- Manifold version: 0.65-alpha
- Manifold IntelliJ plugin version: 0.65-alpha

**Additional context**
None

**Stack trace**
N/A

**Comment by rsmckinney** [comment]
58f97882 scott on 5/14/2019 at 5:35 PM

(fixed in IJ plugin version 0.66-alpha)
