### ISSUE TITLE
Multiple Manifolds in same module

### ISSUE THREAD

**Issue by Xiakitl** [manifold-systems/manifold#86]
**Describe the bug**
When writing my own manifolds and registering them in the same module (so in the same META-INF/services file), IntelliJ throws an error, saying that the file could not be found within the jar.
When there is only one Manifold mentioned in the file, everything works fine.

**To Reproduce**
1. Write at least two Manifolds (and their model, and generator class)
2. register them in the services file
3. build the jar
4. include the jar as maven dependency in another module/project

**Expected behavior**
The services file gets found and all registered manifolds are detected. 

**Desktop (please complete the following information):**
- OS Type & Version: Ubuntu 18.04
- Java/JDK version: 1.8
- IntelliJ IDEA version: 2019.1.2
- Manifold version: 0.65-alpha
- Manifold IntelliJ plugin version: 0.65-alpha
I'll 

**Stacktrace**
Coming soon

**Comment by rsmckinney** [comment]
Can you provide the contents of your service file?  Note service impl class names must be placed on separate lines with no separator characters between them e.g.,
```
com.example.Foo
com.example.Bar
```

**Comment by Xiakitl** [comment]
Yeah, I did so. Encoded with UTF-8 without BOM.

```
com.xiakitl.eventgenerator.eventinterface.EventInterfaceTypeManifold
com.xiakitl.eventgenerator.event.EventTypeManifold
```

**Comment by rsmckinney** [comment]
Both of these classes implement the interface named by the enclosing file?

Also, if you can, please provide the stack trace.  Better, provide a sample project demonstrating problem.  Thanks!

**Comment by rsmckinney** [comment]
@Xiakitl have you worked through this issue, please update, otherwise it will close, thanks
