### ISSUE TITLE
GraphQL Support for .graphqls files.

### ISSUE THREAD

**Issue by martinlau** [manifold-systems/manifold#89]
**Describe the bug**
Generally graphql queries and mutations are written as .graphql files, while schemas are .graphqls. Currently the [GqlManifold](https://github.com/manifold-systems/manifold/blob/master/manifold-deps-parent/manifold-graphql/src/main/java/manifold/graphql/type/GqlManifold.java#L33) only supports .gql and .graphql and so .graphqls files are ignored.

**To Reproduce**
1. Using the graphql sample application, rename movies.graphql to movies.graphqls
2. Try to build the project
3. Note compilation failures because the schema isn't included

**Expected behavior**
The project should work in the same way as it currently does with the schema named movies.graphql

**Desktop (please complete the following information):**
- OS Type & Version: OSX 10.14.4 (although n/a)
- Java/JDK version: 1.8 and 11
- IntelliJ IDEA version: n/a
- Manifold version: 0.65-alpha
- Manifold IntelliJ plugin version: n/a

**Comment by martinlau** [comment]
Look at that turn around time! Awesome work :)

**Comment by rsmckinney** [comment]
Thanks for pointing that out!  I hadn't known about that extension.  Fix available in version 0.68-alpha, ij plugin release awaiting jetbrains approval, usually within 2 days.  Cheers.
