### ISSUE TITLE
Graal integration

### ISSUE THREAD

**Issue by RaviH** [manifold-systems/manifold#94]
**Is your feature request related to a problem? Please describe.**
When trying to create a native-image with/for Graal, I get the exception below:

```
$ native-image -jar target/graal-micronaut-0.1.jar
Build on Server(pid: 5608, port: 50229)*
[graal-micronaut:5608]    classlist:   4,743.54 ms
[graal-micronaut:5608]        (cap):   1,639.08 ms
[graal-micronaut:5608]        setup:   2,997.04 ms
[graal-micronaut:5608]     analysis:  11,735.64 ms
Error: Unable to handle imagecp element 'manifoldclass://1960125722/'. Make sure that all imagecp entries are either directories or valid jar files.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

```

**Describe the solution you'd like**
Being able to use manifold inside Graal.

**Additional context**
I have attached the sample project. Please run:

`mvn clean package` and then: `native-image -jar target/graal-micronaut-0.1.jar`

```
$ native-image -jar target/graal-micronaut-0.1.jar
Build on Server(pid: 5608, port: 50229)
[graal-micronaut:5608]    classlist:   3,459.12 ms
[graal-micronaut:5608]        (cap):   1,419.84 ms
[graal-micronaut:5608]        setup:   1,833.39 ms
[graal-micronaut:5608]     analysis:   6,985.98 ms
Error: Unable to handle imagecp element 'manifoldclass://1205323916/'. Make sure that all imagecp entries are either directories or valid jar files.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

# rhasija ~/tmp/graal-micronaut on git:master x  C:1
$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /Users/rhasija/.sdkman/candidates/maven/current
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /Users/rhasija/.sdkman/candidates/java/1.0.0-rc-16-grl/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```

**Comment by rsmckinney** [comment]
At the moment perhaps a more practical application of Graal could involve using it as a better JIT compiler. Doing so requires Java 10+ using the following command line options:
```
-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler
```
I have not tried this, but for now using Graal as a JIT compiler seems like a useful mini project.

Other aspects of Graal, such as SubstrateVM are interesting too.  I was sucked into that world for a little while, but determined at least wrt SubstrateVM, its [current limitations](https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md) make it unsuitable for most enterprise class Java applications and most Java applications in general.

What is most confusing about Graal, though, is Oracle's overloading of the name.  "Graal" is Oracle's new JIT compiler, it is also an AOT (SubstrateVM), and a whole new polyglot JDK/JVM.

**Comment by marksto** [comment]
Indeed, one of the **Manifold**'s killer features is the _Dynamic Mode_, which makes the JVM runtime world even more open than it is by default. And that is just the opposite of what the _native image generation_ with SubstrateVM do, closing the world once and forever.

**Comment by rsmckinney** [comment]
Graal support coming soon Will be released along with Android and Kotlin support,. See https://github.com/manifold-systems/manifold/issues/181
